// Reviewed against the catalog's displayed sense, not every possible dictionary sense.
// This is a static review snapshot: adding/changing a catalog entry does not silently
// grant exercise eligibility. Update this review and the policy tests together.
export const LEXICAL_REVIEW_VERSION = 1;

// surface, reading, displayed meaning, conjugation class, transitivity, usage profile
export const REVIEWED_VERB_SENSES = [
  ["書く","かく","写；书写","godan","transitive","action"],
  ["弾く","ひく","弹奏","godan","transitive","action"],
  ["話す","はなす","说；交谈","godan","transitive","action"],
  ["待つ","まつ","等待","godan","transitive","action"],
  ["死ぬ","しぬ","死亡","godan","intransitive","death"],
  ["遊ぶ","あそぶ","玩耍","godan","intransitive","action"],
  ["読む","よむ","阅读","godan","transitive","action"],
  ["買う","かう","购买","godan","transitive","action"],
  ["切る","きる","切；剪","godan","transitive","action"],
  ["泳ぐ","およぐ","游泳","godan","intransitive","action"],
  ["行く","いく","去；前往","godan","intransitive","action"],
  ["飲む","のむ","喝","godan","transitive","action"],
  ["聞く","きく","听；询问","godan","transitive","action"],
  ["帰る","かえる","回去","godan","intransitive","action"],
  ["立つ","たつ","站立","godan","intransitive","action"],
  ["呼ぶ","よぶ","呼叫","godan","transitive","action"],
  ["急ぐ","いそぐ","赶快","godan","intransitive","action"],
  ["取る","とる","拿取","godan","transitive","action"],
  ["会う","あう","见面","godan","intransitive","action"],
  ["歌う","うたう","唱歌","godan","intransitive","action"],
  ["使う","つかう","使用","godan","transitive","action"],
  ["笑う","わらう","笑","godan","intransitive","action"],
  ["働く","はたらく","工作","godan","intransitive","action"],
  ["歩く","あるく","走路","godan","intransitive","action"],
  ["置く","おく","放置","godan","transitive","action"],
  ["脱ぐ","ぬぐ","脱下","godan","transitive","action"],
  ["騒ぐ","さわぐ","吵闹","godan","intransitive","action"],
  ["貸す","かす","借出","godan","transitive","action"],
  ["消す","けす","关闭；消除","godan","transitive","action"],
  ["持つ","もつ","持有","godan","transitive","action"],
  ["打つ","うつ","敲打","godan","transitive","action"],
  ["選ぶ","えらぶ","选择","godan","transitive","action"],
  ["飛ぶ","とぶ","飞","godan","intransitive","action"],
  ["住む","すむ","居住","godan","intransitive","action"],
  ["休む","やすむ","休息","godan","intransitive","action"],
  ["走る","はしる","奔跑","godan","intransitive","action"],
  ["知る","しる","知道","godan","transitive","experience"],
  ["入る","はいる","进入","godan","intransitive","action"],
  ["作る","つくる","制作","godan","transitive","action"],
  ["売る","うる","售卖","godan","transitive","action"],
  ["習う","ならう","学习；练习","godan","transitive","action"],
  ["言う","いう","说","godan","transitive","action"],
  ["思う","おもう","想；认为","godan","transitive","action"],
  ["払う","はらう","支付","godan","transitive","action"],
  ["洗う","あらう","清洗","godan","transitive","action"],
  ["手伝う","てつだう","帮忙","godan","transitive","action"],
  ["もらう","もらう","得到","godan","transitive","action"],
  ["拾う","ひろう","捡；拾","godan","transitive","action"],
  ["向かう","むかう","前往；面向","godan","intransitive","action"],
  ["違う","ちがう","不同；不对","godan","intransitive","state"],
  ["間に合う","まにあう","赶得上","godan","intransitive","action"],
  ["描く","えがく","描绘","godan","transitive","action"],
  ["咲く","さく","开花","godan","intransitive","event"],
  ["着く","つく","到达","godan","intransitive","action"],
  ["届く","とどく","送达；够得着","godan","intransitive","event"],
  ["泣く","なく","哭","godan","intransitive","action"],
  ["動く","うごく","移动；运转","godan","intransitive","action"],
  ["磨く","みがく","刷；磨","godan","transitive","action"],
  ["焼く","やく","烤；烧","godan","transitive","action"],
  ["開く","あく","打开；开放","godan","intransitive","event"],
  ["注ぐ","そそぐ","倒入；注入","godan","transitive","action"],
  ["防ぐ","ふせぐ","防止","godan","transitive","action"],
  ["稼ぐ","かせぐ","挣钱","godan","transitive","action"],
  ["出す","だす","拿出；提交","godan","transitive","action"],
  ["直す","なおす","修理；改正","godan","transitive","action"],
  ["渡す","わたす","交给","godan","transitive","action"],
  ["返す","かえす","归还","godan","transitive","action"],
  ["押す","おす","按；推","godan","transitive","action"],
  ["探す","さがす","寻找","godan","transitive","action"],
  ["落とす","おとす","弄掉；丢失","godan","transitive","action"],
  ["指す","さす","指；指向","godan","transitive","action"],
  ["起こす","おこす","叫醒；引起","godan","transitive","action"],
  ["勝つ","かつ","获胜","godan","intransitive","action"],
  ["役立つ","やくだつ","有用；起作用","godan","intransitive","state"],
  ["運ぶ","はこぶ","搬运","godan","transitive","action"],
  ["並ぶ","ならぶ","排队；排列","godan","intransitive","action"],
  ["学ぶ","まなぶ","学习","godan","transitive","action"],
  ["喜ぶ","よろこぶ","高兴","godan","intransitive","experience"],
  ["頼む","たのむ","拜托；点单","godan","transitive","action"],
  ["楽しむ","たのしむ","享受；期待","godan","transitive","action"],
  ["進む","すすむ","前进；进展","godan","intransitive","action"],
  ["申し込む","もうしこむ","申请；报名","godan","transitive","action"],
  ["包む","つつむ","包裹","godan","transitive","action"],
  ["分かる","わかる","明白","godan","intransitive","experience"],
  ["終わる","おわる","结束","godan","intransitive","action"],
  ["始まる","はじまる","开始","godan","intransitive","event"],
  ["変わる","かわる","改变","godan","intransitive","action"],
  ["戻る","もどる","返回","godan","intransitive","action"],
  ["座る","すわる","坐","godan","intransitive","action"],
  ["困る","こまる","为难；困扰","godan","intransitive","experience"],
  ["送る","おくる","发送；送行","godan","transitive","action"],
  ["渡る","わたる","渡过","godan","intransitive","action"],
  ["乗る","のる","乘坐","godan","intransitive","action"],
  ["降る","ふる","下（雨雪）","godan","intransitive","event"],
  ["守る","まもる","遵守；保护","godan","transitive","action"],
  ["眠る","ねむる","睡眠","godan","intransitive","action"],
  ["喋る","しゃべる","说话；聊天","godan","transitive","action"],
  ["要る","いる","需要","godan","intransitive","state"],
  ["残る","のこる","留下；剩余","godan","intransitive","action"],
  ["曲がる","まがる","转弯；弯曲","godan","intransitive","action"],
  ["食べる","たべる","吃","ichidan","transitive","action"],
  ["見る","みる","看","ichidan","transitive","action"],
  ["起きる","おきる","起床","ichidan","intransitive","action"],
  ["寝る","ねる","睡觉","ichidan","intransitive","action"],
  ["教える","おしえる","教；告诉","ichidan","transitive","action"],
  ["開ける","あける","打开","ichidan","transitive","action"],
  ["閉める","しめる","关闭","ichidan","transitive","action"],
  ["借りる","かりる","借入","ichidan","transitive","action"],
  ["浴びる","あびる","淋；沐浴","ichidan","transitive","action"],
  ["忘れる","わすれる","忘记","ichidan","transitive","experience"],
  ["覚える","おぼえる","记住","ichidan","transitive","action"],
  ["出る","でる","出去","ichidan","intransitive","action"],
  ["着る","きる","穿","ichidan","transitive","action"],
  ["信じる","しんじる","相信","ichidan","transitive","action"],
  ["調べる","しらべる","调查","ichidan","transitive","action"],
  ["始める","はじめる","开始","ichidan","transitive","action"],
  ["続ける","つづける","继续","ichidan","transitive","action"],
  ["逃げる","にげる","逃跑","ichidan","intransitive","action"],
  ["助ける","たすける","帮助","ichidan","transitive","action"],
  ["いる","いる","在；有（生物）","ichidan","intransitive","existence"],
  ["できる","できる","能够；完成","ichidan","intransitive","ability"],
  ["考える","かんがえる","思考；考虑","ichidan","transitive","action"],
  ["答える","こたえる","回答","ichidan","intransitive","action"],
  ["決める","きめる","决定","ichidan","transitive","action"],
  ["止める","とめる","停止；阻止","ichidan","transitive","action"],
  ["見せる","みせる","给……看","ichidan","transitive","action"],
  ["受ける","うける","接受；参加","ichidan","transitive","action"],
  ["付ける","つける","附上；打开","ichidan","transitive","action"],
  ["集める","あつめる","收集","ichidan","transitive","action"],
  ["捨てる","すてる","丢弃","ichidan","transitive","action"],
  ["疲れる","つかれる","疲劳","ichidan","intransitive","experience"],
  ["遅れる","おくれる","迟到；延误","ichidan","intransitive","action"],
  ["降りる","おりる","下车；下来","ichidan","intransitive","action"],
  ["迎える","むかえる","迎接","ichidan","transitive","action"],
  ["伝える","つたえる","传达","ichidan","transitive","action"],
  ["生まれる","うまれる","出生","ichidan","intransitive","event"],
  ["壊れる","こわれる","坏；损坏","ichidan","intransitive","event"],
  ["足りる","たりる","足够","ichidan","intransitive","state"],
  ["似る","にる","相似","ichidan","intransitive","state"],
  ["過ぎる","すぎる","经过；超过","ichidan","intransitive","action"],
  ["落ちる","おちる","掉落","ichidan","intransitive","event"],
  ["増える","ふえる","增加","ichidan","intransitive","event"],
  ["変える","かえる","改变","ichidan","transitive","action"],
  ["届ける","とどける","送到；申报","ichidan","transitive","action"],
  ["片付ける","かたづける","收拾；整理","ichidan","transitive","action"],
  ["出かける","でかける","出门","ichidan","intransitive","action"],
  ["誘う","さそう","邀请","godan","transitive","action"],
  ["雇う","やとう","雇用","godan","transitive","action"],
  ["扱う","あつかう","对待","godan","transitive","action"],
  ["疑う","うたがう","怀疑","godan","transitive","action"],
  ["嫌う","きらう","讨厌","godan","transitive","experience"],
  ["からかう","からかう","取笑","godan","transitive","action"],
  ["祝う","いわう","庆祝","godan","transitive","action"],
  ["追う","おう","追赶","godan","transitive","action"],
  ["する","する","做","irregular","transitive","action"],
  ["来る","くる","来","irregular","intransitive","action"],
].map(([surface, reading, meaning, verbClass, transitivity, profile]) => Object.freeze({
  id: `verb:${surface}:${reading}`, domain: 'verb', surface, reading, meaning, class: verbClass, transitivity, profile, reviewVersion: LEXICAL_REVIEW_VERSION,
}));

// All adjective senses are reviewed for the currently taught class-specific forms.
export const REVIEWED_ADJECTIVE_SENSES = [
  ["高い","たかい","高；贵","i"],
  ["安い","やすい","便宜","i"],
  ["大きい","おおきい","大","i"],
  ["小さい","ちいさい","小","i"],
  ["新しい","あたらしい","新","i"],
  ["古い","ふるい","旧；古老","i"],
  ["いい","いい","好","i"],
  ["悪い","わるい","坏；不好","i"],
  ["暑い","あつい","炎热","i"],
  ["寒い","さむい","寒冷","i"],
  ["熱い","あつい","烫；热","i"],
  ["冷たい","つめたい","冰冷","i"],
  ["暖かい","あたたかい","温暖","i"],
  ["涼しい","すずしい","凉爽","i"],
  ["忙しい","いそがしい","忙碌","i"],
  ["楽しい","たのしい","愉快","i"],
  ["面白い","おもしろい","有趣","i"],
  ["難しい","むずかしい","困难","i"],
  ["易しい","やさしい","容易","i"],
  ["優しい","やさしい","温柔","i"],
  ["美味しい","おいしい","好吃","i"],
  ["まずい","まずい","难吃；糟糕","i"],
  ["早い","はやい","早","i"],
  ["遅い","おそい","迟；慢","i"],
  ["速い","はやい","快速","i"],
  ["近い","ちかい","近","i"],
  ["遠い","とおい","远","i"],
  ["長い","ながい","长","i"],
  ["短い","みじかい","短","i"],
  ["多い","おおい","多","i"],
  ["少ない","すくない","少","i"],
  ["明るい","あかるい","明亮；开朗","i"],
  ["暗い","くらい","昏暗","i"],
  ["重い","おもい","重","i"],
  ["軽い","かるい","轻","i"],
  ["強い","つよい","强","i"],
  ["弱い","よわい","弱","i"],
  ["可愛い","かわいい","可爱","i"],
  ["怖い","こわい","可怕","i"],
  ["痛い","いたい","疼痛","i"],
  ["眠い","ねむい","困倦","i"],
  ["欲しい","ほしい","想要","i"],
  ["赤い","あかい","红","i"],
  ["白い","しろい","白","i"],
  ["黒い","くろい","黑","i"],
  ["青い","あおい","蓝；青","i"],
  ["丸い","まるい","圆","i"],
  ["甘い","あまい","甜","i"],
  ["辛い","からい","辣","i"],
  ["若い","わかい","年轻","i"],
  ["かっこいい","かっこいい","帅；酷","i"],
  ["静か","しずか","安静","na"],
  ["元気","げんき","精神；健康","na"],
  ["親切","しんせつ","亲切","na"],
  ["便利","べんり","方便","na"],
  ["不便","ふべん","不方便","na"],
  ["簡単","かんたん","简单","na"],
  ["複雑","ふくざつ","复杂","na"],
  ["上手","じょうず","擅长","na"],
  ["下手","へた","不擅长","na"],
  ["好き","すき","喜欢","na"],
  ["嫌い","きらい","讨厌","na"],
  ["きれい","きれい","漂亮；干净","na"],
  ["有名","ゆうめい","有名","na"],
  ["大切","たいせつ","重要；珍贵","na"],
  ["必要","ひつよう","必要","na"],
  ["暇","ひま","空闲","na"],
  ["賑やか","にぎやか","热闹","na"],
  ["丈夫","じょうぶ","结实；健康","na"],
  ["安全","あんぜん","安全","na"],
  ["危険","きけん","危险","na"],
  ["自由","じゆう","自由","na"],
  ["真面目","まじめ","认真","na"],
  ["丁寧","ていねい","礼貌；细致","na"],
  ["特別","とくべつ","特别","na"],
  ["普通","ふつう","普通","na"],
  ["変","へん","奇怪","na"],
  ["幸せ","しあわせ","幸福","na"],
  ["残念","ざんねん","遗憾","na"],
  ["素敵","すてき","出色；迷人","na"],
  ["無理","むり","勉强；不可能","na"],
  ["十分","じゅうぶん","充分","na"],
  ["可能","かのう","可能","na"],
  ["自然","しぜん","自然","na"],
  ["健康","けんこう","健康","na"],
  ["新鮮","しんせん","新鲜","na"],
  ["熱心","ねっしん","热心","na"],
  ["心配","しんぱい","担心","na"],
  ["楽","らく","轻松","na"],
  ["快適","かいてき","舒适","na"],
  ["正直","しょうじき","诚实","na"],
].map(([surface, reading, meaning, adjectiveClass]) => Object.freeze({
  id: `adjective:${surface}:${reading}`, domain: 'adjective', surface, reading, meaning, class: adjectiveClass,
  profile: 'adjective', reviewVersion: LEXICAL_REVIEW_VERSION,
}));

export const REVIEWED_LEXICAL_SENSES = Object.freeze([...REVIEWED_VERB_SENSES, ...REVIEWED_ADJECTIVE_SENSES]);
const bySurface = new Map(REVIEWED_LEXICAL_SENSES.map(sense => [`${sense.domain}:${sense.surface}`, sense]));
export function reviewedLexicalSense(item) {
  if (!item || typeof item.surface !== 'string') return null;
  const domain = item.domain ?? (['i', 'na'].includes(item.class) ? 'adjective' : 'verb');
  const sense = bySurface.get(`${domain}:${item.surface}`);
  // Missing optional fields are allowed for old internal callers; supplied identity
  // fields must match. A new reading or changed gloss always needs a new review.
  return sense && sense.class === item.class
    && (item.reading == null || item.reading === sense.reading)
    && (item.meaning == null || item.meaning === sense.meaning) ? sense : null;
}
