export default [
  {"id":"usage:youtosuru:verb:弾く:ひく","senseId":"verb:弾く:ひく","meaning":"弹奏","form":"youtosuru","scene":"弟弟爱逞强，没练过的曲子也不看谱。","before":[{"text":"弟は初めての曲でも、楽譜を見ずに","reading":"おとうとははじめてのきょくでも、がくふをみずに"}],"after":[{"text":"。"}],"translation":"弟弟即便碰到第一次接触的曲子，也试图不看乐谱弹奏。","review":"approved"},
  {"id":"usage:youtosuruPast:verb:弾く:ひく","senseId":"verb:弾く:ひく","meaning":"弹奏","form":"youtosuruPast","scene":"在姐姐面前试弹吉他，却紧张僵住。","before":[{"text":"私は姉の前でギターを","reading":"わたしはあねのまえでギターを"}],"after":[{"text":"が、緊張で指が動かなかった。","reading":"が、きんちょうでゆびがうごかなかった。"}],"translation":"我试图在姐姐面前弹吉他，却紧张得手指动不了。","review":"approved"},
  {"id":"usage:youtosuruNegative:verb:弾く:ひく","senseId":"verb:弾く:ひく","meaning":"弹奏","form":"youtosuruNegative","scene":"女儿摸着新买的钢琴，却不肯试弹。","before":[{"text":"娘は新しいピアノに触るだけで、まだ","reading":"むすめはあたらしいピアノにさわるだけで、まだ"}],"after":[{"text":"。"}],"translation":"女儿只是摸摸新钢琴，还不肯弹。","review":"approved"},
  {"id":"usage:youtosuruNegativePast:verb:弾く:ひく","senseId":"verb:弾く:ひく","meaning":"弹奏","form":"youtosuruNegativePast","scene":"宴会上大家再三恳求，父亲仍不肯弹。","before":[{"text":"父は何度頼んでも、宴会では三味線を","reading":"ちちはなんどたのんでも、えんかいではしゃみせんを"}],"after":[{"text":"。"}],"translation":"无论请求多少次，父亲当时都不肯在宴会上弹三味线。","review":"approved"},
  {"id":"usage:youtosuru:verb:いる:いる","senseId":"verb:いる:いる","meaning":"在；有（生物）","form":"youtosuru","scene":"女儿一感到不安，丈夫就尽量陪着她。","before":[{"text":"娘が不安がると、夫はできるだけそばに","reading":"むすめがふあんがると、おっとはできるだけそばに"}],"after":[{"text":"。"}],"translation":"女儿感到不安时，丈夫就设法尽量待在她身边。","review":"approved"},
  {"id":"usage:youtosuruPast:verb:いる:いる","senseId":"verb:いる:いる","meaning":"在；有（生物）","form":"youtosuruPast","scene":"探视结束了，仍想留在母亲病房。","before":[{"text":"私は母の病室に","reading":"わたしはははのびょうしつに"}],"after":[{"text":"が、看護師に退室を促された。","reading":"が、かんごしにたいしつをうながされた。"}],"translation":"我试图留在母亲的病房里，但护士催促我离开。","review":"approved"},
  {"id":"usage:youtosuruNegative:verb:いる:いる","senseId":"verb:いる:いる","meaning":"在；有（生物）","form":"youtosuruNegative","scene":"雷声吓到了儿子，他不肯独自在家。","before":[{"text":"息子は雷が怖くて、","reading":"むすこはかみなりがこわくて、"},{"text":"一人","reading":"ひとり"},{"text":"では家に","reading":"ではいえに"}],"after":[{"text":"。"}],"translation":"儿子怕雷，不肯一个人在家待着。","review":"approved"},
  {"id":"usage:youtosuruNegativePast:verb:いる:いる","senseId":"verb:いる:いる","meaning":"在；有（生物）","form":"youtosuruNegativePast","scene":"哥哥和父亲吵架，当晚不肯留在家里。","before":[{"text":"父とけんかした兄は、その晩、家に","reading":"ちちとけんかしたあには、そのばん、いえに"}],"after":[{"text":"。"}],"translation":"和父亲吵了架的哥哥，那天晚上不肯待在家里。","review":"approved"},
  {"id":"usage:youtosuru:verb:落ちる:おちる","senseId":"verb:落ちる:おちる","meaning":"掉落","form":"youtosuru","scene":"看见箱子悬在架子边，急忙伸手托住。","before":[{"text":"今にも棚から","reading":"いまにもたなから"}],"after":[{"text":"箱を、両手で支えた。","reading":"はこを、りょうてでささえた。"}],"translation":"用双手托住了眼看要从架子上掉下来的箱子。","note":"这里描述箱子即将掉落，不表示箱子有意图。","review":"approved"},
  {"id":"usage:youtosuruPast:verb:落ちる:おちる","senseId":"verb:落ちる:おちる","meaning":"掉落","form":"youtosuruPast","scene":"猫碰歪了花瓶，母亲赶紧伸手稳住。","before":[{"text":"花瓶が棚から","reading":"かびんがたなから"}],"after":[{"text":"が、母が素早く押さえた。","reading":"が、ははがすばやくおさえた。"}],"translation":"花瓶眼看要从架子上掉下来，但母亲迅速按住了它。","note":"表示当时即将掉落，句中母亲及时阻止了掉落。","review":"approved"},
];
