// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:tsutsu:verb:着る:きる","senseId":"verb:着る:きる","meaning":"穿","form":"tsutsu","scene":"穿外套准备出门时告诉家人明天的安排。","before":[{"text":"コートを","reading":"コートを"}],"after":[{"text":"、家族に明日の予定を話した。","reading":"、かぞくにあしたのよていをはなした。"}],"translation":"一边穿外套，一边告诉家人明天的安排。","review":"approved"},
  {"id":"usage:tsutsu:verb:続ける:つづける","senseId":"verb:続ける:つづける","meaning":"继续","form":"tsutsu","scene":"继续练习的同时记录技术进步。","before":[{"text":"練習を","reading":"れんしゅうを"}],"after":[{"text":"、技術の進歩を記録した。","reading":"、ぎじゅつのしんぽをきろくした。"}],"translation":"一边继续练习，一边记录了技术的进步。","review":"approved"},
  {"id":"usage:tsutsu:verb:助ける:たすける","senseId":"verb:助ける:たすける","meaning":"帮助","form":"tsutsu","scene":"帮助同事搬运资料并核对清单。","before":[{"text":"同僚を","reading":"どうりょうを"}],"after":[{"text":"、"},{"text":"持ち物","reading":"もちもの"},{"text":"の一覧を確認した。","reading":"のいちらんをかくにんした。"}],"translation":"一边帮助同事，一边确认了物品清单。","review":"approved"},
  {"id":"usage:tsutsu:verb:考える:かんがえる","senseId":"verb:考える:かんがえる","meaning":"思考；考虑","form":"tsutsu","scene":"考虑方案时比较各项费用。","before":[{"text":"計画を","reading":"けいかくを"}],"after":[{"text":"、それぞれの費用を比べた。","reading":"、それぞれのひようをくらべた。"}],"translation":"一边考虑计划，一边比较了各项费用。","review":"approved"},
  {"id":"usage:tsutsu:verb:決める:きめる","senseId":"verb:決める:きめる","meaning":"决定","form":"tsutsu","scene":"逐日确定旅行安排时同步估算所需费用。","before":[{"text":"旅行の日程を一日ずつ","reading":"りょこうのにっていをいちにちずつ"}],"after":[{"text":"、必要な費用も計算した。","reading":"、ひつようなひようもけいさんした。"}],"translation":"一边逐日确定旅行日程，一边也计算所需费用。","review":"approved"},
  {"id":"usage:tsutsu:verb:見せる:みせる","senseId":"verb:見せる:みせる","meaning":"给……看","form":"tsutsu","scene":"给客户看设计图并说明修改处。","before":[{"text":"顧客に設計図を","reading":"こきゃくにせっけいずを"}],"after":[{"text":"、変更点を説明した。","reading":"、へんこうてんをせつめいした。"}],"translation":"一边给客户看设计图，一边说明了修改处。","review":"approved"},
  {"id":"usage:tsutsu:verb:付ける:つける","senseId":"verb:付ける:つける","meaning":"附上；打开","form":"tsutsu","scene":"在家给衬衫缝纽扣时听广播新闻。","before":[{"text":"シャツにボタンを","reading":"シャツにボタンを"}],"after":[{"text":"、ラジオのニュースを聞いた。","reading":"、ラジオのニュースをきいた。"}],"translation":"一边给衬衫缝纽扣，一边听广播新闻。","review":"approved"},
  {"id":"usage:tsutsu:verb:捨てる:すてる","senseId":"verb:捨てる:すてる","meaning":"丢弃","form":"tsutsu","scene":"在办公室清理旧文件时听广播新闻。","before":[{"text":"古い書類を","reading":"ふるいしょるいを"}],"after":[{"text":"、ラジオのニュースを聞いた。","reading":"、ラジオのニュースをきいた。"}],"translation":"一边丢弃旧文件，一边听广播新闻。","review":"approved"},
  {"id":"usage:tsutsu:verb:迎える:むかえる","senseId":"verb:迎える:むかえる","meaning":"迎接","form":"tsutsu","scene":"在车站迎接客人并接过行李。","before":[{"text":"駅で客を","reading":"えきできゃくを"}],"after":[{"text":"、荷物を受け取った。","reading":"、にもつをうけとった。"}],"translation":"一边在车站迎接客人，一边接过了行李。","review":"approved"},
  {"id":"usage:tsutsu:verb:変える:かえる","senseId":"verb:変える:かえる","meaning":"改变","form":"tsutsu","scene":"为客户逐步调整画面颜色时听取他的意见。","before":[{"text":"画面の色を少しずつ","reading":"がめんのいろをすこしずつ"}],"after":[{"text":"、顧客の意見を聞いた。","reading":"、こきゃくのいけんをきいた。"}],"translation":"一边一点点改变画面的颜色，一边听客户的意见。","review":"approved"},
  {"id":"usage:tsutsu:verb:片付ける:かたづける","senseId":"verb:片付ける:かたづける","meaning":"收拾；整理","form":"tsutsu","scene":"结束工作后边收拾桌面边考虑翌日安排。","before":[{"text":"机の上を","reading":"つくえのうえを"}],"after":[{"text":"、翌日の予定を考えた。","reading":"、よくじつのよていをかんがえた。"}],"translation":"一边收拾桌面，一边考虑第二天的安排。","review":"approved"}
];
