// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:tsutsu:verb:立つ:たつ","senseId":"verb:立つ:たつ","meaning":"站立","form":"tsutsu","scene":"他起身迎接客人，离开椅子时便开口问好。","before":[{"text":"彼は椅子から","reading":"かれはいすから"}],"after":[{"text":"、客に挨拶した。","reading":"、きゃくにあいさつした。"}],"translation":"他一边从椅子上站起身，一边向客人打招呼。","review":"approved"},
  {"id":"usage:tsutsu:verb:急ぐ:いそぐ","senseId":"verb:急ぐ:いそぐ","meaning":"赶快","form":"tsutsu","scene":"赶往车站的路上抽空联络同事。","before":[{"text":"駅へ","reading":"えきへ"}],"after":[{"text":"、同僚に連絡した。","reading":"、どうりょうにれんらくした。"}],"translation":"一边赶往车站，一边联系同事。","review":"approved"},
  {"id":"usage:tsutsu:verb:会う:あう","senseId":"verb:会う:あう","meaning":"见面","form":"tsutsu","scene":"为了采访传统手艺而走访各地工匠。","before":[{"text":"各地の職人に","reading":"かくちのしょくにんに"}],"after":[{"text":"、伝統工芸の取材を続けた。","reading":"、でんとうこうげいのしゅざいをつづけた。"}],"translation":"一边与各地的工匠见面，一边持续采访传统工艺。","review":"approved"},
  {"id":"usage:tsutsu:verb:使う:つかう","senseId":"verb:使う:つかう","meaning":"使用","form":"tsutsu","scene":"使用新软件，同时熟悉快捷键。","before":[{"text":"新しいソフトを","reading":"あたらしいソフトを"}],"after":[{"text":"、ショートカットを覚えた。","reading":"、ショートカットをおぼえた。"}],"translation":"使用新软件的同时，记住了快捷键。","review":"approved"},
  {"id":"usage:tsutsu:verb:働く:はたらく","senseId":"verb:働く:はたらく","meaning":"工作","form":"tsutsu","scene":"在家工作，同时照看年幼的孩子。","before":[{"text":"家で","reading":"いえで"}],"after":[{"text":"、幼い子を見守った。","reading":"、おさないこをみまもった。"}],"translation":"在家工作时，也照看了年幼的孩子。","review":"approved"},
  {"id":"usage:tsutsu:verb:置く:おく","senseId":"verb:置く:おく","meaning":"放置","form":"tsutsu","scene":"布置餐桌时一面放餐具一面确认座位。","before":[{"text":"食器を","reading":"しょっきを"}],"after":[{"text":"、席を確かめた。","reading":"、せきをたしかめた。"}],"translation":"一边摆放餐具，一边确认座位。","review":"approved"},
  {"id":"usage:tsutsu:verb:騒ぐ:さわぐ","senseId":"verb:騒ぐ:さわぐ","meaning":"吵闹","form":"tsutsu","scene":"孩子们吵闹着，同时追逐院中的猫。","before":[{"text":"子どもたちは","reading":"こどもたちは"}],"after":[{"text":"、庭の猫を追いかけた。","reading":"、にわのねこをおいかけた。"}],"translation":"孩子们吵闹着，同时追逐院子里的猫。","review":"approved"},
  {"id":"usage:tsutsu:verb:消す:けす","senseId":"verb:消す:けす","meaning":"关闭；消除","form":"tsutsu","scene":"课堂结束前老师边擦黑板边解答提问。","before":[{"text":"黒板の文字を","reading":"こくばんのもじを"}],"after":[{"text":"、生徒の質問に答えた。","reading":"、せいとのしつもんにこたえた。"}],"translation":"一边擦掉黑板上的字，一边回答学生的问题。","review":"approved"},
  {"id":"usage:tsutsu:verb:打つ:うつ","senseId":"verb:打つ:うつ","meaning":"敲打","form":"tsutsu","scene":"敲打鼓面，同时留意指挥的手势。","before":[{"text":"太鼓を","reading":"たいこを"}],"after":[{"text":"、指揮者の合図を見た。","reading":"、しきしゃのあいずをみた。"}],"translation":"敲打太鼓的同时，留意了指挥的手势。","review":"approved"},
  {"id":"usage:tsutsu:verb:飛ぶ:とぶ","senseId":"verb:飛ぶ:とぶ","meaning":"飞","form":"tsutsu","scene":"飞行训练中，同时确认仪表读数。","before":[{"text":"操縦士は空を","reading":"そうじゅうしはそらを"}],"after":[{"text":"、計器を確認した。","reading":"、けいきをかくにんした。"}],"translation":"飞行员在空中飞行时，确认了仪表读数。","review":"approved"},
  {"id":"usage:tsutsu:verb:休む:やすむ","senseId":"verb:休む:やすむ","meaning":"休息","form":"tsutsu","scene":"在室内稍作休息，听着窗外的雨声。","before":[{"text":"少し","reading":"すこし"}],"after":[{"text":"、窓の外の雨音を聞いた。","reading":"、まどのそとのあまおとをきいた。"}],"translation":"一边稍作休息，一边听窗外的雨声。","review":"approved"},
  {"id":"usage:tsutsu:verb:入る:はいる","senseId":"verb:入る:はいる","meaning":"进入","form":"tsutsu","scene":"迈入会场时向入口接待人员打招呼。","before":[{"text":"会場に","reading":"かいじょうに"}],"after":[{"text":"、受付の人に挨拶した。","reading":"、うけつけのひとにあいさつした。"}],"translation":"一边走进会场，一边向接待人员打招呼。","review":"approved"},
  {"id":"usage:tsutsu:verb:売る:うる","senseId":"verb:売る:うる","meaning":"售卖","form":"tsutsu","scene":"售卖手工皂，同时介绍制作方法。","before":[{"text":"手作り石けんを","reading":"てづくりせっけんを"}],"after":[{"text":"、作り方を説明した。","reading":"、つくりかたをせつめいした。"}],"translation":"售卖手工皂的同时，介绍了制作方法。","review":"approved"},
  {"id":"usage:tsutsu:verb:言う:いう","senseId":"verb:言う:いう","meaning":"说","form":"tsutsu","scene":"说明注意事项，同时观察听众的反应。","before":[{"text":"注意点を","reading":"ちゅういてんを"}],"after":[{"text":"、"},{"text":"聞き手","reading":"ききて"},{"text":"の反応を見た。","reading":"のはんのうをみた。"}],"translation":"说明注意事项时，观察了听众的反应。","review":"approved"},
  {"id":"usage:tsutsu:verb:払う:はらう","senseId":"verb:払う:はらう","meaning":"支付","form":"tsutsu","scene":"用餐后在收银台付款时向店员道谢。","before":[{"text":"食事代を","reading":"しょくじだいを"}],"after":[{"text":"、店員に礼を言った。","reading":"、てんいんにれいをいった。"}],"translation":"一边支付餐费，一边向店员道谢。","review":"approved"},
  {"id":"usage:tsutsu:verb:手伝う:てつだう","senseId":"verb:手伝う:てつだう","meaning":"帮忙","form":"tsutsu","scene":"帮朋友搬家期间边干活边听他的近况。","before":[{"text":"引っ越しを","reading":"ひっこしを"}],"after":[{"text":"、友人の近況を聞いた。","reading":"、ゆうじんのきんきょうをきいた。"}],"translation":"一边帮忙搬家，一边听朋友讲近况。","review":"approved"}
];
