// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:nagara:verb:捨てる:すてる","senseId":"verb:捨てる:すてる","meaning":"丢弃","form":"nagara","scene":"清走旧纸箱时和同事商量仓库用途。","before":[{"text":"古い段ボールを","reading":"ふるいだんボールを"}],"after":[{"text":"、同僚と倉庫の使い方を相談した。","reading":"、どうりょうとそうこのつかいかたをそうだんした。"}],"translation":"一边丢弃旧纸箱，一边和同事商量仓库的用法。","review":"approved"},
  {"id":"usage:nagara:verb:迎える:むかえる","senseId":"verb:迎える:むかえる","meaning":"迎接","form":"nagara","scene":"在接待处逐位迎接客人，并标记来访名单。","before":[{"text":"受付で次々と客を","reading":"うけつけでつぎつぎときゃくを"}],"after":[{"text":"、名簿に印を付けた。","reading":"、めいぼにしるしをつけた。"}],"translation":"一边在接待处接连迎接客人，一边在名单上做记号。","review":"approved"},
  {"id":"usage:nagara:verb:変える:かえる","senseId":"verb:変える:かえる","meaning":"改变","form":"nagara","scene":"调整画面配色时逐步查看最终效果。","before":[{"text":"画面の色を少しずつ","reading":"がめんのいろをすこしずつ"}],"after":[{"text":"、仕上がりを確認した。","reading":"、しあがりをかくにんした。"}],"translation":"一边一点点改变画面的颜色，一边确认呈现的效果。","review":"approved"},
  {"id":"usage:nagara:verb:片付ける:かたづける","senseId":"verb:片付ける:かたづける","meaning":"收拾；整理","form":"nagara","scene":"下班前收拾桌面时思考第二天的工作。","before":[{"text":"机の上を","reading":"つくえのうえを"}],"after":[{"text":"、翌日の仕事を考えた。","reading":"、よくじつのしごとをかんがえた。"}],"translation":"一边收拾桌面，一边考虑第二天的工作。","review":"approved"},
  {"id":"usage:tsutsu:verb:楽しむ:たのしむ","senseId":"verb:楽しむ:たのしむ","meaning":"享受；期待","form":"tsutsu","scene":"在庭院里慢慢散步，欣赏周围景色。","before":[{"text":"景色を","reading":"けしきを"}],"after":[{"text":"、庭をゆっくり歩いた。","reading":"、にわをゆっくりあるいた。"}],"translation":"一边欣赏风景，一边在庭院里慢慢走。","review":"approved"},
  {"id":"usage:tsutsu:verb:申し込む:もうしこむ","senseId":"verb:申し込む:もうしこむ","meaning":"申请；报名","form":"tsutsu","scene":"在线办理讲座报名时核对参加条件。","before":[{"text":"オンラインで講座に","reading":"オンラインでこうざに"}],"after":[{"text":"、参加条件を確認した。","reading":"、さんかじょうけんをかくにんした。"}],"translation":"一边在网上报名讲座，一边确认参加条件。","review":"approved"},
  {"id":"usage:tsutsu:verb:変わる:かわる","senseId":"verb:変わる:かわる","meaning":"改变","form":"tsutsu","scene":"夕阳下云层渐渐变红，并向东漂移。","before":[{"text":"雲は赤く","reading":"くもはあかく"}],"after":[{"text":"、東へ流れていった。","reading":"、ひがしへながれていった。"}],"translation":"云一边变红，一边向东飘去。","review":"approved"},
  {"id":"usage:tsutsu:verb:座る:すわる","senseId":"verb:座る:すわる","meaning":"坐","form":"tsutsu","scene":"在会场落座时开口向邻座的人问好。","before":[{"text":"彼は椅子に","reading":"かれはいすに"}],"after":[{"text":"、隣の人に挨拶した。","reading":"、となりのひとにあいさつした。"}],"translation":"他一边坐到椅子上，一边向旁边的人打招呼。","review":"approved"},
  {"id":"usage:tsutsu:verb:送る:おくる","senseId":"verb:送る:おくる","meaning":"发送；送行","form":"tsutsu","scene":"逐张发送旅行照片，同时通电话讲解地点。","before":[{"text":"写真を一枚ずつ","reading":"しゃしんをいちまいずつ"}],"after":[{"text":"、電話で撮影場所を説明した。","reading":"、でんわでさつえいばしょをせつめいした。"}],"translation":"一边逐张发送照片，一边在电话里说明拍摄地点。","review":"approved"},
  {"id":"usage:tsutsu:verb:乗る:のる","senseId":"verb:乗る:のる","meaning":"乘坐","form":"tsutsu","scene":"登上公交车时向驾驶座上的司机打招呼。","before":[{"text":"彼はバスに","reading":"かれはバスに"}],"after":[{"text":"、運転手に挨拶した。","reading":"、うんてんしゅにあいさつした。"}],"translation":"他一边上公交车，一边向司机打招呼。","review":"approved"},
  {"id":"usage:tsutsu:verb:食べる:たべる","senseId":"verb:食べる:たべる","meaning":"吃","form":"tsutsu","scene":"吃点心，同时阅读展览说明。","before":[{"text":"お菓子を","reading":"おかしを"}],"after":[{"text":"、展示の説明を読んだ。","reading":"、てんじのせつめいをよんだ。"}],"translation":"吃点心的同时，阅读了展览说明。","review":"approved"},
  {"id":"usage:tsutsu:verb:開ける:あける","senseId":"verb:開ける:あける","meaning":"打开","form":"tsutsu","scene":"推开窗户时开口招呼屋外的朋友。","before":[{"text":"窓を","reading":"まどを"}],"after":[{"text":"、外にいる友人に声をかけた。","reading":"、そとにいるゆうじんにこえをかけた。"}],"translation":"一边打开窗户，一边招呼在外面的朋友。","review":"approved"},
  {"id":"usage:tsutsu:verb:借りる:かりる","senseId":"verb:借りる:かりる","meaning":"借入","form":"tsutsu","scene":"每月借用市里的会议室举办读书会。","before":[{"text":"市の会議室を毎月","reading":"しのかいぎしつをまいつき"}],"after":[{"text":"、読書会を続けた。","reading":"、どくしょかいをつづけた。"}],"translation":"一边每月借用市里的会议室，一边持续举办读书会。","review":"approved"},
  {"id":"usage:tsutsu:verb:覚える:おぼえる","senseId":"verb:覚える:おぼえる","meaning":"记住","form":"tsutsu","scene":"记住新表达，同时在对话中练习使用。","before":[{"text":"新しい表現を","reading":"あたらしいひょうげんを"}],"after":[{"text":"、会話で使う練習をした。","reading":"、かいわでつかうれんしゅうをした。"}],"translation":"记住新表达的同时，练习了在对话中使用。","review":"approved"}
];
