// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:nagara:verb:泳ぐ:およぐ","senseId":"verb:泳ぐ:およぐ","meaning":"游泳","form":"nagara","scene":"在海里游泳时留意自己离岸有多远。","before":[{"text":"海で","reading":"うみで"}],"after":[{"text":"、岸までの距離を確かめた。","reading":"、きしまでのきょりをたしかめた。"}],"translation":"一边在海里游泳，一边确认离岸的距离。","review":"approved"},
  {"id":"usage:nagara:verb:聞く:きく","senseId":"verb:聞く:きく","meaning":"听；询问","form":"nagara","scene":"听音乐的同时完成作业。","before":[{"text":"音楽を","reading":"おんがくを"}],"after":[{"text":"、宿題をした。","reading":"、しゅくだいをした。"}],"translation":"一边听音乐，一边做了作业。","review":"approved"},
  {"id":"usage:nagara:verb:立つ:たつ","senseId":"verb:立つ:たつ","meaning":"站立","form":"nagara","scene":"他从椅子上起身时向来访的客人打招呼。","before":[{"text":"彼は椅子から","reading":"かれはいすから"}],"after":[{"text":"、客に挨拶した。","reading":"、きゃくにあいさつした。"}],"translation":"他一边从椅子上站起身，一边向客人打招呼。","review":"approved"},
  {"id":"usage:nagara:verb:急ぐ:いそぐ","senseId":"verb:急ぐ:いそぐ","meaning":"赶快","form":"nagara","scene":"赶往车站时给朋友打电话。","before":[{"text":"駅へ","reading":"えきへ"}],"after":[{"text":"、友達に電話した。","reading":"、ともだちにでんわした。"}],"translation":"一边赶往车站，一边给朋友打了电话。","review":"approved"},
  {"id":"usage:nagara:verb:会う:あう","senseId":"verb:会う:あう","meaning":"见面","form":"nagara","scene":"走访当地多位居民，逐步调查小镇历史。","before":[{"text":"地元の住民に次々と","reading":"じもとのじゅうみんにつぎつぎと"}],"after":[{"text":"、町の歴史を調べた。","reading":"、まちのれきしをしらべた。"}],"translation":"一边逐一与当地居民见面，一边调查小镇的历史。","review":"approved"},
  {"id":"usage:nagara:verb:使う:つかう","senseId":"verb:使う:つかう","meaning":"使用","form":"nagara","scene":"使用词典查词义并做笔记。","before":[{"text":"辞書を","reading":"じしょを"}],"after":[{"text":"、意味をノートに書いた。","reading":"、いみをノートにかいた。"}],"translation":"一边使用词典，一边把词义写在笔记本上。","review":"approved"},
  {"id":"usage:nagara:verb:働く:はたらく","senseId":"verb:働く:はたらく","meaning":"工作","form":"nagara","scene":"在咖啡店工作时听顾客的意见。","before":[{"text":"店で","reading":"みせで"}],"after":[{"text":"、お客さんの声を聞いていた。","reading":"、おきゃくさんのこえをきいていた。"}],"translation":"一边在店里工作，一边听取顾客的意见。","review":"approved"},
  {"id":"usage:nagara:verb:置く:おく","senseId":"verb:置く:おく","meaning":"放置","form":"nagara","scene":"会议前摆放资料时向大家说明会议流程。","before":[{"text":"資料を机の上に","reading":"しりょうをつくえのうえに"}],"after":[{"text":"、会議の流れを説明した。","reading":"、かいぎのながれをせつめいした。"}],"translation":"一边把资料放到桌上，一边说明会议流程。","review":"approved"},
  {"id":"usage:nagara:verb:騒ぐ:さわぐ","senseId":"verb:騒ぐ:さわぐ","meaning":"吵闹","form":"nagara","scene":"孩子们吵闹着收拾教室。","before":[{"text":"子どもたちは教室で","reading":"こどもたちはきょうしつで"}],"after":[{"text":"、机を片付けた。","reading":"、つくえをかたづけた。"}],"translation":"孩子们一边在教室里吵闹，一边收拾了桌子。","review":"approved"},
  {"id":"usage:nagara:verb:消す:けす","senseId":"verb:消す:けす","meaning":"关闭；消除","form":"nagara","scene":"老师擦黑板时回答学生提出的问题。","before":[{"text":"黒板の文字を","reading":"こくばんのもじを"}],"after":[{"text":"、生徒の質問に答えた。","reading":"、せいとのしつもんにこたえた。"}],"translation":"一边擦掉黑板上的字，一边回答学生的问题。","review":"approved"},
  {"id":"usage:nagara:verb:打つ:うつ","senseId":"verb:打つ:うつ","meaning":"敲打","form":"nagara","scene":"做木工时边敲钉子边留意木板的位置。","before":[{"text":"釘を","reading":"くぎを"}],"after":[{"text":"、板の位置を確かめた。","reading":"、いたのいちをたしかめた。"}],"translation":"一边敲钉子，一边确认木板的位置。","review":"approved"},
  {"id":"usage:nagara:verb:飛ぶ:とぶ","senseId":"verb:飛ぶ:とぶ","meaning":"飞","form":"nagara","scene":"飞行员在海上空训练时查看机舱仪表。","before":[{"text":"操縦士は海の上を","reading":"そうじゅうしはうみのうえを"}],"after":[{"text":"、計器を確認した。","reading":"、けいきをかくにんした。"}],"translation":"飞行员一边在海面上空飞行，一边确认仪表。","review":"approved"},
  {"id":"usage:nagara:verb:休む:やすむ","senseId":"verb:休む:やすむ","meaning":"休息","form":"nagara","scene":"在长椅上休息时欣赏风景。","before":[{"text":"ベンチで","reading":"ベンチで"}],"after":[{"text":"、景色を眺めた。","reading":"、けしきをながめた。"}],"translation":"一边在长椅上休息，一边欣赏了风景。","review":"approved"},
  {"id":"usage:nagara:verb:入る:はいる","senseId":"verb:入る:はいる","meaning":"进入","form":"nagara","scene":"迈进店门时向门边的店员打招呼。","before":[{"text":"店に","reading":"みせに"}],"after":[{"text":"、店員に挨拶した。","reading":"、てんいんにあいさつした。"}],"translation":"一边走进店里，一边向店员打招呼。","review":"approved"},
  {"id":"usage:nagara:verb:売る:うる","senseId":"verb:売る:うる","meaning":"售卖","form":"nagara","scene":"售卖蔬菜时回答顾客的问题。","before":[{"text":"店頭で野菜を","reading":"てんとうでやさいを"}],"after":[{"text":"、客の質問に答えた。","reading":"、きゃくのしつもんにこたえた。"}],"translation":"一边在店门口售卖蔬菜，一边回答顾客的问题。","review":"approved"},
  {"id":"usage:nagara:verb:言う:いう","senseId":"verb:言う:いう","meaning":"说","form":"nagara","scene":"表达意见时说明理由。","before":[{"text":"自分の意見を","reading":"じぶんのいけんを"}],"after":[{"text":"、理由を説明した。","reading":"、りゆうをせつめいした。"}],"translation":"一边说出自己的意见，一边说明了理由。","review":"approved"}
];
