// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:tsutsu:verb:拾う:ひろう","senseId":"verb:拾う:ひろう","meaning":"捡；拾","form":"tsutsu","scene":"沿海滩捡贝壳，同时寻找孩子的帽子。","before":[{"text":"浜で貝殻を","reading":"はまでかいがらを"}],"after":[{"text":"、子どもの帽子を探した。","reading":"、こどものぼうしをさがした。"}],"translation":"在海滩捡贝壳的同时，寻找了孩子的帽子。","review":"approved"},
  {"id":"usage:tsutsu:verb:描く:えがく","senseId":"verb:描く:えがく","meaning":"描绘","form":"tsutsu","scene":"描绘城市夜景，同时构思故事背景。","before":[{"text":"街の夜景を","reading":"まちのやけいを"}],"after":[{"text":"、"},{"text":"物語","reading":"ものがたり"},{"text":"の舞台を考えた。","reading":"のぶたいをかんがえた。"}],"translation":"描绘城市夜景的同时，构思了故事的舞台。","review":"approved"},
  {"id":"usage:tsutsu:verb:動く:うごく","senseId":"verb:動く:うごく","meaning":"移动；运转","form":"tsutsu","scene":"演员在舞台上走位，同时反复练习台词。","before":[{"text":"俳優は舞台の上を","reading":"はいゆうはぶたいのうえを"}],"after":[{"text":"、台詞を繰り返した。","reading":"、せりふをくりかえした。"}],"translation":"演员一边在舞台上移动，一边反复说台词。","review":"approved"},
  {"id":"usage:tsutsu:verb:焼く:やく","senseId":"verb:焼く:やく","meaning":"烤；烧","form":"tsutsu","scene":"烤面包，同时准备早晨的咖啡。","before":[{"text":"パンを","reading":"パンを"}],"after":[{"text":"、朝のコーヒーを用意した。","reading":"、あさのコーヒーをよういした。"}],"translation":"烤面包的同时，准备了早晨的咖啡。","review":"approved"},
  {"id":"usage:tsutsu:verb:防ぐ:ふせぐ","senseId":"verb:防ぐ:ふせぐ","meaning":"防止","form":"tsutsu","scene":"工人穿戴防护用品，操作机器时避免受伤。","before":[{"text":"作業員は保護具でけがを","reading":"さぎょういんはほごぐでけがを"}],"after":[{"text":"、機械を操作した。","reading":"、きかいをそうさした。"}],"translation":"工人一边用防护用品防止受伤，一边操作机器。","review":"approved"},
  {"id":"usage:tsutsu:verb:出す:だす","senseId":"verb:出す:だす","meaning":"拿出；提交","form":"tsutsu","scene":"旅途中从包里拿出地图并说明下一站。","before":[{"text":"彼はかばんから地図を","reading":"かれはかばんからちずを"}],"after":[{"text":"、次の目的地を説明した。","reading":"、つぎのもくてきちをせつめいした。"}],"translation":"他一边从包里拿出地图，一边说明下一个目的地。","review":"approved"},
  {"id":"usage:tsutsu:verb:渡す:わたす","senseId":"verb:渡す:わたす","meaning":"交给","form":"tsutsu","scene":"递交文件，同时说明截止日期。","before":[{"text":"書類を","reading":"しょるいを"}],"after":[{"text":"、締め切りを伝えた。","reading":"、しめきりをつたえた。"}],"translation":"递交文件时，说明了截止日期。","review":"approved"},
  {"id":"usage:tsutsu:verb:押す:おす","senseId":"verb:押す:おす","meaning":"按；推","form":"tsutsu","scene":"推着沉重的门时开口招呼后面的人。","before":[{"text":"重い扉を","reading":"おもいとびらを"}],"after":[{"text":"、後ろの人に声をかけた。","reading":"、うしろのひとにこえをかけた。"}],"translation":"一边推沉重的门，一边招呼后面的人。","review":"approved"},
  {"id":"usage:tsutsu:verb:落とす:おとす","senseId":"verb:落とす:おとす","meaning":"弄掉；丢失","form":"tsutsu","scene":"探路时沿途丢下小石子标记回来的路线。","before":[{"text":"目印に小石を一つずつ","reading":"めじるしにこいしをひとつずつ"}],"after":[{"text":"、森の奥へ進んだ。","reading":"、もりのおくへすすんだ。"}],"translation":"一边一个个丢下小石子做记号，一边向树林深处前进。","review":"approved"},
  {"id":"usage:tsutsu:verb:起こす:おこす","senseId":"verb:起こす:おこす","meaning":"叫醒；引起","form":"tsutsu","scene":"妈妈叫弟弟起床时还顺手拉开房间窗帘。","before":[{"text":"母は声をかけて弟を","reading":"はははこえをかけておとうとを"}],"after":[{"text":"、部屋のカーテンを開けた。","reading":"、へやのカーテンをあけた。"}],"translation":"妈妈一边出声叫弟弟起床，一边拉开房间的窗帘。","review":"approved"},
  {"id":"usage:tsutsu:verb:並ぶ:ならぶ","senseId":"verb:並ぶ:ならぶ","meaning":"排队；排列","form":"tsutsu","scene":"排队等候时，同时查看手机上的通知。","before":[{"text":"列に","reading":"れつに"}],"after":[{"text":"、スマホの通知を確認した。","reading":"、スマホのつうちをかくにんした。"}],"translation":"排队等候时，查看了手机上的通知。","review":"approved"},
  {"id":"usage:tsutsu:verb:喜ぶ:よろこぶ","senseId":"verb:喜ぶ:よろこぶ","meaning":"高兴","form":"tsutsu","scene":"得知令人高兴的消息后告诉家人。","before":[{"text":"知らせを","reading":"しらせを"}],"after":[{"text":"、家族に伝えた。","reading":"、かぞくにつたえた。"}],"translation":"一边为消息感到高兴，一边把消息告诉家人。","review":"approved"},
  {"id":"usage:nagara:verb:楽しむ:たのしむ","senseId":"verb:楽しむ:たのしむ","meaning":"享受；期待","form":"nagara","scene":"享受音乐，同时准备晚餐。","before":[{"text":"音楽を","reading":"おんがくを"}],"after":[{"text":"、夕食を作った。","reading":"、ゆうしょくをつくった。"}],"translation":"享受音乐的同时，做了晚餐。","review":"approved"},
  {"id":"usage:nagara:verb:申し込む:もうしこむ","senseId":"verb:申し込む:もうしこむ","meaning":"申请；报名","form":"nagara","scene":"在线填写课程报名手续时核对上课日期。","before":[{"text":"オンラインで講座に","reading":"オンラインでこうざに"}],"after":[{"text":"、日程を確認した。","reading":"、にっていをかくにんした。"}],"translation":"一边在网上报名课程，一边确认日程。","review":"approved"},
  {"id":"usage:nagara:verb:変わる:かわる","senseId":"verb:変わる:かわる","meaning":"改变","form":"nagara","scene":"夕阳下云层逐渐变红，同时向东漂移。","before":[{"text":"雲は赤く","reading":"くもはあかく"}],"after":[{"text":"、東へ流れていった。","reading":"、ひがしへながれていった。"}],"translation":"云一边变红，一边向东飘去。","review":"approved"},
  {"id":"usage:nagara:verb:座る:すわる","senseId":"verb:座る:すわる","meaning":"坐","form":"nagara","scene":"在会场落座时向相邻座位的人打招呼。","before":[{"text":"彼は椅子に","reading":"かれはいすに"}],"after":[{"text":"、隣の人に挨拶した。","reading":"、となりのひとにあいさつした。"}],"translation":"他一边坐到椅子上，一边向旁边的人打招呼。","review":"approved"}
];
