// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:nagara:verb:払う:はらう","senseId":"verb:払う:はらう","meaning":"支付","form":"nagara","scene":"付款时向店员道谢。","before":[{"text":"代金を","reading":"だいきんを"}],"after":[{"text":"、店員に礼を言った。","reading":"、てんいんにれいをいった。"}],"translation":"一边支付费用，一边向店员道了谢。","review":"approved"},
  {"id":"usage:nagara:verb:手伝う:てつだう","senseId":"verb:手伝う:てつだう","meaning":"帮忙","form":"nagara","scene":"帮朋友搬家时边搬东西边商量摆放位置。","before":[{"text":"友達の引っ越しを","reading":"ともだちのひっこしを"}],"after":[{"text":"、荷物の置き場所を相談した。","reading":"、にもつのおきばしょをそうだんした。"}],"translation":"一边帮朋友搬家，一边商量行李的摆放位置。","review":"approved"},
  {"id":"usage:nagara:verb:拾う:ひろう","senseId":"verb:拾う:ひろう","meaning":"捡；拾","form":"nagara","scene":"和朋友清理海岸，边捡垃圾边聊天。","before":[{"text":"海岸でごみを","reading":"かいがんでごみを"}],"after":[{"text":"、友人と話した。","reading":"、ゆうじんとはなした。"}],"translation":"一边在海岸捡垃圾，一边和朋友聊天。","review":"approved"},
  {"id":"usage:nagara:verb:描く:えがく","senseId":"verb:描く:えがく","meaning":"描绘","form":"nagara","scene":"为朋友画出地图，同时琢磨行走路线。","before":[{"text":"地図を","reading":"ちずを"}],"after":[{"text":"、道順を考えた。","reading":"、みちじゅんをかんがえた。"}],"translation":"一边画地图，一边考虑路线。","review":"approved"},
  {"id":"usage:nagara:verb:動く:うごく","senseId":"verb:動く:うごく","meaning":"移动；运转","form":"nagara","scene":"机器运转时发出异常声音。","before":[{"text":"機械が","reading":"きかいが"}],"after":[{"text":"、異常な音を出した。","reading":"、いじょうなおとをだした。"}],"translation":"机器一边运转，一边发出了异常的声音。","review":"approved"},
  {"id":"usage:nagara:verb:焼く:やく","senseId":"verb:焼く:やく","meaning":"烤；烧","form":"nagara","scene":"准备晚餐时同时烤鱼和煮米饭。","before":[{"text":"魚を","reading":"さかなを"}],"after":[{"text":"、ご飯を炊いた。","reading":"、ごはんをたいた。"}],"translation":"一边烤鱼，一边煮米饭。","review":"approved"},
  {"id":"usage:nagara:verb:防ぐ:ふせぐ","senseId":"verb:防ぐ:ふせぐ","meaning":"防止","form":"nagara","scene":"戴着帽子防晒，同时清理院中的杂草。","before":[{"text":"帽子で日焼けを","reading":"ぼうしでひやけを"}],"after":[{"text":"、庭の草を抜いた。","reading":"、にわのくさをぬいた。"}],"translation":"一边用帽子防止晒伤，一边拔院子里的草。","review":"approved"},
  {"id":"usage:nagara:verb:出す:だす","senseId":"verb:出す:だす","meaning":"拿出；提交","form":"nagara","scene":"取出包里的文件时向同事讲解其内容。","before":[{"text":"書類をかばんから","reading":"しょるいをかばんから"}],"after":[{"text":"、内容を説明した。","reading":"、ないようをせつめいした。"}],"translation":"一边从包里拿出文件，一边说明文件的内容。","review":"approved"},
  {"id":"usage:nagara:verb:渡す:わたす","senseId":"verb:渡す:わたす","meaning":"交给","form":"nagara","scene":"递给负责人资料时顺带说明其中的要点。","before":[{"text":"資料を担当者に","reading":"しりょうをたんとうしゃに"}],"after":[{"text":"、要点を説明した。","reading":"、ようてんをせつめいした。"}],"translation":"一边把资料交给负责人，一边说明要点。","review":"approved"},
  {"id":"usage:nagara:verb:押す:おす","senseId":"verb:押す:おす","meaning":"按；推","form":"nagara","scene":"推着平板车经过通道时留意周围是否安全。","before":[{"text":"台車を","reading":"だいしゃを"}],"after":[{"text":"、通路の安全を確かめた。","reading":"、つうろのあんぜんをたしかめた。"}],"translation":"一边推平板车，一边确认通道是否安全。","review":"approved"},
  {"id":"usage:nagara:verb:落とす:おとす","senseId":"verb:落とす:おとす","meaning":"弄掉；丢失","form":"nagara","scene":"走入树林时沿途丢下小石子作为路标。","before":[{"text":"目印に小石を一つずつ","reading":"めじるしにこいしをひとつずつ"}],"after":[{"text":"、森の奥へ進んだ。","reading":"、もりのおくへすすんだ。"}],"translation":"一边一个个丢下小石子做记号，一边向树林深处前进。","review":"approved"},
  {"id":"usage:nagara:verb:起こす:おこす","senseId":"verb:起こす:おこす","meaning":"叫醒；引起","form":"nagara","scene":"妈妈开口叫弟弟起床，同时拉开房间窗帘。","before":[{"text":"母は声をかけて弟を","reading":"はははこえをかけておとうとを"}],"after":[{"text":"、部屋のカーテンを開けた。","reading":"、へやのカーテンをあけた。"}],"translation":"妈妈一边出声叫弟弟起床，一边拉开房间的窗帘。","review":"approved"},
  {"id":"usage:nagara:verb:並ぶ:ならぶ","senseId":"verb:並ぶ:ならぶ","meaning":"排队；排列","form":"nagara","scene":"排队等候时查看手机消息。","before":[{"text":"店の前に","reading":"みせのまえに"}],"after":[{"text":"、スマートフォンを見た。","reading":"、スマートフォンをみた。"}],"translation":"一边在店前排队，一边看了手机。","review":"approved"},
  {"id":"usage:nagara:verb:喜ぶ:よろこぶ","senseId":"verb:喜ぶ:よろこぶ","meaning":"高兴","form":"nagara","scene":"得知合格后高兴地向家人报告。","before":[{"text":"合格を","reading":"ごうかくを"}],"after":[{"text":"、家族に報告した。","reading":"、かぞくにほうこくした。"}],"translation":"一边为合格感到高兴，一边向家人报告了。","review":"approved"},
  {"id":"usage:tsutsu:verb:泳ぐ:およぐ","senseId":"verb:泳ぐ:およぐ","meaning":"游泳","form":"tsutsu","scene":"选手在练习时边游泳边留意前方浮标。","before":[{"text":"選手は","reading":"せんしゅは"}],"after":[{"text":"、前方の浮きを目で追った。","reading":"、ぜんぽうのうきをめでおった。"}],"translation":"选手一边游泳，一边用目光追着前方的浮标。","review":"approved"},
  {"id":"usage:tsutsu:verb:聞く:きく","senseId":"verb:聞く:きく","meaning":"听；询问","form":"tsutsu","scene":"听老师说明时记录要点。","before":[{"text":"先生の説明を","reading":"せんせいのせつめいを"}],"after":[{"text":"、要点を記録した。","reading":"、ようてんをきろくした。"}],"translation":"一边听老师的说明，一边记录了要点。","review":"approved"}
];
