// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:nagara:verb:送る:おくる","senseId":"verb:送る:おくる","meaning":"发送；送行","form":"nagara","scene":"逐封发送工作邮件时听同事说明工作。","before":[{"text":"仕事のメールを次々と","reading":"しごとのメールをつぎつぎと"}],"after":[{"text":"、同僚の説明を聞いた。","reading":"、どうりょうのせつめいをきいた。"}],"translation":"一边接连发送工作邮件，一边听同事的说明。","review":"approved"},
  {"id":"usage:nagara:verb:乗る:のる","senseId":"verb:乗る:のる","meaning":"乘坐","form":"nagara","scene":"登上公交车的台阶时向司机打招呼。","before":[{"text":"彼はバスに","reading":"かれはバスに"}],"after":[{"text":"、運転手に挨拶した。","reading":"、うんてんしゅにあいさつした。"}],"translation":"他一边上公交车，一边向司机打招呼。","review":"approved"},
  {"id":"usage:nagara:verb:眠る:ねむる","senseId":"verb:眠る:ねむる","meaning":"睡眠","form":"nagara","scene":"同伴睡着后好几次开口说梦话。","before":[{"text":"彼は","reading":"かれは"}],"after":[{"text":"、何度も寝言を言った。","reading":"、なんどもねごとをいった。"}],"translation":"他一边睡觉，一边好几次说梦话。","review":"approved"},
  {"id":"usage:nagara:verb:食べる:たべる","senseId":"verb:食べる:たべる","meaning":"吃","form":"nagara","scene":"吃午餐，同时讨论下午的安排。","before":[{"text":"昼食を","reading":"ちゅうしょくを"}],"after":[{"text":"、午後の予定を話し合った。","reading":"、ごごのよていをはなしあった。"}],"translation":"吃午餐的同时，讨论了下午的安排。","review":"approved"},
  {"id":"usage:nagara:verb:開ける:あける","senseId":"verb:開ける:あける","meaning":"打开","form":"nagara","scene":"打开包裹，同时向孩子说明里面的东西。","before":[{"text":"包みを","reading":"つつみを"}],"after":[{"text":"、中身を子どもに説明した。","reading":"、なかみをこどもにせつめいした。"}],"translation":"打开包裹的同时，向孩子说明了里面的东西。","review":"approved"},
  {"id":"usage:nagara:verb:借りる:かりる","senseId":"verb:借りる:かりる","meaning":"借入","form":"nagara","scene":"每周去图书馆借书，持续学习日本历史。","before":[{"text":"図書館で毎週本を","reading":"としょかんでまいしゅうほんを"}],"after":[{"text":"、日本の歴史を学んだ。","reading":"、にほんのれきしをまなんだ。"}],"translation":"一边每周在图书馆借书，一边学习日本历史。","review":"approved"},
  {"id":"usage:nagara:verb:覚える:おぼえる","senseId":"verb:覚える:おぼえる","meaning":"记住","form":"nagara","scene":"记单词的同时，在短句中使用它们。","before":[{"text":"単語を","reading":"たんごを"}],"after":[{"text":"、短い文で使った。","reading":"、みじかいぶんでつかった。"}],"translation":"记单词的同时，在短句中使用了它们。","review":"approved"},
  {"id":"usage:nagara:verb:着る:きる","senseId":"verb:着る:きる","meaning":"穿","form":"nagara","scene":"早晨穿外套时告诉家人第二天的安排。","before":[{"text":"コートを","reading":"コートを"}],"after":[{"text":"、家族に明日の予定を話した。","reading":"、かぞくにあしたのよていをはなした。"}],"translation":"一边穿外套，一边告诉家人明天的安排。","review":"approved"},
  {"id":"usage:nagara:verb:調べる:しらべる","senseId":"verb:調べる:しらべる","meaning":"调查","form":"nagara","scene":"查资料的同时，思考报告的结构。","before":[{"text":"資料を","reading":"しりょうを"}],"after":[{"text":"、レポートの構成を考えた。","reading":"、レポートのこうせいをかんがえた。"}],"translation":"查资料的同时，思考了报告的结构。","review":"approved"},
  {"id":"usage:nagara:verb:続ける:つづける","senseId":"verb:続ける:つづける","meaning":"继续","form":"nagara","scene":"继续练习，同时调整手指的位置。","before":[{"text":"練習を","reading":"れんしゅうを"}],"after":[{"text":"、指の位置を直した。","reading":"、ゆびのいちをなおした。"}],"translation":"继续练习的同时，调整了手指的位置。","review":"approved"},
  {"id":"usage:nagara:verb:助ける:たすける","senseId":"verb:助ける:たすける","meaning":"帮助","form":"nagara","scene":"帮正在搬东西的新人一把，并告诉他休息安排。","before":[{"text":"荷物を運ぶ新人を","reading":"にもつをはこぶしんじんを"}],"after":[{"text":"、休憩の予定を伝えた。","reading":"、きゅうけいのよていをつたえた。"}],"translation":"一边帮助正在搬行李的新人，一边告诉他休息安排。","review":"approved"},
  {"id":"usage:nagara:verb:考える:かんがえる","senseId":"verb:考える:かんがえる","meaning":"思考；考虑","form":"nagara","scene":"思考解决办法，同时在房间里来回走动。","before":[{"text":"解決策を","reading":"かいけつさくを"}],"after":[{"text":"、部屋を歩き回った。","reading":"、へやをあるきまわった。"}],"translation":"思考解决办法的同时，在房间里来回走动。","review":"approved"},
  {"id":"usage:nagara:verb:決める:きめる","senseId":"verb:決める:きめる","meaning":"决定","form":"nagara","scene":"确定旅行计划，同时和家人商量。","before":[{"text":"旅行の日程を","reading":"りょこうのにっていを"}],"after":[{"text":"、家族と相談した。","reading":"、かぞくとそうだんした。"}],"translation":"确定旅行日程的同时，和家人商量了。","review":"approved"},
  {"id":"usage:nagara:verb:見せる:みせる","senseId":"verb:見せる:みせる","meaning":"给……看","form":"nagara","scene":"展示设计草图，同时解释修改之处。","before":[{"text":"設計図を","reading":"せっけいずを"}],"after":[{"text":"、変更点を説明した。","reading":"、へんこうてんをせつめいした。"}],"translation":"展示设计图的同时，说明了修改之处。","review":"approved"},
  {"id":"usage:nagara:verb:付ける:つける","senseId":"verb:付ける:つける","meaning":"附上；打开","form":"nagara","scene":"给商品贴标签时和同事核对当天的安排。","before":[{"text":"商品にラベルを","reading":"しょうひんにラベルを"}],"after":[{"text":"、同僚と今日の予定を確認した。","reading":"、どうりょうときょうのよていをかくにんした。"}],"translation":"一边给商品贴标签，一边和同事核对今天的安排。","review":"approved"}
];
