// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:nagara:verb:弾く:ひく","senseId":"verb:弾く:ひく","meaning":"弹奏","form":"nagara","scene":"在练琴室边弹钢琴边轻声唱歌。","before":[{"text":"ピアノを","reading":"ピアノを"}],"after":[{"text":"、小さな声で歌った。","reading":"、ちいさなこえでうたった。"}],"translation":"一边弹钢琴，一边小声唱歌。","review":"approved"},
  {"id":"usage:nagara:verb:待つ:まつ","senseId":"verb:待つ:まつ","meaning":"等待","form":"nagara","scene":"在车站等朋友时顺便查看明天的行程。","before":[{"text":"駅で友人を","reading":"えきでゆうじんを"}],"after":[{"text":"、明日の予定を確認した。","reading":"、あしたのよていをかくにんした。"}],"translation":"一边在车站等朋友，一边确认明天的安排。","review":"approved"},
  {"id":"usage:nagara:verb:読む:よむ","senseId":"verb:読む:よむ","meaning":"阅读","form":"nagara","scene":"通勤电车上边阅读新闻边喝咖啡。","before":[{"text":"電車でニュースを","reading":"でんしゃでニュースを"}],"after":[{"text":"、コーヒーを飲んだ。","reading":"、コーヒーをのんだ。"}],"translation":"一边在电车上读新闻，一边喝咖啡。","review":"approved"},
  {"id":"usage:nagara:verb:切る:きる","senseId":"verb:切る:きる","meaning":"切；剪","form":"nagara","scene":"准备晚餐时边切蔬菜边听广播。","before":[{"text":"野菜を","reading":"やさいを"}],"after":[{"text":"、ラジオを聞いている。","reading":"、ラジオをきいている。"}],"translation":"一边切蔬菜，一边听广播。","review":"approved"},
  {"id":"usage:nagara:verb:思う:おもう","senseId":"verb:思う:おもう","meaning":"想；认为","form":"nagara","scene":"回忆故乡时边想着家人边整理旧照片。","before":[{"text":"故郷の家族を","reading":"ふるさとのかぞくを"}],"after":[{"text":"、古い写真を整理した。","reading":"、ふるいしゃしんをせいりした。"}],"translation":"一边想着故乡的家人，一边整理旧照片。","review":"approved"},
  {"id":"usage:tsutsu:verb:弾く:ひく","senseId":"verb:弾く:ひく","meaning":"弹奏","form":"tsutsu","scene":"音乐会的回忆中写到自己边演奏边看指挥。","before":[{"text":"ピアノを","reading":"ピアノを"}],"after":[{"text":"、指揮者の手を見ていた。","reading":"、しきしゃのてをみていた。"}],"translation":"一边弹钢琴，一边看着指挥的手。","review":"approved"},
  {"id":"usage:tsutsu:verb:待つ:まつ","senseId":"verb:待つ:まつ","meaning":"等待","form":"tsutsu","scene":"在候车记录中回顾等车时读报的情形。","before":[{"text":"列車を","reading":"れっしゃを"}],"after":[{"text":"、駅で買った新聞を読んだ。","reading":"、えきでかったしんぶんをよんだ。"}],"translation":"一边等列车，一边读车站买来的报纸。","review":"approved"},
  {"id":"usage:tsutsu:verb:読む:よむ","senseId":"verb:読む:よむ","meaning":"阅读","form":"tsutsu","scene":"研究时一边阅读资料一边整理关键论点。","before":[{"text":"資料を","reading":"しりょうを"}],"after":[{"text":"、要点を整理する。","reading":"、ようてんをせいりする。"}],"translation":"一边阅读资料，一边整理要点。","review":"approved"},
  {"id":"usage:tsutsu:verb:切る:きる","senseId":"verb:切る:きる","meaning":"切；剪","form":"tsutsu","scene":"做料理时一边切水果一边听取家人的意见。","before":[{"text":"果物を","reading":"くだものを"}],"after":[{"text":"、家族の意見を聞いた。","reading":"、かぞくのいけんをきいた。"}],"translation":"一边切水果，一边听家人的意见。","review":"approved"},
  {"id":"usage:tsutsu:verb:思う:おもう","senseId":"verb:思う:おもう","meaning":"想；认为","form":"tsutsu","scene":"写计划时想起父亲曾经给自己的话。","before":[{"text":"父の言葉を","reading":"ちちのことばを"}],"after":[{"text":"、今後の計画を書いた。","reading":"、こんごのけいかくをかいた。"}],"translation":"一边想着父亲的话，一边写下今后的计划。","review":"approved"}
];
