// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:temo:verb:死ぬ:しぬ","senseId":"verb:死ぬ:しぬ","meaning":"死亡","form":"temo","scene":"游戏允许复活，提醒队友不要放弃。","before":[{"text":"このゲームでは、キャラクターが"}],"after":[{"text":"、すぐに"},{"text":"復活","reading":"ふっかつ"},{"text":"できます。"}],"translation":"在这个游戏里，即使角色死了，也能立刻复活。","review":"approved"},
  {"id":"usage:temo:verb:知る:しる","senseId":"verb:知る:しる","meaning":"知道","form":"temo","scene":"朋友担心说出真相会被我讨厌。","before":[{"text":"本当","reading":"ほんとう"},{"text":"のことを"}],"after":[{"text":"、あなたを"},{"text":"嫌","reading":"きら"},{"text":"いにはなりません。"}],"translation":"即使知道真相，我也不会讨厌你。","review":"approved"},
  {"id":"usage:temo:verb:寝る:ねる","senseId":"verb:寝る:ねる","meaning":"睡觉","form":"temo","scene":"最近睡得很多，醒来仍觉得疲惫。","before":[{"text":"十分","reading":"じゅうぶん"},{"text":"に"}],"after":[{"text":"、"},{"text":"疲","reading":"つか"},{"text":"れが"},{"text":"取","reading":"と"},{"text":"れません。"}],"translation":"即使睡得很充足，疲劳也消除不了。","review":"approved"},
  {"id":"usage:temo:verb:忘れる:わすれる","senseId":"verb:忘れる:わすれる","meaning":"忘记","form":"temo","scene":"担心记不住密码，朋友说明找回办法。","before":[{"text":"パスワードを"}],"after":[{"text":"、メールで"},{"text":"再設定","reading":"さいせってい"},{"text":"できます。"}],"translation":"即使忘了密码，也能通过邮件重新设置。","review":"approved"},
  {"id":"usage:temo:verb:いる:いる","senseId":"verb:いる:いる","meaning":"在；有（生物）","form":"temo","scene":"孩子不怕生，陌生人来了也不哭。","before":[{"text":"知","reading":"し"},{"text":"らない"},{"text":"人","reading":"ひと"},{"text":"がそばに"}],"after":[{"text":"、この"},{"text":"子","reading":"こ"},{"text":"は"},{"text":"泣","reading":"な"},{"text":"きません。"}],"translation":"即使身边有陌生人，这孩子也不会哭。","review":"approved"},
  {"id":"usage:tatte:verb:死ぬ:しぬ","senseId":"verb:死ぬ:しぬ","meaning":"死亡","form":"tatte","scene":"同伴怕角色死掉，说明游戏复活规则。","before":[{"text":"このゲームなら、キャラクターが"}],"after":[{"text":"、すぐに"},{"text":"生","reading":"い"},{"text":"き"},{"text":"返","reading":"かえ"},{"text":"るよ。"}],"translation":"这个游戏里，就算角色死了，也会马上复活哦。","review":"approved"},
  {"id":"usage:tatte:verb:知る:しる","senseId":"verb:知る:しる","meaning":"知道","form":"tatte","scene":"朋友事后才追问，提醒错过补救机会。","before":[{"text":"今","reading":"いま"},{"text":"さら"},{"text":"理由","reading":"りゆう"},{"text":"を"}],"after":[{"text":"、もうやり"},{"text":"直","reading":"なお"},{"text":"せないよ。"}],"translation":"事到如今就算知道原因，也已经无法重来了。","review":"approved"},
  {"id":"usage:tatte:verb:寝る:ねる","senseId":"verb:寝る:ねる","meaning":"睡觉","form":"tatte","scene":"朋友劝早点休息，我说睡够仍然累。","before":[{"text":"たっぷり"}],"after":[{"text":"、"},{"text":"疲","reading":"つか"},{"text":"れが"},{"text":"取","reading":"と"},{"text":"れないんだ。"}],"translation":"就算睡得很足，疲劳也消除不了。","review":"approved"},
  {"id":"usage:tatte:verb:忘れる:わすれる","senseId":"verb:忘れる:わすれる","meaning":"忘记","form":"tatte","scene":"朋友担心背错台词会被老师责骂。","before":[{"text":"せりふを"}],"after":[{"text":"、"},{"text":"先生","reading":"せんせい"},{"text":"は"},{"text":"怒","reading":"おこ"},{"text":"らないよ。"}],"translation":"就算忘了台词，老师也不会生气的。","review":"approved"},
  {"id":"usage:tatte:verb:いる:いる","senseId":"verb:いる:いる","meaning":"在；有（生物）","form":"tatte","scene":"朋友在空办公室等人，劝他先回去。","before":[{"text":"ここにいつまでも"}],"after":[{"text":"、"},{"text":"誰","reading":"だれ"},{"text":"も"},{"text":"来","reading":"こ"},{"text":"ないよ。"}],"translation":"就算一直待在这里，也不会有人来的。","review":"approved"},
  {"id":"usage:tatte:verb:する:する","senseId":"verb:する:する","meaning":"做","form":"tatte","scene":"朋友怕实验失败，鼓励他再次尝试。","before":[{"text":"実験","reading":"じっけん"},{"text":"で"},{"text":"失敗","reading":"しっぱい"},{"text":"を"}],"after":[{"text":"、また"},{"text":"挑戦","reading":"ちょうせん"},{"text":"できるよ。"}],"translation":"就算实验失败了，也能再次挑战。","review":"approved"}
];
