// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:temo:verb:書く:かく","senseId":"verb:書く:かく","meaning":"写；书写","form":"temo","scene":"申请结果不会因反复重写而改变。","before":[{"text":"申請書を何度","reading":"しんせいしょをなんど"}],"after":[{"text":"、結果は変わらない。","reading":"、けっかはかわらない。"}],"translation":"无论申请书写多少次，结果都不会改变。","review":"approved"},
  {"id":"usage:temo:verb:話す:はなす","senseId":"verb:話す:はなす","meaning":"说；交谈","form":"temo","scene":"无论解释多少次，他还是不接受。","before":[{"text":"何度","reading":"なんど"}],"after":[{"text":"、彼は納得しない。","reading":"、かれはなっとくしない。"}],"translation":"无论说多少次，他都不会接受。","review":"approved"},
  {"id":"usage:temo:verb:遊ぶ:あそぶ","senseId":"verb:遊ぶ:あそぶ","meaning":"玩耍","form":"temo","scene":"孩子玩一会儿，离作业截止还有时间。","before":[{"text":"子どもが少し","reading":"こどもがすこし"}],"after":[{"text":"、宿題の締め切りにはまだ時間がある。","reading":"、しゅくだいのしめきりにはまだじかんがある。"}],"translation":"即使孩子玩一会儿，离作业截止也还有时间。","review":"approved"},
  {"id":"usage:temo:verb:分かる:わかる","senseId":"verb:分かる:わかる","meaning":"明白","form":"temo","scene":"即使明白理由，也不能马上改变决定。","before":[{"text":"理由が","reading":"りゆうが"}],"after":[{"text":"、決定はすぐに変えられない。","reading":"、けっていはすぐにかえられない。"}],"translation":"即使明白理由，也无法立刻改变决定。","review":"approved"},
  {"id":"usage:temo:verb:起きる:おきる","senseId":"verb:起きる:おきる","meaning":"起床","form":"temo","scene":"首班车开得很早，五点起床也赶不上。","before":[{"text":"朝五時に","reading":"あさごじに"}],"after":[{"text":"、始発には間に合わない。","reading":"、しはつにはまにあわない。"}],"translation":"即使早上五点起床，也赶不上首班车。","review":"approved"},
  {"id":"usage:temo:verb:来る:くる","senseId":"verb:来る:くる","meaning":"来","form":"temo","scene":"会议快结束了，他现在赶来也来不及。","before":[{"text":"今から会場に","reading":"いまからかいじょうに"}],"after":[{"text":"、会議には間に合わない。","reading":"、かいぎにはまにあわない。"}],"translation":"即使现在赶来会场，也赶不上会议。","review":"approved"},
  {"id":"usage:tatte:verb:話す:はなす","senseId":"verb:話す:はなす","meaning":"说；交谈","form":"tatte","scene":"再怎么说，他也不会改变主意。","before":[{"text":"何度","reading":"なんど"}],"after":[{"text":"、彼は考えを変えない。","reading":"、かれはかんがえをかえない。"}],"translation":"再怎么说，他也不会改变主意。","note":"たって是ても的口语形式。","review":"approved"},
  {"id":"usage:tatte:verb:遊ぶ:あそぶ","senseId":"verb:遊ぶ:あそぶ","meaning":"玩耍","form":"tatte","scene":"安慰队员：休息一天不会抹去此前训练。","before":[{"text":"一日","reading":"いちにち"}],"after":[{"text":"、今までの練習が無駄になるわけじゃないよ。","reading":"、いままでのれんしゅうがむだになるわけじゃないよ。"}],"translation":"就算玩一天，此前的练习也不会因此白费。","note":"たって是ても的口语形式。","review":"approved"},
  {"id":"usage:tatte:verb:分かる:わかる","senseId":"verb:分かる:わかる","meaning":"明白","form":"tatte","scene":"即使明白说明，不去实践也没有意义。","before":[{"text":"説明の内容が","reading":"せつめいのないようが"}],"after":[{"text":"、実行しなければ意味がない。","reading":"、じっこうしなければいみがない。"}],"translation":"即使明白说明，不去实践也没有意义。","note":"たって是ても的口语形式。","review":"approved"},
  {"id":"usage:tatte:verb:起きる:おきる","senseId":"verb:起きる:おきる","meaning":"起床","form":"tatte","scene":"约定时间快到了，朋友现在起床也会迟到。","before":[{"text":"今から","reading":"いまから"}],"after":[{"text":"、約束の時間には間に合わないよ。","reading":"、やくそくのじかんにはまにあわないよ。"}],"translation":"就算现在起床，也赶不上约定的时间了。","note":"たって是ても的口语形式。","review":"approved"}
];
