// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:nagara:verb:書く:かく","senseId":"verb:書く:かく","meaning":"写；书写","form":"nagara","scene":"边写信边和朋友通电话。","before":[{"text":"手紙を","reading":"てがみを"}],"after":[{"text":"、友達と電話で話した。","reading":"、ともだちとでんわではなした。"}],"translation":"一边写信，一边和朋友通了电话。","review":"approved"},
  {"id":"usage:nagara:verb:話す:はなす","senseId":"verb:話す:はなす","meaning":"说；交谈","form":"nagara","scene":"和朋友聊天时一起走去车站。","before":[{"text":"友達と","reading":"ともだちと"}],"after":[{"text":"、駅まで歩いた。","reading":"、えきまであるいた。"}],"translation":"一边和朋友聊天，一边走到了车站。","review":"approved"},
  {"id":"usage:nagara:verb:遊ぶ:あそぶ","senseId":"verb:遊ぶ:あそぶ","meaning":"玩耍","form":"nagara","scene":"孩子们在公园玩耍时唱歌。","before":[{"text":"子どもたちは公園で","reading":"こどもたちはこうえんで"}],"after":[{"text":"、歌を歌った。","reading":"、うたをうたった。"}],"translation":"孩子们一边在公园玩耍，一边唱了歌。","review":"approved"},
  {"id":"usage:nagara:verb:買う:かう","senseId":"verb:買う:かう","meaning":"购买","form":"nagara","scene":"买纪念品时和店员商量选择。","before":[{"text":"旅行先でお土産を","reading":"りょこうさきでおみやげを"}],"after":[{"text":"、店員と相談した。","reading":"、てんいんとそうだんした。"}],"translation":"在旅行地一边买纪念品，一边和店员商量。","review":"approved"},
  {"id":"usage:nagara:verb:寝る:ねる","senseId":"verb:寝る:ねる","meaning":"睡觉","form":"nagara","scene":"婴儿睡觉时手还在轻轻动。","before":[{"text":"赤ちゃんは","reading":"あかちゃんは"}],"after":[{"text":"、手を動かしている。","reading":"、てをうごかしている。"}],"translation":"婴儿一边睡觉，手一边动着。","review":"approved"},
  {"id":"usage:tsutsu:verb:書く:かく","senseId":"verb:書く:かく","meaning":"写；书写","form":"tsutsu","scene":"边记录边确认工作的进展。","before":[{"text":"記録を","reading":"きろくを"}],"after":[{"text":"、作業の進み具合を確認した。","reading":"、さぎょうのすすみぐあいをかくにんした。"}],"translation":"一边写记录，一边确认工作的进展。","review":"approved"},
  {"id":"usage:tsutsu:verb:話す:はなす","senseId":"verb:話す:はなす","meaning":"说；交谈","form":"tsutsu","scene":"和参加者交谈并整理问题。","before":[{"text":"参加者と","reading":"さんかしゃと"}],"after":[{"text":"、問題点を整理した。","reading":"、もんだいてんをせいりした。"}],"translation":"一边和参加者交谈，一边整理问题。","review":"approved"},
  {"id":"usage:tsutsu:verb:遊ぶ:あそぶ","senseId":"verb:遊ぶ:あそぶ","meaning":"玩耍","form":"tsutsu","scene":"孩子们在户外玩耍，接触和了解大自然。","before":[{"text":"子どもたちは屋外で","reading":"こどもたちはおくがいで"}],"after":[{"text":"、自然について学んでいる。","reading":"、しぜんについてまなんでいる。"}],"translation":"孩子们一边在户外玩耍，一边了解大自然。","review":"approved"},
  {"id":"usage:tsutsu:verb:買う:かう","senseId":"verb:買う:かう","meaning":"购买","form":"tsutsu","scene":"买食材时同时思考当天的菜单。","before":[{"text":"必要な食材を","reading":"ひつようなしょくざいを"}],"after":[{"text":"、献立を考えた。","reading":"、こんだてをかんがえた。"}],"translation":"一边买需要的食材，一边考虑了菜单。","review":"approved"}
];
