// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:ba:verb:知る:しる","senseId":"verb:知る:しる","meaning":"知道","form":"ba","scene":"讨论了解争执的来龙去脉有何帮助。","before":[{"text":"詳しい事情を","reading":"くわしいじじょうを"}],"after":[{"text":"、彼の決断も理解できます。","reading":"、かれのけつだんもりかいできます。"}],"translation":"如果知道详细情况，就也能理解他的决定。","review":"approved"},
  {"id":"usage:ba:verb:思う:おもう","senseId":"verb:思う:おもう","meaning":"想；认为","form":"ba","scene":"独自在外工作时想起家人给自己鼓劲。","before":[{"text":"家族のことを","reading":"かぞくのことを"}],"after":[{"text":"、もう少し頑張れます。","reading":"、もうすこしがんばれます。"}],"translation":"想到家人，就能再努力一阵子。","review":"approved"},
  {"id":"usage:ba:verb:忘れる:わすれる","senseId":"verb:忘れる:わすれる","meaning":"忘记","form":"ba","scene":"向新用户说明记住密码的重要性。","before":[{"text":"パスワードを","reading":"パスワードを"}],"after":[{"text":"、ログインできません。","reading":"、ログインできません。"}],"translation":"如果忘记密码，就无法登录。","review":"approved"},
  {"id":"usage:ba:verb:いる:いる","senseId":"verb:いる:いる","meaning":"在；有（生物）","form":"ba","scene":"确认家中是否有人能帮忙收快递。","before":[{"text":"家に誰かが","reading":"いえにだれかが"}],"after":[{"text":"、荷物を受け取ってもらえます。","reading":"、にもつをうけとってもらえます。"}],"translation":"只要家里有人，就能请他帮忙收包裹。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:高い:たかい","senseId":"adjective:高い:たかい","meaning":"高；贵","form":"adjectiveBa","scene":"比较旅行方案时先考虑费用是否合适。","before":[{"text":"料金が","reading":"りょうきんが"}],"after":[{"text":"、別のプランを選びます。","reading":"、べつのプランをえらびます。"}],"translation":"如果费用高，就选择其他方案。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:元気:げんき","senseId":"adjective:元気:げんき","meaning":"精神；健康","form":"adjectiveBa","scene":"约好周末见面但先顾及朋友的身体。","before":[{"text":"週末、あなたが","reading":"しゅうまつ、あなたが"}],"after":[{"text":"、一緒に散歩しましょう。","reading":"、いっしょにさんぽしましょう。"}],"translation":"周末你身体好的话，我们一起散步吧。","review":"approved"},
  {"id":"usage:tara:verb:知る:しる","senseId":"verb:知る:しる","meaning":"知道","form":"tara","scene":"等待比赛结果时请朋友也通知自己。","before":[{"text":"結果を","reading":"けっかを"}],"after":[{"text":"、私にも教えてください。","reading":"、わたしにもおしえてください。"}],"translation":"得知结果后，也请告诉我。","review":"approved"},
  {"id":"usage:tara:verb:思う:おもう","senseId":"verb:思う:おもう","meaning":"想；认为","form":"tara","scene":"交代工地新人察觉危险时及时停工。","before":[{"text":"危ないと","reading":"あぶないと"}],"after":[{"text":"、すぐに作業をやめてください。","reading":"、すぐにさぎょうをやめてください。"}],"translation":"如果觉得危险，就请立刻停止作业。","review":"approved"},
  {"id":"usage:tara:verb:忘れる:わすれる","senseId":"verb:忘れる:わすれる","meaning":"忘记","form":"tara","scene":"提醒同伴办理手续时需要带证件。","before":[{"text":"身分証を","reading":"みぶんしょうを"}],"after":[{"text":"、受付で手続きができません。","reading":"、うけつけでてつづきができません。"}],"translation":"如果忘带身份证件，就无法在接待处办理手续。","review":"approved"},
  {"id":"usage:tara:verb:いる:いる","senseId":"verb:いる:いる","meaning":"在；有（生物）","form":"tara","scene":"在会场迷路时决定找工作人员问路。","before":[{"text":"会場にスタッフが","reading":"かいじょうにスタッフが"}],"after":[{"text":"、受付の場所を聞いてみます。","reading":"、うけつけのばしょをきいてみます。"}],"translation":"如果会场有工作人员，我就试着问一下接待处在哪里。","review":"approved"}
];
