// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:adjectiveBa:adjective:優しい:やさしい","senseId":"adjective:優しい:やさしい","meaning":"温柔","form":"adjectiveBa","scene":"为孩子选老师时重视老师是否温柔。","before":[{"text":"先生が","reading":"せんせいが"}],"after":[{"text":"、子どもも安心して質問できます。","reading":"、こどももあんしんしてしつもんできます。"}],"translation":"老师温柔的话，孩子也能安心提问。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:まずい:まずい","senseId":"adjective:まずい:まずい","meaning":"难吃；糟糕","form":"adjectiveBa","scene":"朋友担心浪费食物时劝他不必勉强吃。","before":[{"text":"料理が","reading":"りょうりが"}],"after":[{"text":"、無理に全部食べなくてもいいです。","reading":"、むりにぜんぶたべなくてもいいです。"}],"translation":"菜不好吃的话，不必勉强全部吃完。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:遅い:おそい","senseId":"adjective:遅い:おそい","meaning":"迟；慢","form":"adjectiveBa","scene":"关心家人晚归时是否需要去车站接人。","before":[{"text":"帰りが","reading":"かえりが"}],"after":[{"text":"、駅まで迎えに行きます。","reading":"、えきまでむかえにいきます。"}],"translation":"回得晚的话，我就去车站接你。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:近い:ちかい","senseId":"adjective:近い:ちかい","meaning":"近","form":"adjectiveBa","scene":"讨论搬到学校附近能给早晨带来的便利。","before":[{"text":"家が学校に","reading":"いえががっこうに"}],"after":[{"text":"、朝は少しゆっくりできます。","reading":"、あさはすこしゆっくりできます。"}],"translation":"家离学校近的话，早晨就能从容一些。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:長い:ながい","senseId":"adjective:長い:ながい","meaning":"长","form":"adjectiveBa","scene":"孩子试穿新衣服时给出调整袖口的办法。","before":[{"text":"袖が","reading":"そでが"}],"after":[{"text":"、少し折って着てください。","reading":"、すこしおってきてください。"}],"translation":"袖子长的话，请折起来一点再穿。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:多い:おおい","senseId":"adjective:多い:おおい","meaning":"多","form":"adjectiveBa","scene":"朋友收拾旅行用品时提出借大包给他。","before":[{"text":"荷物が","reading":"にもつが"}],"after":[{"text":"、大きいかばんを貸します。","reading":"、おおきいかばんをかします。"}],"translation":"行李多的话，我把大包借给你。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:明るい:あかるい","senseId":"adjective:明るい:あかるい","meaning":"明亮；开朗","form":"adjectiveBa","scene":"拍照前判断房间的光线是否足够。","before":[{"text":"部屋が","reading":"へやが"}],"after":[{"text":"、フラッシュは必要ありません。","reading":"、フラッシュはひつようありません。"}],"translation":"房间明亮的话，就不需要闪光灯。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:重い:おもい","senseId":"adjective:重い:おもい","meaning":"重","form":"adjectiveBa","scene":"看到朋友提行李时表示可以帮忙分担。","before":[{"text":"かばんが","reading":"かばんが"}],"after":[{"text":"、私が持ちますよ。","reading":"、わたしがもちますよ。"}],"translation":"包重的话，我来拿吧。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:強い:つよい","senseId":"adjective:強い:つよい","meaning":"强","form":"adjectiveBa","scene":"出海前根据风力决定是否取消航行。","before":[{"text":"風が","reading":"かぜが"}],"after":[{"text":"、船は出せません。","reading":"、ふねはだせません。"}],"translation":"风大的话，就无法开船出海。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:可愛い:かわいい","senseId":"adjective:可愛い:かわいい","meaning":"可爱","form":"adjectiveBa","scene":"挑选衣服时说明喜欢可爱款式的偏好。","before":[{"text":"デザインが","reading":"デザインが"}],"after":[{"text":"、少し高くても買いたいです。","reading":"、すこしたかくてもかいたいです。"}],"translation":"款式可爱的话，稍微贵一点我也想买。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:痛い:いたい","senseId":"adjective:痛い:いたい","meaning":"疼痛","form":"adjectiveBa","scene":"练习时教练叮嘱学员注意膝盖的感受。","before":[{"text":"膝が","reading":"ひざが"}],"after":[{"text":"、今日","reading":"、きょう"},{"text":"は"},{"text":"走らないでください。","reading":"はしらないでください。"}],"translation":"膝盖疼的话，今天请不要跑步。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:欲しい:ほしい","senseId":"adjective:欲しい:ほしい","meaning":"想要","form":"adjectiveBa","scene":"朋友喜欢自己做的书签便提出送给他。","before":[{"text":"このしおりが","reading":"このしおりが"}],"after":[{"text":"、一枚あげます。","reading":"、いちまいあげます。"}],"translation":"想要这种书签的话，我送你一张。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:白い:しろい","senseId":"adjective:白い:しろい","meaning":"白","form":"adjectiveBa","scene":"挑选作画纸张时说明纸张需要的颜色。","before":[{"text":"紙が","reading":"かみが"}],"after":[{"text":"、裏に文字があっても使えます。","reading":"、うらにもじがあってもつかえます。"}],"translation":"纸是白色的话，背面有文字也能用。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:青い:あおい","senseId":"adjective:青い:あおい","meaning":"蓝；青","form":"adjectiveBa","scene":"选晴天拍照时希望天空颜色衬托花朵。","before":[{"text":"空が","reading":"そらが"}],"after":[{"text":"、白い花がよく映えます。","reading":"、しろいはながよくはえます。"}],"translation":"天空蓝的话，白花会显得很突出。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:甘い:あまい","senseId":"adjective:甘い:あまい","meaning":"甜","form":"adjectiveBa","scene":"给孩子调果汁时说明太甜时如何稀释。","before":[{"text":"ジュースが","reading":"ジュースが"}],"after":[{"text":"、水で少し薄めてください。","reading":"、みずですこしうすめてください。"}],"translation":"果汁甜的话，请加水稀释一点。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:若い:わかい","senseId":"adjective:若い:わかい","meaning":"年轻","form":"adjectiveBa","scene":"园艺师解释为什么应趁树龄较小时移栽。","before":[{"text":"木が","reading":"きが"}],"after":[{"text":"、別の場所に移しやすいです。","reading":"、べつのばしょにうつしやすいです。"}],"translation":"树还年轻的话，就比较容易移到别处。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:便利:べんり","senseId":"adjective:便利:べんり","meaning":"方便","form":"adjectiveBa","scene":"试用手机应用后决定是否长期使用。","before":[{"text":"このアプリが","reading":"このアプリが"}],"after":[{"text":"、これからも使いたいです。","reading":"、これからもつかいたいです。"}],"translation":"这个应用方便的话，我以后也想继续用。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:簡単:かんたん","senseId":"adjective:簡単:かんたん","meaning":"简单","form":"adjectiveBa","scene":"朋友提到一道菜时希望学简单的做法。","before":[{"text":"作り方が","reading":"つくりかたが"}],"after":[{"text":"、私にも教えてください。","reading":"、わたしにもおしえてください。"}],"translation":"做法简单的话，也请教教我。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:上手:じょうず","senseId":"adjective:上手:じょうず","meaning":"擅长","form":"adjectiveBa","scene":"布置文化节会场时请擅长画画的人帮忙。","before":[{"text":"絵が","reading":"えが"}],"after":[{"text":"、ポスターを描いてもらえませんか。","reading":"、ポスターをかいてもらえませんか。"}],"translation":"你擅长画画的话，能请你画张海报吗？","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:好き:すき","senseId":"adjective:好き:すき","meaning":"喜欢","form":"adjectiveBa","scene":"得知朋友喜欢推理小说后邀他去书店。","before":[{"text":"推理小説が","reading":"すいりしょうせつが"}],"after":[{"text":"、この本屋に行ってみませんか。","reading":"、このほんやにいってみませんか。"}],"translation":"喜欢推理小说的话，要不要去这家书店看看？","review":"approved"}
];
