// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:adjectiveBa:adjective:面白い:おもしろい","senseId":"adjective:面白い:おもしろい","meaning":"有趣","form":"adjectiveBa","scene":"先试看电视剧，觉得有趣就继续看。","before":[{"text":"このドラマが","reading":"このドラマが"}],"after":[{"text":"、来週も見ます。","reading":"、らいしゅうもみます。"}],"translation":"这部电视剧有趣的话，下周我也看。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:易しい:やさしい","senseId":"adjective:易しい:やさしい","meaning":"容易","form":"adjectiveBa","scene":"弟弟想独自做题，简单的应该没问题。","before":[{"text":"問題が","reading":"もんだいが"}],"after":[{"text":"、弟も一人で解けます。","reading":"、おとうともひとりでとけます。"}],"translation":"题目简单的话，弟弟也能独自解答。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:美味しい:おいしい","senseId":"adjective:美味しい:おいしい","meaning":"好吃","form":"adjectiveBa","scene":"想试试这家面包店，好吃就再买。","before":[{"text":"このパンが","reading":"このパンが"}],"after":[{"text":"、また買いに来ます。","reading":"、またかいにきます。"}],"translation":"这面包好吃的话，我还会来买。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:早い:はやい","senseId":"adjective:早い:はやい","meaning":"早","form":"adjectiveBa","scene":"安排明天的出发时间，早出发就早到。","before":[{"text":"出発が","reading":"しゅっぱつが"}],"after":[{"text":"、昼前に着きます。","reading":"、ひるまえにつきます。"}],"translation":"出发早的话，中午之前就能到。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:速い:はやい","senseId":"adjective:速い:はやい","meaning":"快速","form":"adjectiveBa","scene":"散步时朋友可能跟不上，可以放慢脚步。","before":[{"text":"歩くのが","reading":"あるくのが"}],"after":[{"text":"、遠慮なく言ってください。","reading":"、えんりょなくいってください。"}],"translation":"如果我走得快，请不要客气，告诉我。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:遠い:とおい","senseId":"adjective:遠い:とおい","meaning":"远","form":"adjectiveBa","scene":"正在选酒店，离车站远就考虑另一家。","before":[{"text":"駅から","reading":"えきから"}],"after":[{"text":"、別のホテルにしましょう。","reading":"、べつのホテルにしましょう。"}],"translation":"离车站远的话，就选另一家酒店吧。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:短い:みじかい","senseId":"adjective:短い:みじかい","meaning":"短","form":"adjectiveBa","scene":"窗帘买来不知够不够长，可以再接一段。","before":[{"text":"カーテンが","reading":"カーテンが"}],"after":[{"text":"、布を足せます。","reading":"、ぬのをたせます。"}],"translation":"窗帘短的话，可以再接一块布。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:少ない:すくない","senseId":"adjective:少ない:すくない","meaning":"少","form":"adjectiveBa","scene":"报名人数还未确定，人少就用小教室。","before":[{"text":"参加者が","reading":"さんかしゃが"}],"after":[{"text":"、小さい教室で十分です。","reading":"、ちいさいきょうしつでじゅうぶんです。"}],"translation":"参加者少的话，小教室就够了。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:暗い:くらい","senseId":"adjective:暗い:くらい","meaning":"昏暗","form":"adjectiveBa","scene":"客人要在屋里看书，可以打开台灯。","before":[{"text":"部屋が","reading":"へやが"}],"after":[{"text":"、このライトをつけてください。","reading":"、このライトをつけてください。"}],"translation":"屋里暗的话，请打开这盏灯。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:軽い:かるい","senseId":"adjective:軽い:かるい","meaning":"轻","form":"adjectiveBa","scene":"去车站没有电梯，轻行李可以自己提。","before":[{"text":"荷物が","reading":"にもつが"}],"after":[{"text":"、一人で運べます。","reading":"、ひとりではこべます。"}],"translation":"行李轻的话，我一个人就搬得动。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:弱い:よわい","senseId":"adjective:弱い:よわい","meaning":"弱","form":"adjectiveBa","scene":"公园放风筝，风弱的时候很难飞高。","before":[{"text":"風が","reading":"かぜが"}],"after":[{"text":"、たこは高く上がりません。","reading":"、たこはたかくあがりません。"}],"translation":"风弱的话，风筝就飞不高。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:怖い:こわい","senseId":"adjective:怖い:こわい","meaning":"可怕","form":"adjectiveBa","scene":"朋友不敢独自进暗房，我可以陪同。","before":[{"text":"一人で入るのが","reading":"ひとりではいるのが"}],"after":[{"text":"、私も一緒に行きます。","reading":"、わたしもいっしょにいきます。"}],"translation":"害怕一个人进去的话，我陪你去。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:眠い:ねむい","senseId":"adjective:眠い:ねむい","meaning":"困倦","form":"adjectiveBa","scene":"朋友昨晚没睡好，可以先睡一会儿。","before":[],"after":[{"text":"、少し寝てもいいですよ。","reading":"、すこしねてもいいですよ。"}],"translation":"困了的话，可以睡一会儿。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:赤い:あかい","senseId":"adjective:赤い:あかい","meaning":"红","form":"adjectiveBa","scene":"看樱桃是否成熟，变红的就可以摘。","before":[{"text":"実が","reading":"みが"}],"after":[{"text":"、食べ頃です。","reading":"、たべごろです。"}],"translation":"果实是红色的话，就到了适合食用的时候。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:黒い:くろい","senseId":"adjective:黒い:くろい","meaning":"黑","form":"adjectiveBa","scene":"挑选工作服，黑色比较不容易显脏。","before":[{"text":"服が","reading":"ふくが"}],"after":[{"text":"、汚れが目立ちません。","reading":"、よごれがめだちません。"}],"translation":"衣服是黑色的话，污渍就不显眼。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:丸い:まるい","senseId":"adjective:丸い:まるい","meaning":"圆","form":"adjectiveBa","scene":"做手工球，圆的形状比较容易滚动。","before":[{"text":"形が","reading":"かたちが"}],"after":[{"text":"、転がりやすいです。","reading":"、ころがりやすいです。"}],"translation":"形状圆的话，就容易滚动。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:辛い:からい","senseId":"adjective:辛い:からい","meaning":"辣","form":"adjectiveBa","scene":"朋友吃不了辣咖喱，可以加些酸奶。","before":[{"text":"カレーが","reading":"カレーが"}],"after":[{"text":"、ヨーグルトを足してください。","reading":"、ヨーグルトをたしてください。"}],"translation":"咖喱辣的话，请加些酸奶。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:かっこいい:かっこいい","senseId":"adjective:かっこいい:かっこいい","meaning":"帅；酷","form":"adjectiveBa","scene":"弟弟挑运动鞋，外观帅气就想买。","before":[{"text":"デザインが","reading":"デザインが"}],"after":[{"text":"、弟は買いたがるでしょう。","reading":"、おとうとはかいたがるでしょう。"}],"translation":"设计很酷的话，弟弟大概会想买。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:親切:しんせつ","senseId":"adjective:親切:しんせつ","meaning":"亲切","form":"adjectiveBa","scene":"选择驾校时，希望教练待人亲切。","before":[{"text":"先生が","reading":"せんせいが"}],"after":[{"text":"、安心して質問できます。","reading":"、あんしんしてしつもんできます。"}],"translation":"老师亲切的话，就能放心提问。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:不便:ふべん","senseId":"adjective:不便:ふべん","meaning":"不方便","form":"adjectiveBa","scene":"游客不确定住哪，交通不便就换地方。","before":[{"text":"交通が","reading":"こうつうが"}],"after":[{"text":"、別の場所に泊まりましょう。","reading":"、べつのばしょにとまりましょう。"}],"translation":"交通不方便的话，就住在别的地方吧。","review":"approved"}
];
