// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:adjectiveBa:adjective:きれい:きれい","senseId":"adjective:きれい:きれい","meaning":"漂亮；干净","form":"adjectiveBa","scene":"收拾餐桌时确认盘子是否还需要清洗。","before":[{"text":"この皿が","reading":"このさらが"}],"after":[{"text":"、そのまま食器棚に戻してください。","reading":"、そのまましょっきだなにもどしてください。"}],"translation":"这个盘子干净的话，请直接放回餐具柜。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:大切:たいせつ","senseId":"adjective:大切:たいせつ","meaning":"重要；珍贵","form":"adjectiveBa","scene":"朋友担心弄丢纪念照片时给出保管建议。","before":[{"text":"その写真が","reading":"そのしゃしんが"}],"after":[{"text":"、封筒に入れておきましょう。","reading":"、ふうとうにいれておきましょう。"}],"translation":"那张照片很珍贵的话，我们先把它装进信封吧。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:暇:ひま","senseId":"adjective:暇:ひま","meaning":"空闲","form":"adjectiveBa","scene":"邀请周末有空的朋友一起去看展览。","before":[{"text":"週末","reading":"しゅうまつ"}],"after":[{"text":"、一緒に展覧会に行きませんか。","reading":"、いっしょにてんらんかいにいきませんか。"}],"translation":"周末有空的话，要不要一起去看展览？","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:丈夫:じょうぶ","senseId":"adjective:丈夫:じょうぶ","meaning":"结实；健康","form":"adjectiveBa","scene":"准备寄书时检查纸箱是否能承重。","before":[{"text":"この箱が","reading":"このはこが"}],"after":[{"text":"、本を入れて送れます。","reading":"、ほんをいれておくれます。"}],"translation":"这个箱子结实的话，就能装书寄出去。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:危険:きけん","senseId":"adjective:危険:きけん","meaning":"危险","form":"adjectiveBa","scene":"徒步途中询问山路状况并准备换路线。","before":[{"text":"この道が","reading":"このみちが"}],"after":[{"text":"、別の道を探しましょう。","reading":"、べつのみちをさがしましょう。"}],"translation":"这条路危险的话，我们就找别的路吧。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:真面目:まじめ","senseId":"adjective:真面目:まじめ","meaning":"认真","form":"adjectiveBa","scene":"招店员时讨论肯认真工作就可从头培养。","before":[{"text":"仕事に対して","reading":"しごとにたいして"}],"after":[{"text":"、経験が少なくても教えがいがあります。","reading":"、けいけんがすくなくてもおしえがいがあります。"}],"translation":"对工作认真的话，即使经验少也值得教。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:特別:とくべつ","senseId":"adjective:特別:とくべつ","meaning":"特别","form":"adjectiveBa","scene":"朋友挑蛋糕时表示特殊日子可以奢侈些。","before":[{"text":"今日が","reading":"きょうが"}],"after":[{"text":"、少し高いケーキにしましょう。","reading":"、すこしたかいケーキにしましょう。"}],"translation":"今天是特别的日子的话，就选贵一点的蛋糕吧。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:変:へん","senseId":"adjective:変:へん","meaning":"奇怪","form":"adjectiveBa","scene":"穿新衣服照镜子时请朋友直说搭配如何。","before":[{"text":"この組み合わせが","reading":"このくみあわせが"}],"after":[{"text":"、遠慮せずに言ってください。","reading":"、えんりょせずにいってください。"}],"translation":"这个搭配奇怪的话，请不要客气，直接告诉我。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:残念:ざんねん","senseId":"adjective:残念:ざんねん","meaning":"遗憾","form":"adjectiveBa","scene":"朋友遗憾错过演出时提议预约下一场。","before":[{"text":"行けなかったのが","reading":"いけなかったのが"}],"after":[{"text":"、次の公演を予約しませんか。","reading":"、つぎのこうえんをよやくしませんか。"}],"translation":"如果你为没能去而感到遗憾，要不要预约下一场演出？","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:無理:むり","senseId":"adjective:無理:むり","meaning":"勉强；不可能","form":"adjectiveBa","scene":"安排会面时表示今天不行便改到明天。","before":[{"text":"今日が","reading":"きょうが"}],"after":[{"text":"、明日にしましょう。","reading":"、あしたにしましょう。"}],"translation":"今天不行的话，就改到明天吧。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:可能:かのう","senseId":"adjective:可能:かのう","meaning":"可能","form":"adjectiveBa","scene":"请求同事尽量在当天发来所需资料。","before":[{"text":"今日中の送付が","reading":"きょうじゅうのそうふが"}],"after":[{"text":"、メールで送ってください。","reading":"、メールでおくってください。"}],"translation":"如果今天之内能发送，请通过电子邮件发来。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:健康:けんこう","senseId":"adjective:健康:けんこう","meaning":"健康","form":"adjectiveBa","scene":"照顾老狗时讨论身体好便可短距离散步。","before":[{"text":"犬が","reading":"いぬが"}],"after":[{"text":"、短い散歩を毎日続けられます。","reading":"、みじかいさんぽをまいにちつづけられます。"}],"translation":"狗身体健康的话，就能每天坚持短距离散步。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:熱心:ねっしん","senseId":"adjective:熱心:ねっしん","meaning":"热心","form":"adjectiveBa","scene":"教练看到学员十分热心便邀请他再来练习。","before":[{"text":"そんなに","reading":"そんなに"}],"after":[{"text":"、次の練習にも参加してみませんか。","reading":"、つぎのれんしゅうにもさんかしてみませんか。"}],"translation":"你这么热心的话，要不要也来参加下次练习？","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:楽:らく","senseId":"adjective:楽:らく","meaning":"轻松","form":"adjectiveBa","scene":"安排见面时表示也可以用轻松的电话交谈。","before":[{"text":"電話の方が","reading":"でんわのほうが"}],"after":[{"text":"、電話で話しましょう。","reading":"、でんわではなしましょう。"}],"translation":"打电话更轻松的话，我们就用电话聊吧。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:正直:しょうじき","senseId":"adjective:正直:しょうじき","meaning":"诚实","form":"adjectiveBa","scene":"挑选合作伙伴时把诚实放在经验之前。","before":[{"text":"相手が","reading":"あいてが"}],"after":[{"text":"、経験が少なくても一緒に働きたいです。","reading":"、けいけんがすくなくてもいっしょにはたらきたいです。"}],"translation":"对方诚实的话，即使经验少，我也愿意一起工作。","review":"approved"},
  {"id":"usage:tara:verb:開ける:あける","senseId":"verb:開ける:あける","meaning":"打开","form":"tara","scene":"回忆打开窗户时感受到清凉的风。","before":[{"text":"窓を","reading":"まどを"}],"after":[{"text":"、涼しい風が入ってきました。","reading":"、すずしいかぜがはいってきました。"}],"translation":"打开窗户后，一阵凉风吹了进来。","review":"approved"}
];
