// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:adjectiveBa:adjective:複雑:ふくざつ","senseId":"adjective:複雑:ふくざつ","meaning":"复杂","form":"adjectiveBa","scene":"新规则可能难懂，需要时可以画图解释。","before":[{"text":"ルールが","reading":"ルールが"}],"after":[{"text":"、図を使って説明します。","reading":"、ずをつかってせつめいします。"}],"translation":"规则复杂的话，我会用图来说明。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:下手:へた","senseId":"adjective:下手:へた","meaning":"不擅长","form":"adjectiveBa","scene":"制作班级海报，不擅长画画可以用照片。","before":[{"text":"絵が","reading":"えが"}],"after":[{"text":"、写真を使ってもいいですよ。","reading":"、しゃしんをつかってもいいですよ。"}],"translation":"不擅长画画的话，也可以用照片。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:嫌い:きらい","senseId":"adjective:嫌い:きらい","meaning":"讨厌","form":"adjectiveBa","scene":"朋友不爱喝咖啡，也可以改喝茶。","before":[{"text":"コーヒーが","reading":"コーヒーが"}],"after":[{"text":"、お茶にしましょうか。","reading":"、おちゃにしましょうか。"}],"translation":"不喜欢咖啡的话，改喝茶好吗？","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:有名:ゆうめい","senseId":"adjective:有名:ゆうめい","meaning":"有名","form":"adjectiveBa","scene":"不知道餐厅在哪，有名的话司机应该知道。","before":[{"text":"その店が","reading":"そのみせが"}],"after":[{"text":"、運転手も知っているでしょう。","reading":"、うんてんしゅもしっているでしょう。"}],"translation":"那家店有名的话，司机应该也知道。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:賑やか:にぎやか","senseId":"adjective:賑やか:にぎやか","meaning":"热闹","form":"adjectiveBa","scene":"客人怕吵，外面热闹可以把窗关上。","before":[{"text":"外が","reading":"そとが"}],"after":[{"text":"、窓を閉めましょう。","reading":"、まどをしめましょう。"}],"translation":"外面热闹的话，把窗关上吧。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:安全:あんぜん","senseId":"adjective:安全:あんぜん","meaning":"安全","form":"adjectiveBa","scene":"选好河边步道前，先确认能否安全通行。","before":[{"text":"この道が","reading":"このみちが"}],"after":[{"text":"、歩いて行きましょう。","reading":"、あるいていきましょう。"}],"translation":"这条路安全的话，就走过去吧。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:自由:じゆう","senseId":"adjective:自由:じゆう","meaning":"自由","form":"adjectiveBa","scene":"参加聚会前问过要求，穿着可自行选择。","before":[{"text":"服装が","reading":"ふくそうが"}],"after":[{"text":"、ジーンズで行きます。","reading":"、ジーンズでいきます。"}],"translation":"服装自由的话，我就穿牛仔裤去。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:丁寧:ていねい","senseId":"adjective:丁寧:ていねい","meaning":"礼貌；细致","form":"adjectiveBa","scene":"写客户回信时，关键是语气礼貌。","before":[{"text":"言葉遣いが","reading":"ことばづかいが"}],"after":[{"text":"、短い返事でも失礼にはなりません。","reading":"、みじかいへんじでもしつれいにはなりません。"}],"translation":"措辞礼貌的话，简短的回复也不会失礼。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:普通:ふつう","senseId":"adjective:普通:ふつう","meaning":"普通","form":"adjectiveBa","scene":"比较两家餐厅，远的那家味道未必特别。","before":[{"text":"味が","reading":"あじが"}],"after":[{"text":"、近くの店で食べましょう。","reading":"、ちかくのみせでたべましょう。"}],"translation":"味道普通的话，就在附近的店吃吧。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:幸せ:しあわせ","senseId":"adjective:幸せ:しあわせ","meaning":"幸福","form":"adjectiveBa","scene":"朋友担心父母反对婚事，母亲表达支持。","before":[{"text":"あなたが","reading":"あなたが"}],"after":[{"text":"、私もうれしいです。","reading":"、わたしもうれしいです。"}],"translation":"你幸福的话，我也高兴。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:素敵:すてき","senseId":"adjective:素敵:すてき","meaning":"出色；迷人","form":"adjectiveBa","scene":"打算挑张照片装饰客厅，好看的就挂上。","before":[{"text":"その写真が","reading":"そのしゃしんが"}],"after":[{"text":"、居間に飾りたいです。","reading":"、いまにかざりたいです。"}],"translation":"那张照片好看的话，我想把它挂在客厅。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:十分:じゅうぶん","senseId":"adjective:十分:じゅうぶん","meaning":"充分","form":"adjectiveBa","scene":"预算还在核算，钱够的话可安排两晚。","before":[{"text":"予算が","reading":"よさんが"}],"after":[{"text":"、二泊しましょう。","reading":"、にはくしましょう。"}],"translation":"预算充足的话，我们住两晚吧。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:自然:しぜん","senseId":"adjective:自然:しぜん","meaning":"自然","form":"adjectiveBa","scene":"查看刚拍的人像，笑容自然就采用。","before":[{"text":"笑顔が","reading":"えがおが"}],"after":[{"text":"、この写真を使いましょう。","reading":"、このしゃしんをつかいましょう。"}],"translation":"笑容自然的话，就用这张照片吧。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:新鮮:しんせん","senseId":"adjective:新鮮:しんせん","meaning":"新鲜","form":"adjectiveBa","scene":"去市场买蔬菜，新鲜的话就多买一些。","before":[{"text":"野菜が","reading":"やさいが"}],"after":[{"text":"、少し多めに買います。","reading":"、すこしおおめにかいます。"}],"translation":"蔬菜新鲜的话，我就稍微多买一些。","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:心配:しんぱい","senseId":"adjective:心配:しんぱい","meaning":"担心","form":"adjectiveBa","scene":"朋友在家等孩子，可以打电话确认情况。","before":[{"text":"子どものことが","reading":"こどものことが"}],"after":[{"text":"、電話してみたらどうですか。","reading":"、でんわしてみたらどうですか。"}],"translation":"担心孩子的话，打个电话问问怎么样？","review":"approved"},
  {"id":"usage:adjectiveBa:adjective:快適:かいてき","senseId":"adjective:快適:かいてき","meaning":"舒适","form":"adjectiveBa","scene":"打算先住一晚，住得舒服以后还来。","before":[{"text":"この部屋が","reading":"このへやが"}],"after":[{"text":"、また泊まりたいです。","reading":"、またとまりたいです。"}],"translation":"这个房间舒适的话，我还想再来住。","review":"approved"},
  {"id":"usage:tara:verb:行く:いく","senseId":"verb:行く:いく","meaning":"去；前往","form":"tara","scene":"去车站接朋友，却发现对方已经到了。","before":[{"text":"駅に","reading":"えきに"}],"after":[{"text":"、友達はもう着いていました。","reading":"、ともだちはもうついていました。"}],"translation":"去了车站，发现朋友已经到了。","review":"approved"}
];
