// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:tari:verb:買う:かう","senseId":"verb:買う:かう","meaning":"购买","form":"tari","scene":"旅行中买纪念品，也会拍下当地风景。","before":[{"text":"旅行先では、お土産を","reading":"りょこうさきでは、おみやげを"}],"after":[{"text":"、景色を写真に撮ったりする。","reading":"、けしきをしゃしんにとったりする。"}],"translation":"旅行时会买纪念品，也会把风景拍成照片。","review":"approved"},
  {"id":"usage:tari:verb:泳ぐ:およぐ","senseId":"verb:泳ぐ:およぐ","meaning":"游泳","form":"tari","scene":"夏天去海边游泳，也在沙滩上散步。","before":[{"text":"夏は海で","reading":"なつはうみで"}],"after":[{"text":"、砂浜を歩いたりする。","reading":"、すなはまをあるいたりする。"}],"translation":"夏天会在海里游泳，也会在沙滩上走走。","review":"approved"},
  {"id":"usage:tari:verb:飲む:のむ","senseId":"verb:飲む:のむ","meaning":"喝","form":"tari","scene":"午后在咖啡馆喝茶，也吃一块蛋糕。","before":[{"text":"午後は喫茶店で紅茶を","reading":"ごごはきっさてんでこうちゃを"}],"after":[{"text":"、ケーキを食べたりする。","reading":"、ケーキをたべたりする。"}],"translation":"下午会在咖啡馆喝红茶，也会吃蛋糕。","review":"approved"},
  {"id":"usage:tari:verb:帰る:かえる","senseId":"verb:帰る:かえる","meaning":"回去","form":"tari","scene":"下班后有时直接回家，有时先去超市。","before":[{"text":"仕事の後はまっすぐ家に","reading":"しごとのあとはまっすぐいえに"}],"after":[{"text":"、買い物に寄ったりする。","reading":"、かいものによったりする。"}],"translation":"下班后有时直接回家，有时顺便去买东西。","review":"approved"},
  {"id":"usage:tari:verb:呼ぶ:よぶ","senseId":"verb:呼ぶ:よぶ","meaning":"呼叫","form":"tari","scene":"餐厅里叫服务员，也和朋友商量点什么菜。","before":[{"text":"店では店員を","reading":"みせではてんいんを"}],"after":[{"text":"、友達と注文を相談したりする。","reading":"、ともだちとちゅうもんをそうだんしたりする。"}],"translation":"在店里会叫服务员，也会和朋友商量点什么。","review":"approved"},
  {"id":"usage:tari:verb:取る:とる","senseId":"verb:取る:とる","meaning":"拿取","form":"tari","scene":"整理资料时拿文件，也把重要内容记下来。","before":[{"text":"必要な書類を","reading":"ひつようなしょるいを"}],"after":[{"text":"、要点をメモしたりする。","reading":"、ようてんをメモしたりする。"}],"translation":"会拿取必要文件，也会记下要点之类。","review":"approved"},
  {"id":"usage:tari:verb:歌う:うたう","senseId":"verb:歌う:うたう","meaning":"唱歌","form":"tari","scene":"卡拉OK里唱歌，也和朋友合唱。","before":[{"text":"カラオケでは好きな歌を","reading":"カラオケではすきなうたを"}],"after":[{"text":"、友達と合唱したりする。","reading":"、ともだちとがっしょうしたりする。"}],"translation":"在卡拉OK会唱喜欢的歌，也会和朋友合唱。","review":"approved"},
  {"id":"usage:tari:verb:笑う:わらう","senseId":"verb:笑う:わらう","meaning":"笑","form":"tari","scene":"看喜剧时放声大笑，也会和旁人交换感想。","before":[{"text":"喜劇を見て","reading":"きげきをみて"}],"after":[{"text":"、感想を話したりする。","reading":"、かんそうをはなしたりする。"}],"translation":"看喜剧时会笑，也会聊聊感想。","review":"approved"},
  {"id":"usage:tari:verb:歩く:あるく","senseId":"verb:歩く:あるく","meaning":"走路","form":"tari","scene":"天气晴朗时在公园走走，也坐在长椅上休息。","before":[{"text":"晴れた日は公園を","reading":"はれたひはこうえんを"}],"after":[{"text":"、ベンチで休んだりする。","reading":"、ベンチでやすんだりする。"}],"translation":"天气晴朗时会在公园走走，也会在长椅上休息。","review":"approved"},
  {"id":"usage:tari:verb:脱ぐ:ぬぐ","senseId":"verb:脱ぐ:ぬぐ","meaning":"脱下","form":"tari","scene":"玄关处会脱鞋，也会把外套挂起来。","before":[{"text":"玄関で靴を","reading":"げんかんでくつを"}],"after":[{"text":"、上着を掛けたりする。","reading":"、うわぎをかけたりする。"}],"translation":"会在玄关脱鞋，也会挂起外套之类。","review":"approved"},
  {"id":"usage:tari:verb:貸す:かす","senseId":"verb:貸す:かす","meaning":"借出","form":"tari","scene":"同学需要时借出笔记，也分享参考书。","before":[{"text":"友達にノートを","reading":"ともだちにノートを"}],"after":[{"text":"、参考書を見せたりする。","reading":"、さんこうしょをみせたりする。"}],"translation":"会把笔记借给朋友，也会给朋友看参考书之类。","review":"approved"},
  {"id":"usage:tari:verb:持つ:もつ","senseId":"verb:持つ:もつ","meaning":"持有","form":"tari","scene":"出门时带伞，也随身带着水壶。","before":[{"text":"出かけるときは傘を","reading":"でかけるときはかさを"}],"after":[{"text":"、水筒を持ち歩いたりする。","reading":"、すいとうをもちあるいたりする。"}],"translation":"出门时会带伞，也会随身带着水壶。","review":"approved"},
  {"id":"usage:tari:verb:選ぶ:えらぶ","senseId":"verb:選ぶ:えらぶ","meaning":"选择","form":"tari","scene":"买礼物时挑颜色，也比较不同的包装。","before":[{"text":"贈り物","reading":"おくりもの"},{"text":"の色を","reading":"のいろを"}],"after":[{"text":"、包装を比べたりする。","reading":"、ほうそうをくらべたりする。"}],"translation":"会挑选礼物的颜色，也会比较包装之类。","review":"approved"},
  {"id":"usage:tari:verb:住む:すむ","senseId":"verb:住む:すむ","meaning":"居住","form":"tari","scene":"年轻时住过城市，也在郊外生活过。","before":[{"text":"若いころは都会に","reading":"わかいころはとかいに"}],"after":[{"text":"、郊外で暮らしたりした。","reading":"、こうがいでくらしたりした。"}],"translation":"年轻时住在城市，也曾在郊外生活过。","review":"approved"},
  {"id":"usage:tari:verb:走る:はしる","senseId":"verb:走る:はしる","meaning":"奔跑","form":"tari","scene":"训练时在操场奔跑，也做拉伸运动。","before":[{"text":"練習では運動場を","reading":"れんしゅうではうんどうじょうを"}],"after":[{"text":"、ストレッチをしたりする。","reading":"、ストレッチをしたりする。"}],"translation":"训练时会在操场跑步，也会做拉伸。","review":"approved"},
  {"id":"usage:tari:verb:入る:はいる","senseId":"verb:入る:はいる","meaning":"进入","form":"tari","scene":"逛街时进书店，也去附近的咖啡馆。","before":[{"text":"買い物","reading":"かいもの"},{"text":"の途中で本屋に","reading":"のとちゅうでほんやに"}],"after":[{"text":"、喫茶店に寄ったりする。","reading":"、きっさてんによったりする。"}],"translation":"购物途中会进书店，也会顺便去咖啡馆。","review":"approved"}
];
