// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:tari:verb:着る:きる","senseId":"verb:着る:きる","meaning":"穿","form":"tari","scene":"试衣服时反复穿上、脱下，查看是否合身。","before":[{"text":"試着室で服を","reading":"しちゃくしつでふくを"}],"after":[{"text":"、脱いだりする。","reading":"、ぬいだりする。"}],"translation":"在试衣间把衣服穿上、脱下。","review":"approved"},
  {"id":"usage:tari:verb:調べる:しらべる","senseId":"verb:調べる:しらべる","meaning":"调查","form":"tari","scene":"写报告时查资料、记录出处。","before":[{"text":"資料を","reading":"しりょうを"}],"after":[{"text":"、出典を記録したりする。","reading":"、しゅってんをきろくしたりする。"}],"translation":"会查阅资料，也会记录出处之类。","review":"approved"},
  {"id":"usage:tari:verb:続ける:つづける","senseId":"verb:続ける:つづける","meaning":"继续","form":"tari","scene":"练习时继续练、停下来调整动作。","before":[{"text":"練習を","reading":"れんしゅうを"}],"after":[{"text":"、休んだりする。","reading":"、やすんだりする。"}],"translation":"有时继续练习，有时休息。","review":"approved"},
  {"id":"usage:tari:verb:助ける:たすける","senseId":"verb:助ける:たすける","meaning":"帮助","form":"tari","scene":"照顾队友时帮助他、鼓励他。","before":[{"text":"仲間を","reading":"なかまを"}],"after":[{"text":"、励ましたりする。","reading":"、はげましたりする。"}],"translation":"会帮助同伴，也会鼓励他们之类。","review":"approved"},
  {"id":"usage:tari:verb:できる:できる","senseId":"verb:できる:できる","meaning":"能够；完成","form":"tari","scene":"手工作业进度不一，有时能完成，有时需重做。","before":[{"text":"工作の課題が","reading":"こうさくのかだいが"}],"after":[{"text":"、やり直しになったりする。","reading":"、やりなおしになったりする。"}],"translation":"手工作业有时能完成，有时需要重做。","review":"approved"},
  {"id":"usage:tari:verb:答える:こたえる","senseId":"verb:答える:こたえる","meaning":"回答","form":"tari","scene":"问答练习中回答问题、请对方重复。","before":[{"text":"質問に","reading":"しつもんに"}],"after":[{"text":"、聞き返したりする。","reading":"、ききかえしたりする。"}],"translation":"会回答问题，也会请对方再说一遍之类。","review":"approved"},
  {"id":"usage:tari:verb:止める:とめる","senseId":"verb:止める:とめる","meaning":"停止；阻止","form":"tari","scene":"维修时需要停下机器，也要重新开动。","before":[{"text":"修理中は機械を","reading":"しゅうりちゅうはきかいを"}],"after":[{"text":"、また動かしたりする。","reading":"、またうごかしたりする。"}],"translation":"维修时会停下机器，也会重新开动。","review":"approved"},
  {"id":"usage:tari:verb:受ける:うける","senseId":"verb:受ける:うける","meaning":"接受；参加","form":"tari","scene":"学习期间参加培训课程，也向讲师提问。","before":[{"text":"講習を","reading":"こうしゅうを"}],"after":[{"text":"、講師に質問したりする。","reading":"、こうしにしつもんしたりする。"}],"translation":"会参加培训课程，也会向讲师提问之类。","review":"approved"},
  {"id":"usage:tari:verb:集める:あつめる","senseId":"verb:集める:あつめる","meaning":"收集","form":"tari","scene":"整理研究资料时收集、分类文件。","before":[{"text":"資料を","reading":"しりょうを"}],"after":[{"text":"、分類したりする。","reading":"、ぶんるいしたりする。"}],"translation":"会收集资料，也会进行分类之类。","review":"approved"},
  {"id":"usage:tari:verb:疲れる:つかれる","senseId":"verb:疲れる:つかれる","meaning":"疲劳","form":"tari","scene":"长途旅行中感到疲劳、停下休息。","before":[{"text":"長旅では","reading":"ながたびでは"}],"after":[{"text":"、休んだりする。","reading":"、やすんだりする。"}],"translation":"长途旅行中会感到疲劳、休息之类。","review":"approved"},
  {"id":"usage:tewa:verb:押す:おす","senseId":"verb:押す:おす","meaning":"按；推","form":"tewa","scene":"测试按钮时反复按下又查看屏幕。","before":[{"text":"ボタンを","reading":"ボタンを"}],"after":[{"text":"、画面の変化を確認した。","reading":"、がめんのへんかをかくにんした。"}],"translation":"每按一次按钮，就确认一下画面的变化。","review":"approved"},
  {"id":"usage:tewa:verb:落とす:おとす","senseId":"verb:落とす:おとす","meaning":"弄掉；丢失","form":"tewa","scene":"孩子反复弄掉积木又捡回来。","before":[{"text":"積み木を","reading":"つみきを"}],"after":[{"text":"、拾っている。","reading":"、ひろっている。"}],"translation":"反复弄掉积木，又把它捡起来。","review":"approved"},
  {"id":"usage:tewa:verb:起こす:おこす","senseId":"verb:起こす:おこす","meaning":"叫醒；引起","form":"tewa","scene":"母亲每天做早饭时叫醒孩子，再继续准备。","before":[{"text":"母","reading":"はは"},{"text":"は毎朝、子どもを","reading":"はまいあさ、こどもを"}],"after":[{"text":"、朝食の用意に戻った。","reading":"、ちょうしょくのよういにもどった。"}],"translation":"母亲每天早上叫醒孩子后，就回去继续准备早餐。","review":"approved"},
  {"id":"usage:tewa:verb:並ぶ:ならぶ","senseId":"verb:並ぶ:ならぶ","meaning":"排队；排列","form":"tewa","scene":"孩子们一遍遍排队，反复坐同一个游乐设施。","before":[{"text":"子どもたちは列に","reading":"こどもたちはれつに"}],"after":[{"text":"、同じ乗り物に乗った。","reading":"、おなじのりものにのった。"}],"translation":"孩子们一次次排队，乘坐同一个游乐设施。","review":"approved"},
  {"id":"usage:tewa:verb:喜ぶ:よろこぶ","senseId":"verb:喜ぶ:よろこぶ","meaning":"高兴","form":"tewa","scene":"他每有小小的成功就高兴，还与同伴举杯。","before":[{"text":"彼は小さな成功を","reading":"かれはちいさなせいこうを"}],"after":[{"text":"、仲間と乾杯した。","reading":"、なかまとかんぱいした。"}],"translation":"他为一个个小小的成功而高兴，每次都和同伴干杯。","review":"approved"}
];
