// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:tari:verb:書く:かく","senseId":"verb:書く:かく","meaning":"写；书写","form":"tari","scene":"周末整理房间，写写东西也看看旧照片。","before":[{"text":"週末は手紙を","reading":"しゅうまつはてがみを"}],"after":[{"text":"、古い写真を見たりする。","reading":"、ふるいしゃしんをみたりする。"}],"translation":"周末会写写信，也看看旧照片之类的。","review":"approved"},
  {"id":"usage:tari:verb:話す:はなす","senseId":"verb:話す:はなす","meaning":"说；交谈","form":"tari","scene":"同学会上与老朋友聊天，也看看以前的照片。","before":[{"text":"同窓会では友達と","reading":"どうそうかいではともだちと"}],"after":[{"text":"、昔の写真を見たりする。","reading":"、むかしのしゃしんをみたりする。"}],"translation":"同学会上会和朋友聊天，也看看以前的照片之类的。","review":"approved"},
  {"id":"usage:tari:verb:死ぬ:しぬ","senseId":"verb:死ぬ:しぬ","meaning":"死亡","form":"tari","scene":"这款冒险游戏里，角色会阵亡或丢失道具。","before":[{"text":"このゲームでは、キャラクターが","reading":"このゲームでは、キャラクターが"}],"after":[{"text":"、道具を失ったりする。","reading":"、どうぐをうしなったりする。"}],"translation":"在这款游戏里，角色会阵亡、丢失道具之类的。","review":"approved"},
  {"id":"usage:tari:verb:分かる:わかる","senseId":"verb:分かる:わかる","meaning":"明白","form":"tari","scene":"听课时有时弄懂重点，有时还会留下疑问。","before":[{"text":"授業では要点が","reading":"じゅぎょうではようてんが"}],"after":[{"text":"、疑問が残ったりする。","reading":"、ぎもんがのこったりする。"}],"translation":"上课时有时能明白要点，有时会留下疑问。","review":"approved"},
  {"id":"usage:tari:verb:見る:みる","senseId":"verb:見る:みる","meaning":"看","form":"tari","scene":"下雨的下午在家看看电影，也读读漫画。","before":[{"text":"雨の日の午後は映画を","reading":"あめのひのごごはえいがを"}],"after":[{"text":"、漫画を読んだりする。","reading":"、まんがをよんだりする。"}],"translation":"下雨的下午会看看电影，也读读漫画之类的。","review":"approved"},
  {"id":"usage:tari:verb:来る:くる","senseId":"verb:来る:くる","meaning":"来","form":"tari","scene":"周末朋友有时来家里，有时发消息联系。","before":[{"text":"週末は友達が家に","reading":"しゅうまつはともだちがいえに"}],"after":[{"text":"、メッセージを送ったりする。","reading":"、メッセージをおくったりする。"}],"translation":"周末朋友有时来家里，有时发消息之类的。","review":"approved"},
  {"id":"usage:tewa:verb:書く:かく","senseId":"verb:書く:かく","meaning":"写；书写","form":"tewa","scene":"反复改写申请书草稿，写了又擦掉。","before":[{"text":"申請書の下書きを","reading":"しんせいしょのしたがきを"}],"after":[{"text":"、消していた。","reading":"、けしていた。"}],"translation":"反复写申请书的草稿，写了又擦掉。","review":"approved"},
  {"id":"usage:tewa:verb:話す:はなす","senseId":"verb:話す:はなす","meaning":"说；交谈","form":"tewa","scene":"爷爷常说起年轻时的往事，怀念地笑起来。","before":[{"text":"祖父は若い頃のことを","reading":"そふはわかいころのことを"}],"after":[{"text":"、懐かしそうに笑った。","reading":"、なつかしそうにわらった。"}],"translation":"爷爷常说起年轻时的往事，每次都露出怀念的笑容。","review":"approved"},
  {"id":"usage:tewa:verb:死ぬ:しぬ","senseId":"verb:死ぬ:しぬ","meaning":"死亡","form":"tewa","scene":"游戏里角色反复阵亡，玩家一次次重新开始。","before":[{"text":"このゲームでは、キャラクターが","reading":"このゲームでは、キャラクターが"}],"after":[{"text":"、プレイヤーは最初からやり直す。","reading":"、プレイヤーはさいしょからやりなおす。"}],"translation":"在这款游戏里，角色一次次阵亡，玩家便一次次从头再来。","review":"approved"},
  {"id":"usage:tewa:verb:分かる:わかる","senseId":"verb:分かる:わかる","meaning":"明白","form":"tewa","scene":"研究时弄懂新知识便高兴，遇到瓶颈又沮丧。","before":[{"text":"研究では、新しいことが","reading":"けんきゅうでは、あたらしいことが"}],"after":[{"text":"、喜び、行き詰まっては落ち込んだ。","reading":"、よろこび、いきづまってはおちこんだ。"}],"translation":"研究时，每弄懂新的事情便高兴，遇到瓶颈又沮丧，反复如此。","review":"approved"},
  {"id":"usage:tewa:verb:見る:みる","senseId":"verb:見る:みる","meaning":"看","form":"tewa","scene":"约好的朋友迟迟未到，他反复看表叹气。","before":[{"text":"彼は待ち合わせの間、時計を","reading":"かれはまちあわせのあいだ、とけいを"}],"after":[{"text":"、ため息をついた。","reading":"、ためいきをついた。"}],"translation":"他等人碰面时，总是看了看表又叹气。","review":"approved"},
  {"id":"usage:tewa:verb:来る:くる","senseId":"verb:来る:くる","meaning":"来","form":"tewa","scene":"朋友周末常来家里，每次都聊到夜里。","before":[{"text":"友達は週末に家に","reading":"ともだちはしゅうまつにいえに"}],"after":[{"text":"、夜まで話していく。","reading":"、よるまではなしていく。"}],"translation":"朋友周末常来家里，每次都聊到夜里才走。","review":"approved"}
];
