// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:tari:verb:扱う:あつかう","senseId":"verb:扱う:あつかう","meaning":"对待","form":"tari","scene":"朋友总爱替我做主，还把我当作孩子。","before":[{"text":"彼は私を子どものように","reading":"かれはわたしをこどものように"}],"after":[{"text":"、勝手に予定を決めたりする。","reading":"、かってによていをきめたりする。"}],"translation":"他有时把我当孩子对待，也会擅自决定安排。","review":"approved"},
  {"id":"usage:tari:verb:嫌う:きらう","senseId":"verb:嫌う:きらう","meaning":"讨厌","form":"tari","scene":"这只猫讨厌陌生人，也躲开吵闹的声音。","before":[{"text":"この猫は知らない人を","reading":"このねこはしらないひとを"}],"after":[{"text":"、大きな音を避けたりする。","reading":"、おおきなおとをさけたりする。"}],"translation":"这只猫会讨厌陌生人，也会躲避大的声响。","review":"approved"},
  {"id":"usage:tari:verb:祝う:いわう","senseId":"verb:祝う:いわう","meaning":"庆祝","form":"tari","scene":"家人庆祝生日，也会为新工作的开始举杯。","before":[{"text":"家族の誕生日を","reading":"かぞくのたんじょうびを"}],"after":[{"text":"、新しい仕事の門出に乾杯したりする。","reading":"、あたらしいしごとのかどでにかんぱいしたりする。"}],"translation":"会庆祝家人的生日，也会为新工作的开始举杯之类。","review":"approved"},
  {"id":"usage:tewa:verb:降りる:おりる","senseId":"verb:降りる:おりる","meaning":"下车；下来","form":"tewa","scene":"坐火车旅行时一站站下车，拍摄车站留念。","before":[{"text":"鉄道の旅では、各駅で","reading":"てつどうのたびでは、かくえきで"}],"after":[{"text":"、駅の写真を撮った。","reading":"、えきのしゃしんをとった。"}],"translation":"坐火车旅行时，每到一站下车，就拍摄车站的照片。","review":"approved"},
  {"id":"usage:tewa:verb:伝える:つたえる","senseId":"verb:伝える:つたえる","meaning":"传达","form":"tewa","scene":"负责人通知一项变更，团队马上重新安排工作。","before":[{"text":"担当者が変更を一つ","reading":"たんとうしゃがへんこうをひとつ"}],"after":[{"text":"、皆が予定を組み直す。","reading":"、みんながよていをくみなおす。"}],"translation":"负责人每传达一项变更，大家就重新安排计划。","review":"approved"},
  {"id":"usage:tewa:verb:壊れる:こわれる","senseId":"verb:壊れる:こわれる","meaning":"坏；损坏","form":"tewa","scene":"旧机器三天两头坏，修好后又继续运转。","before":[{"text":"古い機械が","reading":"ふるいきかいが"}],"after":[{"text":"、修理されてまた動き出した。","reading":"、しゅうりされてまたうごきだした。"}],"translation":"旧机器坏了又修，修好后再次运转，反复如此。","review":"approved"},
  {"id":"usage:tewa:verb:落ちる:おちる","senseId":"verb:落ちる:おちる","meaning":"掉落","form":"tewa","scene":"树上的果实掉下来一个，孩子就捡起一个。","before":[{"text":"木の実が一つ","reading":"きのみがひとつ"}],"after":[{"text":"、子どもが拾う。","reading":"、こどもがひろう。"}],"translation":"树上的果实掉下一个，孩子就捡起一个。","review":"approved"},
  {"id":"usage:tewa:verb:変える:かえる","senseId":"verb:変える:かえる","meaning":"改变","form":"tewa","scene":"他调整一次路线，就重新查看地图。","before":[{"text":"道順を","reading":"みちじゅんを"}],"after":[{"text":"、地図を確認し直す。","reading":"、ちずをかくにんしなおす。"}],"translation":"他每改变一次路线，就重新核对地图。","review":"approved"},
  {"id":"usage:tewa:verb:片付ける:かたづける","senseId":"verb:片付ける:かたづける","meaning":"收拾；整理","form":"tewa","scene":"收拾完一张桌子又去整理下一张，房间逐渐整齐。","before":[{"text":"机を一つ","reading":"つくえをひとつ"}],"after":[{"text":"、次の机に移る。","reading":"、つぎのつくえにうつる。"}],"translation":"他每收拾完一张桌子，就转向下一张。","review":"approved"},
  {"id":"usage:tewa:verb:誘う:さそう","senseId":"verb:誘う:さそう","meaning":"邀请","form":"tewa","scene":"她逐个邀请同事吃饭，每次都问对方哪天有空。","before":[{"text":"彼女は同僚を食事に","reading":"かのじょはどうりょうをしょくじに"}],"after":[{"text":"、都合のいい日を聞いた。","reading":"、つごうのいいひをきいた。"}],"translation":"她每邀请同事吃饭，就问对方哪天有空。","review":"approved"},
  {"id":"usage:tewa:verb:扱う:あつかう","senseId":"verb:扱う:あつかう","meaning":"对待","form":"tewa","scene":"他总把朋友当小孩，反复惹得对方生气。","before":[{"text":"彼は友達を子どものように","reading":"かれはともだちをこどものように"}],"after":[{"text":"、怒らせていた。","reading":"、おこらせていた。"}],"translation":"他总把朋友当小孩对待，一次次惹对方生气。","review":"approved"},
  {"id":"usage:tewa:verb:嫌う:きらう","senseId":"verb:嫌う:きらう","meaning":"讨厌","form":"tewa","scene":"他总因为讨厌新上司而换工作，一再如此。","before":[{"text":"彼は新しい上司を","reading":"かれはあたらしいじょうしを"}],"after":[{"text":"、別の会社に移った。","reading":"、べつのかいしゃにうつった。"}],"translation":"他每次讨厌新上司，就又换一家公司。","review":"approved"},
  {"id":"usage:tewa:verb:祝う:いわう","senseId":"verb:祝う:いわう","meaning":"庆祝","form":"tewa","scene":"家里过生日总要拍合照，一年年积累了许多。","before":[{"text":"家族は誕生日を","reading":"かぞくはたんじょうびを"}],"after":[{"text":"、記念写真を撮ってきた。","reading":"、きねんしゃしんをとってきた。"}],"translation":"家人每次庆祝生日，都拍纪念照，一直如此。","review":"approved"}
];
