// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:tari:verb:売る:うる","senseId":"verb:売る:うる","meaning":"售卖","form":"tari","scene":"市集里卖蔬菜，也介绍自家果酱。","before":[{"text":"市場では野菜を","reading":"いちばではやさいを"}],"after":[{"text":"、手作りのジャムを紹介したりする。","reading":"、てづくりのジャムをしょうかいしたりする。"}],"translation":"在市场会卖蔬菜，也会介绍自制果酱。","review":"approved"},
  {"id":"usage:tari:verb:言う:いう","senseId":"verb:言う:いう","meaning":"说","form":"tari","scene":"讨论时提出意见，也回应别人的问题。","before":[{"text":"会議では自分の意見を","reading":"かいぎではじぶんのいけんを"}],"after":[{"text":"、質問に答えたりする。","reading":"、しつもんにこたえたりする。"}],"translation":"开会时会说出自己的意见，也会回答问题。","review":"approved"},
  {"id":"usage:tari:verb:払う:はらう","senseId":"verb:払う:はらう","meaning":"支付","form":"tari","scene":"结账时付现金，也使用手机支付。","before":[{"text":"会計では現金で","reading":"かいけいではげんきんで"}],"after":[{"text":"、電子決済を使ったりする。","reading":"、でんしけっさいをつかったりする。"}],"translation":"结账时会付现金，也会用电子支付。","review":"approved"},
  {"id":"usage:tari:verb:手伝う:てつだう","senseId":"verb:手伝う:てつだう","meaning":"帮忙","form":"tari","scene":"周末帮家人搬家，也整理旧物。","before":[{"text":"週末は家族の引っ越しを","reading":"しゅうまつはかぞくのひっこしを"}],"after":[{"text":"、古い荷物を整理したりする。","reading":"、ふるいにもつをせいりしたりする。"}],"translation":"周末会帮家人搬家，也会整理旧行李。","review":"approved"},
  {"id":"usage:tari:verb:拾う:ひろう","senseId":"verb:拾う:ひろう","meaning":"捡；拾","form":"tari","scene":"在海边散步时，捡贝壳也收集漂木。","before":[{"text":"浜辺で貝殻を","reading":"はまべでかいがらを"}],"after":[{"text":"、流木を集めたりする。","reading":"、りゅうぼくをあつめたりする。"}],"translation":"会在海边捡贝壳、收集漂木之类。","review":"approved"},
  {"id":"usage:tari:verb:違う:ちがう","senseId":"verb:違う:ちがう","meaning":"不同；不对","form":"tari","scene":"和朋友对答案，有些相同，有些不一样。","before":[{"text":"問題によって、友達と答えが","reading":"もんだいによって、ともだちとこたえが"}],"after":[{"text":"、同じだったりする。","reading":"、おなじだったりする。"}],"translation":"有的题和朋友的答案不同，有的题答案相同。","review":"approved"},
  {"id":"usage:tari:verb:描く:えがく","senseId":"verb:描く:えがく","meaning":"描绘","form":"tari","scene":"画画时描绘风景，也设计人物形象。","before":[{"text":"風景を","reading":"ふうけいを"}],"after":[{"text":"、人物像を考えたりする。","reading":"、じんぶつぞうをかんがえたりする。"}],"translation":"会描绘风景，也会构思人物形象之类。","review":"approved"},
  {"id":"usage:tari:verb:着く:つく","senseId":"verb:着く:つく","meaning":"到达","form":"tari","scene":"旅途中时间难以掌握，有时早到有时误车。","before":[{"text":"旅では、予定より早く駅に","reading":"たびでは、よていよりはやくえきに"}],"after":[{"text":"、電車に乗り遅れたりすることもある。","reading":"、でんしゃにのりおくれたりすることもある。"}],"translation":"旅途中有时会比计划早到车站，有时也会没赶上电车。","review":"approved"},
  {"id":"usage:tari:verb:泣く:なく","senseId":"verb:泣く:なく","meaning":"哭","form":"tari","scene":"电影感人时会哭，也会被温暖的结局逗笑。","before":[{"text":"映画を見て","reading":"えいがをみて"}],"after":[{"text":"、結末で笑ったりする。","reading":"、けつまつでわらったりする。"}],"translation":"看电影时会哭，也会因结局而笑。","review":"approved"},
  {"id":"usage:tari:verb:磨く:みがく","senseId":"verb:磨く:みがく","meaning":"刷；磨","form":"tari","scene":"说起睡前习惯，会刷牙也会洗脸。","before":[{"text":"寝る前は歯を","reading":"ねるまえははを"}],"after":[{"text":"、顔を洗ったりする。","reading":"、かおをあらったりする。"}],"translation":"睡前会刷牙、洗脸之类。","review":"approved"},
  {"id":"usage:tari:verb:開く:あく","senseId":"verb:開く:あく","meaning":"打开；开放","form":"tari","scene":"大风天门窗松动，有的被吹开，有的关上。","before":[{"text":"風の強い日は、窓が","reading":"かぜのつよいひは、まどが"}],"after":[{"text":"、ドアが閉まったりする。","reading":"、ドアがしまったりする。"}],"translation":"风大的日子，窗户会打开，门也会关上。","review":"approved"},
  {"id":"usage:tari:verb:防ぐ:ふせぐ","senseId":"verb:防ぐ:ふせぐ","meaning":"防止","form":"tari","scene":"雨季采取措施防灾，也检查排水沟。","before":[{"text":"雨季は浸水を","reading":"うきはしんすいを"}],"after":[{"text":"、排水溝を掃除したりする。","reading":"、はいすいこうをそうじしたりする。"}],"translation":"雨季会防止进水，也会清扫排水沟。","review":"approved"},
  {"id":"usage:tari:verb:出す:だす","senseId":"verb:出す:だす","meaning":"拿出；提交","form":"tari","scene":"申请时提交表格，也附上必要的证明。","before":[{"text":"申請では書類を","reading":"しんせいではしょるいを"}],"after":[{"text":"、証明書を添えたりする。","reading":"、しょうめいしょをそえたりする。"}],"translation":"申请时会提交文件，也会附上证明材料。","review":"approved"},
  {"id":"usage:tari:verb:渡す:わたす","senseId":"verb:渡す:わたす","meaning":"交给","form":"tari","scene":"交接工作时递交钥匙，也交代注意事项。","before":[{"text":"引き継ぎでは鍵を","reading":"ひきつぎではかぎを"}],"after":[{"text":"、注意点を説明したりする。","reading":"、ちゅういてんをせつめいしたりする。"}],"translation":"交接时会交出钥匙，也会说明注意事项。","review":"approved"},
  {"id":"usage:tewa:verb:買う:かう","senseId":"verb:買う:かう","meaning":"购买","form":"tewa","scene":"她喜欢买新衣，每次买回就照镜子试穿。","before":[{"text":"彼女は服を","reading":"かのじょはふくを"}],"after":[{"text":"、鏡の前で着てみる。","reading":"、かがみのまえできてみる。"}],"translation":"她常买衣服，每次买来就对着镜子试穿。","review":"approved"},
  {"id":"usage:tewa:verb:泳ぐ:およぐ","senseId":"verb:泳ぐ:およぐ","meaning":"游泳","form":"tewa","scene":"训练时反复游到泳池边，再稍作休息。","before":[{"text":"選手はプールの端まで","reading":"せんしゅはプールのはしまで"}],"after":[{"text":"、少し休んだ。","reading":"、すこしやすんだ。"}],"translation":"选手游到泳池边就休息一会儿，反复如此。","review":"approved"}
];
