// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:tewa:verb:楽しむ:たのしむ","senseId":"verb:楽しむ:たのしむ","meaning":"享受；期待","form":"tewa","scene":"他度假时多次泡温泉，每次泡完就回房休息。","before":[{"text":"彼は温泉を","reading":"かれはおんせんを"}],"after":[{"text":"、部屋に戻って休んだ。","reading":"、へやにもどってやすんだ。"}],"translation":"他享受过温泉就回房休息，反复如此。","review":"approved"},
  {"id":"usage:tewa:verb:申し込む:もうしこむ","senseId":"verb:申し込む:もうしこむ","meaning":"申请；报名","form":"tewa","scene":"她常报名新课程，每报一门就把安排写进手账。","before":[{"text":"彼女は新しい講座に","reading":"かのじょはあたらしいこうざに"}],"after":[{"text":"、予定を手帳に書き込んだ。","reading":"、よていをてちょうにかきこんだ。"}],"translation":"她常报名新课程，每次都把安排记到手账上。","review":"approved"},
  {"id":"usage:tewa:verb:始まる:はじまる","senseId":"verb:始まる:はじまる","meaning":"开始","form":"tewa","scene":"会议开始又被打断，主持人反复重新开场。","before":[{"text":"会議が","reading":"かいぎが"}],"after":[{"text":"、また中断される。","reading":"、またちゅうだんされる。"}],"translation":"会议一次次开始，又一次次被打断。","review":"approved"},
  {"id":"usage:tewa:verb:戻る:もどる","senseId":"verb:戻る:もどる","meaning":"返回","form":"tewa","scene":"他出门后总不放心，一次次折回检查门锁。","before":[{"text":"彼は何度も家に","reading":"かれはなんどもいえに"}],"after":[{"text":"、戸締まりを確かめた。","reading":"、とじまりをたしかめた。"}],"translation":"他一次次返回家中，检查门窗是否锁好。","review":"approved"},
  {"id":"usage:tewa:verb:困る:こまる","senseId":"verb:困る:こまる","meaning":"为难；困扰","form":"tewa","scene":"新同事常在工作中遇到困难，每次都找前辈。","before":[{"text":"仕事で","reading":"しごとで"}],"after":[{"text":"、先輩の席へ相談に行った。","reading":"、せんぱいのせきへそうだんにいった。"}],"translation":"工作上一遇到困难，就到前辈的座位那里请教，反复如此。","review":"approved"},
  {"id":"usage:tewa:verb:渡る:わたる","senseId":"verb:渡る:わたる","meaning":"渡过","form":"tewa","scene":"走山路时一座座过桥，每过桥就核对位置。","before":[{"text":"山道で小さな橋を","reading":"やまみちでちいさなはしを"}],"after":[{"text":"、地図で現在地を確かめた。","reading":"、ちずでげんざいちをたしかめた。"}],"translation":"在山路上每过一座小桥，就对照地图确认当前位置。","review":"approved"},
  {"id":"usage:tewa:verb:降る:ふる","senseId":"verb:降る:ふる","meaning":"下（雨雪）","form":"tewa","scene":"雨一下就停，没多久又落下来。","before":[{"text":"雨が","reading":"あめが"}],"after":[{"text":"、すぐにやむ。","reading":"、すぐにやむ。"}],"translation":"雨下起来后很快停下，之后又会下。","review":"approved"},
  {"id":"usage:tewa:verb:眠る:ねむる","senseId":"verb:眠る:ねむる","meaning":"睡眠","form":"tewa","scene":"婴儿睡一会儿就醒，夜里反复如此。","before":[{"text":"赤ちゃんが少し","reading":"あかちゃんがすこし"}],"after":[{"text":"、また目を覚ます。","reading":"、まためをさます。"}],"translation":"婴儿总是睡一会儿又醒来。","review":"approved"},
  {"id":"usage:tewa:verb:曲がる:まがる","senseId":"verb:曲がる:まがる","meaning":"转弯；弯曲","form":"tewa","scene":"他在巷子里找店，每转过街角就停下查看。","before":[{"text":"彼は路地の角を","reading":"かれはろじのかどを"}],"after":[{"text":"、立ち止まって辺りを見回した。","reading":"、たちどまってあたりをみまわした。"}],"translation":"他每转过一个巷口，就停下来看看周围。","review":"approved"},
  {"id":"usage:tewa:verb:教える:おしえる","senseId":"verb:教える:おしえる","meaning":"教；告诉","form":"tewa","scene":"老师讲完一个步骤，学生马上练习一遍。","before":[{"text":"先生が手順を一つ","reading":"せんせいがてじゅんをひとつ"}],"after":[{"text":"、学生が練習する。","reading":"、がくせいがれんしゅうする。"}],"translation":"老师每教一个步骤，学生就进行练习。","review":"approved"},
  {"id":"usage:tewa:verb:閉める:しめる","senseId":"verb:閉める:しめる","meaning":"关闭","form":"tewa","scene":"窗外太吵就关窗，屋里热了又打开，来回调整。","before":[{"text":"窓を","reading":"まどを"}],"after":[{"text":"、暑くなってまた開ける。","reading":"、あつくなってまたあける。"}],"translation":"关上窗，热起来又打开，反复如此。","review":"approved"},
  {"id":"usage:tewa:verb:浴びる:あびる","senseId":"verb:浴びる:あびる","meaning":"淋；沐浴","form":"tewa","scene":"水温还没调好，他冲淋一会儿就重新调整。","before":[{"text":"シャワーを少し","reading":"シャワーをすこし"}],"after":[{"text":"、水温を調整した。","reading":"、すいおんをちょうせいした。"}],"translation":"冲淋一会儿就调整水温，反复如此。","review":"approved"},
  {"id":"usage:tewa:verb:覚える:おぼえる","senseId":"verb:覚える:おぼえる","meaning":"记住","form":"tewa","scene":"学习时每记住一个新词，就顺便复习旧词。","before":[{"text":"単語を一つ","reading":"たんごをひとつ"}],"after":[{"text":"、前に習った単語も復習した。","reading":"、まえにならったたんごもふくしゅうした。"}],"translation":"每记住一个单词，就把以前学过的单词也复习一下。","review":"approved"},
  {"id":"usage:tewa:verb:着る:きる","senseId":"verb:着る:きる","meaning":"穿","form":"tewa","scene":"孩子试穿一件外套又换下，反复挑选合身的。","before":[{"text":"上着を一着","reading":"うわぎをいっちゃく"}],"after":[{"text":"、別の服を試す。","reading":"、べつのふくをためす。"}],"translation":"孩子每穿上一件外套，就又试另一件衣服。","review":"approved"},
  {"id":"usage:tewa:verb:調べる:しらべる","senseId":"verb:調べる:しらべる","meaning":"调查","form":"tewa","scene":"他查一个资料就发现新疑点，研究不断深入。","before":[{"text":"資料を一つ","reading":"しりょうをひとつ"}],"after":[{"text":"、新しい疑問点を見つける。","reading":"、あたらしいぎもんてんをみつける。"}],"translation":"他每查一份资料，就又发现新的疑点。","review":"approved"}
];
