// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:tari:verb:弾く:ひく","senseId":"verb:弾く:ひく","meaning":"弹奏","form":"tari","scene":"周末在家弹琴、看书，悠闲度过一天。","before":[{"text":"週末はピアノを","reading":"しゅうまつはピアノを"}],"after":[{"text":"、本を読んだりして過ごします。","reading":"、ほんをよんだりしてすごします。"}],"translation":"周末会弹钢琴、读书，就这样度过。","review":"approved"},
  {"id":"usage:tari:verb:知る:しる","senseId":"verb:知る:しる","meaning":"知道","form":"tari","scene":"旅行时了解当地历史，也会结识新朋友。","before":[{"text":"旅先では土地の歴史を","reading":"たびさきではとちのれきしを"}],"after":[{"text":"、新しい友人ができたりします。","reading":"、あたらしいゆうじんができたりします。"}],"translation":"旅行中会了解到当地的历史，也会交到新朋友。","review":"approved"},
  {"id":"usage:tari:verb:思う:おもう","senseId":"verb:思う:おもう","meaning":"想；认为","form":"tari","scene":"比赛前一会儿自信，一会儿又感到不安。","before":[{"text":"試合の前は勝てると","reading":"しあいのまえはかてると"}],"after":[{"text":"、不安になったりします。","reading":"、ふあんになったりします。"}],"translation":"比赛前有时觉得能赢，有时又感到不安。","review":"approved"},
  {"id":"usage:tari:verb:忘れる:わすれる","senseId":"verb:忘れる:わすれる","meaning":"忘记","form":"tari","scene":"忙起来会忘记约定，也会漏看消息。","before":[{"text":"忙しいと約束を","reading":"いそがしいとやくそくを"}],"after":[{"text":"、連絡を見落としたりします。","reading":"、れんらくをみおとしたりします。"}],"translation":"一忙起来，有时会忘记约定，有时会漏看消息。","review":"approved"},
  {"id":"usage:tari:verb:いる:いる","senseId":"verb:いる:いる","meaning":"在；有（生物）","form":"tari","scene":"常到朋友家找他，却并非每次都在家。","before":[{"text":"友人は家に","reading":"ゆうじんはいえに"}],"after":[{"text":"、いなかったりします。","reading":"、いなかったりします。"}],"translation":"朋友有时在家，有时不在家。","review":"approved"},
  {"id":"usage:tewa:verb:弾く:ひく","senseId":"verb:弾く:ひく","meaning":"弹奏","form":"tewa","scene":"练习钢琴时每弹一段，就核对乐谱。","before":[{"text":"短い曲を","reading":"みじかいきょくを"}],"after":[{"text":"、楽譜を見直す練習を繰り返した。","reading":"、がくふをみなおすれんしゅうをくりかえした。"}],"translation":"反复练习弹短曲，每弹一遍就重新查看乐谱。","review":"approved"},
  {"id":"usage:tewa:verb:知る:しる","senseId":"verb:知る:しる","meaning":"知道","form":"tewa","scene":"采访中不断知道新的事实，随即补充记录。","before":[{"text":"取材で新しい事実を","reading":"しゅざいであたらしいじじつを"}],"after":[{"text":"、記録に書き加えた。","reading":"、きろくにかきくわえた。"}],"translation":"采访中每知道一个新事实，就把它补写进记录。","review":"approved"},
  {"id":"usage:tewa:verb:思う:おもう","senseId":"verb:思う:おもう","meaning":"想；认为","form":"tewa","scene":"总觉得自己做不到，放弃后又重新挑战。","before":[{"text":"自分には無理だと","reading":"じぶんにはむりだと"}],"after":[{"text":"、諦めかけてまた挑戦した。","reading":"、あきらめかけてまたちょうせんした。"}],"translation":"一次次觉得自己做不到，几乎要放弃，却又再次挑战。","review":"approved"},
  {"id":"usage:tewa:verb:寝る:ねる","senseId":"verb:寝る:ねる","meaning":"睡觉","form":"tewa","scene":"发烧卧床那天，睡醒喝点水又继续睡。","before":[{"text":"熱のある日は少し","reading":"ねつのあるひはすこし"}],"after":[{"text":"、目を覚まして水を飲むことを繰り返した。","reading":"、めをさましてみずをのむことをくりかえした。"}],"translation":"发烧那天睡一会儿，就醒来喝点水，如此反复。","review":"approved"},
  {"id":"usage:tewa:verb:忘れる:わすれる","senseId":"verb:忘れる:わすれる","meaning":"忘记","form":"tewa","scene":"常忘带钥匙，只好一次次找家人开门。","before":[{"text":"何度も鍵を","reading":"なんどもかぎを"}],"after":[{"text":"、家族に玄関を開けてもらった。","reading":"、かぞくにげんかんをあけてもらった。"}],"translation":"多次忘带钥匙，每次都请家人开门。","review":"approved"}
];
