// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:tari:verb:並ぶ:ならぶ","senseId":"verb:並ぶ:ならぶ","meaning":"排队；排列","form":"tari","scene":"展会里排队、找座位等候。","before":[{"text":"会場で列に","reading":"かいじょうでれつに"}],"after":[{"text":"、席を探したりする。","reading":"、せきをさがしたりする。"}],"translation":"会在会场排队、找座位之类。","review":"approved"},
  {"id":"usage:tari:verb:喜ぶ:よろこぶ","senseId":"verb:喜ぶ:よろこぶ","meaning":"高兴","form":"tari","scene":"孩子收到礼物后高兴、惊讶。","before":[{"text":"子どもは贈り物を見て","reading":"こどもはおくりものをみて"}],"after":[{"text":"、驚いたりする。","reading":"、おどろいたりする。"}],"translation":"孩子看到礼物后会高兴、惊讶。","review":"approved"},
  {"id":"usage:tari:verb:楽しむ:たのしむ","senseId":"verb:楽しむ:たのしむ","meaning":"享受；期待","form":"tari","scene":"旅行中欣赏风景、拍照留念。","before":[{"text":"旅行では景色を","reading":"りょこうではけしきを"}],"after":[{"text":"、写真を撮ったりする。","reading":"、しゃしんをとったりする。"}],"translation":"旅行时会欣赏风景、拍照之类。","review":"approved"},
  {"id":"usage:tari:verb:申し込む:もうしこむ","senseId":"verb:申し込む:もうしこむ","meaning":"申请；报名","form":"tari","scene":"准备活动时报名、询问细节。","before":[{"text":"イベントに","reading":"イベントに"}],"after":[{"text":"、担当者に問い合わせたりする。","reading":"、たんとうしゃにといあわせたりする。"}],"translation":"会报名参加活动，也会向负责人询问之类。","review":"approved"},
  {"id":"usage:tari:verb:始まる:はじまる","senseId":"verb:始まる:はじまる","meaning":"开始","form":"tari","scene":"演出有时准时开始，有时延期。","before":[{"text":"公演が予定どおり","reading":"こうえんがよていどおり"}],"after":[{"text":"、延期になったりする。","reading":"、えんきになったりする。"}],"translation":"演出有时按计划开始，有时延期。","review":"approved"},
  {"id":"usage:tari:verb:戻る:もどる","senseId":"verb:戻る:もどる","meaning":"返回","form":"tari","scene":"徒步旅行中返回营地、再次出发。","before":[{"text":"山ではテントに","reading":"やまではテントに"}],"after":[{"text":"、また歩き出したりする。","reading":"、またあるきだしたりする。"}],"translation":"在山里会返回帐篷、再次出发之类。","review":"approved"},
  {"id":"usage:tari:verb:困る:こまる","senseId":"verb:困る:こまる","meaning":"为难；困扰","form":"tari","scene":"遇到手续问题时为难、向柜台求助。","before":[{"text":"手続きで","reading":"てつづきで"}],"after":[{"text":"、窓口に相談したりする。","reading":"、まどぐちにそうだんしたりする。"}],"translation":"办理手续时会为难、向窗口咨询之类。","review":"approved"},
  {"id":"usage:tari:verb:渡る:わたる","senseId":"verb:渡る:わたる","meaning":"渡过","form":"tari","scene":"过河时走桥、乘渡船。","before":[{"text":"川を橋で","reading":"かわをはしで"}],"after":[{"text":"、渡し船に乗ったりする。","reading":"、わたしぶねにのったりする。"}],"translation":"过河时会走桥、乘渡船之类。","review":"approved"},
  {"id":"usage:tari:verb:降る:ふる","senseId":"verb:降る:ふる","meaning":"下（雨雪）","form":"tari","scene":"春天天气忽晴忽雨。","before":[{"text":"春は雨が","reading":"はるはあめが"}],"after":[{"text":"、晴れたりする。","reading":"、はれたりする。"}],"translation":"春天有时下雨，有时放晴。","review":"approved"},
  {"id":"usage:tari:verb:眠る:ねむる","senseId":"verb:眠る:ねむる","meaning":"睡眠","form":"tari","scene":"周末在家睡觉、散步放松。","before":[{"text":"休日は","reading":"きゅうじつは"}],"after":[{"text":"、散歩したりする。","reading":"、さんぽしたりする。"}],"translation":"休息日会睡觉、散步之类。","review":"approved"},
  {"id":"usage:tari:verb:要る:いる","senseId":"verb:要る:いる","meaning":"需要","form":"tari","scene":"不同手续要求不同，有的需要身份证明。","before":[{"text":"手続きによって、身分証明書が","reading":"てつづきによって、みぶんしょうめいしょが"}],"after":[{"text":"、写真が必要だったりする。","reading":"、しゃしんがひつようだったりする。"}],"translation":"不同手续有的需要身份证明，有的需要照片。","review":"approved"},
  {"id":"usage:tari:verb:曲がる:まがる","senseId":"verb:曲がる:まがる","meaning":"转弯；弯曲","form":"tari","scene":"山路有弯曲路段，也有笔直路段。","before":[{"text":"山道は","reading":"やまみちは"}],"after":[{"text":"、まっすぐだったりする。","reading":"、まっすぐだったりする。"}],"translation":"山路有的地方弯曲，有的地方笔直。","review":"approved"},
  {"id":"usage:tari:verb:教える:おしえる","senseId":"verb:教える:おしえる","meaning":"教；告诉","form":"tari","scene":"老师讲解语法、回答学生问题。","before":[{"text":"先生は文法を","reading":"せんせいはぶんぽうを"}],"after":[{"text":"、質問に答えたりする。","reading":"、しつもんにこたえたりする。"}],"translation":"老师会讲解语法、回答问题之类。","review":"approved"},
  {"id":"usage:tari:verb:閉める:しめる","senseId":"verb:閉める:しめる","meaning":"关闭","form":"tari","scene":"通风时反复开关窗户。","before":[{"text":"窓を","reading":"まどを"}],"after":[{"text":"、開けたりする。","reading":"、あけたりする。"}],"translation":"会关窗、开窗，反复交替。","review":"approved"},
  {"id":"usage:tari:verb:浴びる:あびる","senseId":"verb:浴びる:あびる","meaning":"淋；沐浴","form":"tari","scene":"运动后洗澡、换上干净衣服。","before":[{"text":"運動の後はシャワーを","reading":"うんどうのあとはシャワーを"}],"after":[{"text":"、着替えたりする。","reading":"、きがえたりする。"}],"translation":"运动后会洗澡、换衣服之类。","review":"approved"},
  {"id":"usage:tari:verb:覚える:おぼえる","senseId":"verb:覚える:おぼえる","meaning":"记住","form":"tari","scene":"学习新词时记住一些、忘掉一些。","before":[{"text":"新しい単語を","reading":"あたらしいたんごを"}],"after":[{"text":"、忘れたりする。","reading":"、わすれたりする。"}],"translation":"会记住新的单词，也会忘掉。","review":"approved"}
];
