// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:tari:verb:迎える:むかえる","senseId":"verb:迎える:むかえる","meaning":"迎接","form":"tari","scene":"接待活动来宾时，在门口迎接并带路。","before":[{"text":"受付では客を","reading":"うけつけではきゃくを"}],"after":[{"text":"、席へ案内したりします。","reading":"、せきへあんないしたりします。"}],"translation":"接待时会迎接客人、带客人入座等。","review":"approved"},
  {"id":"usage:tewa:verb:迎える:むかえる","senseId":"verb:迎える:むかえる","meaning":"迎接","form":"tewa","scene":"来宾陆续到达，迎接后逐位送去座席。","before":[{"text":"係の人は入口で来客を","reading":"かかりのひとはいりぐちでらいきゃくを"}],"after":[{"text":"、席まで案内していた。","reading":"、せきまであんないしていた。"}],"translation":"工作人员在门口一批批迎接来客，再把他们带到座位上。","review":"approved"},
  {"id":"usage:tari:verb:生まれる:うまれる","senseId":"verb:生まれる:うまれる","meaning":"出生","form":"tari","scene":"牧场春天很热闹，有小羊出生也有小牛断奶。","before":[{"text":"春の牧場では子羊が","reading":"はるのぼくじょうではこひつじが"}],"after":[{"text":"、子牛が乳離れしたりします。","reading":"、こうしがちばなれしたりします。"}],"translation":"春天的牧场里，有小羊出生，也有小牛断奶等。","review":"approved"},
  {"id":"usage:tewa:verb:生まれる:うまれる","senseId":"verb:生まれる:うまれる","meaning":"出生","form":"tewa","scene":"产房里婴儿接连出生，护士逐个称重。","before":[{"text":"産院では赤ちゃんが次々と","reading":"さんいんではあかちゃんがつぎつぎと"}],"after":[{"text":"、看護師が体重を量っていた。","reading":"、かんごしがたいじゅうをはかっていた。"}],"translation":"产院里婴儿接连出生，护士每次都会测量新生儿的体重。","review":"approved"},
  {"id":"usage:tari:verb:足りる:たりる","senseId":"verb:足りる:たりる","meaning":"足够","form":"tari","scene":"每天食堂人数不定，饭量时够时不够。","before":[{"text":"用意したご飯は","reading":"よういしたごはんは"}],"after":[{"text":"、足りなかったりします。","reading":"、たりなかったりします。"}],"translation":"准备好的米饭，有时够吃，有时不够。","review":"approved"},
  {"id":"usage:tari:verb:過ぎる:すぎる","senseId":"verb:過ぎる:すぎる","meaning":"经过；超过","form":"tari","scene":"送货时间难预测，有时超过中午才到。","before":[{"text":"配達は正午を","reading":"はいたつはしょうごを"}],"after":[{"text":"、夕方になったりすることもある。","reading":"、ゆうがたになったりすることもある。"}],"translation":"送货有时会过了中午，有时甚至到傍晚。","review":"approved"},
  {"id":"usage:tewa:verb:過ぎる:すぎる","senseId":"verb:過ぎる:すぎる","meaning":"经过；超过","form":"tewa","scene":"电车一站站驶过，他每过一站就确认站名。","before":[{"text":"電車が駅を","reading":"でんしゃがえきを"}],"after":[{"text":"、彼は路線図で駅名を確かめた。","reading":"、かれはろせんずでえきめいをたしかめた。"}],"translation":"电车每经过一座车站，他就对着线路图确认站名。","review":"approved"},
  {"id":"usage:tari:verb:増える:ふえる","senseId":"verb:増える:ふえる","meaning":"增加","form":"tari","scene":"观察海滩鸟群，数量有时增加有时减少。","before":[{"text":"浜辺の鳥の数は","reading":"はまべのとりのかずは"}],"after":[{"text":"、減ったりしています。","reading":"、へったりしています。"}],"translation":"海滩上的鸟时多时少，数量不断变化。","review":"approved"},
  {"id":"usage:tewa:verb:増える:ふえる","senseId":"verb:増える:ふえる","meaning":"增加","form":"tewa","scene":"书越买越多，书架也一次次添置。","before":[{"text":"本が","reading":"ほんが"}],"after":[{"text":"、新しい本棚を買い足していた。","reading":"、あたらしいほんだなをかいたしていた。"}],"translation":"书一次次增加，每次都再添买新的书架。","review":"approved"},
  {"id":"usage:tari:verb:届ける:とどける","senseId":"verb:届ける:とどける","meaning":"送到；申报","form":"tari","scene":"帮独居老人送饭，也陪他们聊聊天。","before":[{"text":"一人暮らしのお年寄りに弁当を","reading":"ひとりぐらしのおとしよりにべんとうを"}],"after":[{"text":"、話し相手になったりしています。","reading":"、はなしあいてになったりしています。"}],"translation":"给独居老人送便当，也陪他们聊天等。","review":"approved"},
  {"id":"usage:tewa:verb:届ける:とどける","senseId":"verb:届ける:とどける","meaning":"送到；申报","form":"tewa","scene":"快递员送完一单，就回车上取下一件。","before":[{"text":"配達員","reading":"はいたついん"},{"text":"は"},{"text":"家","reading":"いえ"},{"text":"に"},{"text":"荷物","reading":"にもつ"},{"text":"を"}],"after":[{"text":"、次の荷物を取りに車へ戻った。","reading":"、つぎのにもつをとりにくるまへもどった。"}],"translation":"快递员每把一件包裹送到住户家，就回车上拿下一件。","review":"approved"},
  {"id":"usage:tari:verb:出かける:でかける","senseId":"verb:出かける:でかける","meaning":"出门","form":"tari","scene":"天气好就去郊外，也会留在家做家务。","before":[{"text":"休日は郊外へ","reading":"きゅうじつはこうがいへ"}],"after":[{"text":"、家で掃除をしたりします。","reading":"、いえでそうじをしたりします。"}],"translation":"休息日会去郊外，也会在家打扫等。","review":"approved"},
  {"id":"usage:tewa:verb:出かける:でかける","senseId":"verb:出かける:でかける","meaning":"出门","form":"tewa","scene":"退休后常带相机出门，回家整理照片。","before":[{"text":"父はカメラを持って","reading":"ちちはカメラをもって"}],"after":[{"text":"、帰宅後に写真を整理していた。","reading":"、きたくごにしゃしんをせいりしていた。"}],"translation":"父亲一次次带着相机出门，每次回家后都整理照片。","review":"approved"},
  {"id":"usage:tari:verb:雇う:やとう","senseId":"verb:雇う:やとう","meaning":"雇用","form":"tari","scene":"店铺旺季雇临时工，也延长营业时间。","before":[{"text":"繁忙期は臨時の店員を","reading":"はんぼうきはりんじのてんいんを"}],"after":[{"text":"、営業時間を延ばしたりします。","reading":"、えいぎょうじかんをのばしたりします。"}],"translation":"旺季会雇临时店员，也会延长营业时间等。","review":"approved"},
  {"id":"usage:tewa:verb:雇う:やとう","senseId":"verb:雇う:やとう","meaning":"雇用","form":"tewa","scene":"小店员工不断离职，店主反复招聘培训。","before":[{"text":"店主は新しい店員を","reading":"てんしゅはあたらしいてんいんを"}],"after":[{"text":"、接客の仕方を一から教えていた。","reading":"、せっきゃくのしかたをいちからおしえていた。"}],"translation":"店主一次次雇用新店员，每次都从头教他们如何接待客人。","review":"approved"},
  {"id":"usage:tari:verb:疑う:うたがう","senseId":"verb:疑う:うたがう","meaning":"怀疑","form":"tari","scene":"调查时质疑证词，也核查相关记录。","before":[{"text":"調査員は証言を","reading":"ちょうさいんはしょうげんを"}],"after":[{"text":"、記録を調べたりした。","reading":"、きろくをしらべたりした。"}],"translation":"调查人员怀疑证词，也查阅了记录等。","review":"approved"},
  {"id":"usage:tewa:verb:疑う:うたがう","senseId":"verb:疑う:うたがう","meaning":"怀疑","form":"tewa","scene":"担心计算出错，结果查过一遍又一遍。","before":[{"text":"自分の計算結果を","reading":"じぶんのけいさんけっかを"}],"after":[{"text":"、最初から計算し直した。","reading":"、さいしょからけいさんしなおした。"}],"translation":"一次次怀疑自己的计算结果，又从头重新计算。","review":"approved"},
  {"id":"usage:tari:verb:からかう:からかう","senseId":"verb:からかう:からかう","meaning":"取笑","form":"tari","scene":"哥哥常取笑弟弟，也故意藏他的玩具。","before":[{"text":"兄は弟を","reading":"あにはおとうとを"}],"after":[{"text":"、おもちゃを隠したりしていた。","reading":"、おもちゃをかくしたりしていた。"}],"translation":"哥哥会取笑弟弟，还会把他的玩具藏起来。","review":"approved"},
  {"id":"usage:tewa:verb:からかう:からかう","senseId":"verb:からかう:からかう","meaning":"取笑","form":"tewa","scene":"哥哥总取笑弟弟，惹哭后再道歉。","before":[{"text":"兄は弟を","reading":"あにはおとうとを"}],"after":[{"text":"、泣かせてしまって謝った。","reading":"、なかせてしまってあやまった。"}],"translation":"哥哥一次次取笑弟弟，把他惹哭后又道歉。","review":"approved"},
  {"id":"usage:tari:verb:追う:おう","senseId":"verb:追う:おう","meaning":"追赶","form":"tari","scene":"牧羊犬在草地上追赶羊群，也在树下休息。","before":[{"text":"牧羊犬は羊を","reading":"ぼくようけんはひつじを"}],"after":[{"text":"、木陰で休んだりしていた。","reading":"、こかげでやすんだりしていた。"}],"translation":"牧羊犬追赶羊群，也在树荫下休息等。","review":"approved"},
  {"id":"usage:tewa:verb:追う:おう","senseId":"verb:追う:おう","meaning":"追赶","form":"tewa","scene":"小狗不停追球，每次捡回又等人抛出。","before":[{"text":"子犬は投げたボールを","reading":"こいぬはなげたボールを"}],"after":[{"text":"、くわえて戻ってきた。","reading":"、くわえてもどってきた。"}],"translation":"小狗一次次追赶抛出去的球，又把球叼回来。","review":"approved"}
];
