// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:tewa:verb:払う:はらう","senseId":"verb:払う:はらう","meaning":"支付","form":"tewa","scene":"一天在城里多次停车，缴费后又开车离开。","before":[{"text":"街のあちこちで駐車料金を","reading":"まちのあちこちでちゅうしゃりょうきんを"}],"after":[{"text":"、また車を出した。","reading":"、またくるまをだした。"}],"translation":"在城里各处付了停车费，又开车离开，反复如此。","review":"approved"},
  {"id":"usage:tewa:verb:手伝う:てつだう","senseId":"verb:手伝う:てつだう","meaning":"帮忙","form":"tewa","scene":"他帮一点就换下一个任务，工作轮番进行。","before":[{"text":"作業を少し","reading":"さぎょうをすこし"}],"after":[{"text":"、別の作業に移る。","reading":"、べつのさぎょうにうつる。"}],"translation":"他帮忙做一点就转去做另一项工作。","review":"approved"},
  {"id":"usage:tewa:verb:拾う:ひろう","senseId":"verb:拾う:ひろう","meaning":"捡；拾","form":"tewa","scene":"清扫时捡起垃圾又发现新的，海滩仍未干净。","before":[{"text":"ごみを一つずつ","reading":"ごみをひとつずつ"}],"after":[{"text":"、新しいごみを見つける。","reading":"、あたらしいごみをみつける。"}],"translation":"他一个个捡起垃圾，又发现新的垃圾。","review":"approved"},
  {"id":"usage:tewa:verb:描く:えがく","senseId":"verb:描く:えがく","meaning":"描绘","form":"tewa","scene":"画家每画一幅风景，就给朋友看并听取意见。","before":[{"text":"画家は風景を","reading":"がかはふうけいを"}],"after":[{"text":"、友達に見せて感想を聞いた。","reading":"、ともだちにみせてかんそうをきいた。"}],"translation":"画家每画一幅风景，就给朋友看并询问感想。","review":"approved"},
  {"id":"usage:tewa:verb:着く:つく","senseId":"verb:着く:つく","meaning":"到达","form":"tewa","scene":"列车沿途停靠，每到下一站就有人上下车。","before":[{"text":"列車が次の駅に","reading":"れっしゃがつぎのえきに"}],"after":[{"text":"、乗客が乗り降りする。","reading":"、じょうきゃくがのりおりする。"}],"translation":"列车每到下一站，就有乘客上下车。","review":"approved"},
  {"id":"usage:tewa:verb:泣く:なく","senseId":"verb:泣く:なく","meaning":"哭","form":"tewa","scene":"婴儿反复哭闹，母亲总是哄他平静下来。","before":[{"text":"赤ちゃんがしばらく","reading":"あかちゃんがしばらく"}],"after":[{"text":"、母にあやされて泣きやんだ。","reading":"、ははにあやされてなきやんだ。"}],"translation":"婴儿哭一阵，就在母亲的哄慰下停止哭泣，反复如此。","review":"approved"},
  {"id":"usage:tewa:verb:磨く:みがく","senseId":"verb:磨く:みがく","meaning":"刷；磨","form":"tewa","scene":"工匠反复打磨银器，每磨一遍就举到光下检查。","before":[{"text":"職人は銀の器を","reading":"しょくにんはぎんのうつわを"}],"after":[{"text":"、光にかざして確かめた。","reading":"、ひかりにかざしてたしかめた。"}],"translation":"工匠反复打磨银器，每磨一遍就举到光下检查。","review":"approved"},
  {"id":"usage:tewa:verb:開く:あく","senseId":"verb:開く:あく","meaning":"打开；开放","form":"tewa","scene":"风一吹窗户就开，家人不断把它关上。","before":[{"text":"風が吹くたびに窓が","reading":"かぜがふくたびにまどが"}],"after":[{"text":"、家族が閉め直す。","reading":"、かぞくがしめなおす。"}],"translation":"每当风吹得窗户打开，家人就重新关上。","review":"approved"},
  {"id":"usage:tewa:verb:防ぐ:ふせぐ","senseId":"verb:防ぐ:ふせぐ","meaning":"防止","form":"tewa","scene":"比赛中对方不断进攻，选手挡住后迅速反击。","before":[{"text":"選手は相手の攻撃を","reading":"せんしゅはあいてのこうげきを"}],"after":[{"text":"、素早く反撃した。","reading":"、すばやくはんげきした。"}],"translation":"选手每次挡住对方的攻击，就迅速反击。","review":"approved"},
  {"id":"usage:tewa:verb:出す:だす","senseId":"verb:出す:だす","meaning":"拿出；提交","form":"tewa","scene":"报告交了一版又一版，每次被要求修改重写。","before":[{"text":"彼は報告書を","reading":"かれはほうこくしょを"}],"after":[{"text":"、修正を求められて書き直した。","reading":"、しゅうせいをもとめられてかきなおした。"}],"translation":"他每次提交报告，都会被要求修改，于是又重写。","review":"approved"},
  {"id":"usage:tewa:verb:渡す:わたす","senseId":"verb:渡す:わたす","meaning":"交给","form":"tewa","scene":"柜台前顾客排着队，递完商品就叫下一位。","before":[{"text":"店員は客に商品を","reading":"てんいんはきゃくにしょうひんを"}],"after":[{"text":"、次の客を呼んだ。","reading":"、つぎのきゃくをよんだ。"}],"translation":"店员每把商品交给一位顾客，就叫下一位。","review":"approved"},
  {"id":"usage:tari:verb:押す:おす","senseId":"verb:押す:おす","meaning":"按；推","form":"tari","scene":"调试机器时，按按钮也拨动操纵杆。","before":[{"text":"機械のボタンを","reading":"きかいのボタンを"}],"after":[{"text":"、レバーを動かしたりする。","reading":"、レバーをうごかしたりする。"}],"translation":"会按机器上的按钮，也会拨动操纵杆之类。","review":"approved"},
  {"id":"usage:tari:verb:落とす:おとす","senseId":"verb:落とす:おとす","meaning":"弄掉；丢失","form":"tari","scene":"工作时一慌张，就会掉笔、把文件撒到地上。","before":[{"text":"慌てると、ペンを","reading":"あわてると、ペンを"}],"after":[{"text":"、書類を床に散らしたりする。","reading":"、しょるいをゆかにちらしたりする。"}],"translation":"一慌张，就会弄掉笔，或把文件撒到地上之类。","review":"approved"},
  {"id":"usage:tari:verb:起こす:おこす","senseId":"verb:起こす:おこす","meaning":"叫醒；引起","form":"tari","scene":"早晨叫醒孩子，也提醒他准备上学。","before":[{"text":"朝は子どもを","reading":"あさはこどもを"}],"after":[{"text":"、出発を促したりする。","reading":"、しゅっぱつをうながしたりする。"}],"translation":"早晨会叫醒孩子，也会催他出发。","review":"approved"},
  {"id":"usage:tari:verb:役立つ:やくだつ","senseId":"verb:役立つ:やくだつ","meaning":"有用；起作用","form":"tari","scene":"学到的地理知识，旅行和聊天时都能用上。","before":[{"text":"この知識は旅行で","reading":"このちしきはりょこうで"}],"after":[{"text":"、人","reading":"、ひと"},{"text":"と話すきっかけになったりする。","reading":"とはなすきっかけになったりする。"}],"translation":"这些知识会在旅行中派上用场，也会成为与人交谈的契机。","review":"approved"}
];
