// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:tewa:verb:続ける:つづける","senseId":"verb:続ける:つづける","meaning":"继续","form":"tewa","scene":"训练时连续练十分钟再短暂休息，循环进行。","before":[{"text":"練習を十分間","reading":"れんしゅうをじゅっぷんかん"}],"after":[{"text":"、短い休憩を取った。","reading":"、みじかいきゅうけいをとった。"}],"translation":"每连续练习十分钟，就短暂休息一下，反复如此。","review":"approved"},
  {"id":"usage:tewa:verb:助ける:たすける","senseId":"verb:助ける:たすける","meaning":"帮助","form":"tewa","scene":"车站员工不断帮乘客解决困难，再返回服务台。","before":[{"text":"彼は困っている乗客を","reading":"かれはこまっているじょうきゃくを"}],"after":[{"text":"、案内所に戻った。","reading":"、あんないじょにもどった。"}],"translation":"他每帮助一位遇到困难的乘客，就返回服务台。","review":"approved"},
  {"id":"usage:tewa:verb:できる:できる","senseId":"verb:できる:できる","meaning":"能够；完成","form":"tewa","scene":"工坊接连做出作品，每完成一件就摆到架上。","before":[{"text":"工房では作品が一つ","reading":"こうぼうではさくひんがひとつ"}],"after":[{"text":"、展示棚に並べられていった。","reading":"、てんじだなにならべられていった。"}],"translation":"工坊里每完成一件作品，就把它摆上展示架。","review":"approved"},
  {"id":"usage:tewa:verb:答える:こたえる","senseId":"verb:答える:こたえる","meaning":"回答","form":"tewa","scene":"他回答一个问题后，马上又面对新的提问。","before":[{"text":"質問に一つずつ","reading":"しつもんにひとつずつ"}],"after":[{"text":"、次の質問を受ける。","reading":"、つぎのしつもんをうける。"}],"translation":"他逐个回答问题，又接到下一个问题。","review":"approved"},
  {"id":"usage:tewa:verb:止める:とめる","senseId":"verb:止める:とめる","meaning":"停止；阻止","form":"tewa","scene":"他停机检查零件，再重新开动，反复排查故障。","before":[{"text":"機械を","reading":"きかいを"}],"after":[{"text":"、部品を点検してまた動かす。","reading":"、ぶひんをてんけんしてまたうごかす。"}],"translation":"他停下机器，检查零件后重新开动，反复如此。","review":"approved"},
  {"id":"usage:tewa:verb:受ける:うける","senseId":"verb:受ける:うける","meaning":"接受；参加","form":"tewa","scene":"求职时多次面试，每次都把问答内容记下来。","before":[{"text":"彼女は面接を","reading":"かのじょはめんせつを"}],"after":[{"text":"、質問と自分の答えをノートにまとめた。","reading":"、しつもんとじぶんのこたえをノートにまとめた。"}],"translation":"她每参加一次面试，就把问题和自己的回答整理到笔记本里。","review":"approved"},
  {"id":"usage:tewa:verb:集める:あつめる","senseId":"verb:集める:あつめる","meaning":"收集","form":"tewa","scene":"研究者陆续收集数据，每收一批就整理成表。","before":[{"text":"研究者はデータを","reading":"けんきゅうしゃはデータを"}],"after":[{"text":"、表に整理した。","reading":"、ひょうにせいりした。"}],"translation":"研究者每收集一批数据，就整理成表。","review":"approved"},
  {"id":"usage:tewa:verb:疲れる:つかれる","senseId":"verb:疲れる:つかれる","meaning":"疲劳","form":"tewa","scene":"他在山路上反复停下休息，累了就去树荫下。","before":[{"text":"山道で","reading":"やまみちで"}],"after":[{"text":"、木陰で休んだ。","reading":"、こかげでやすんだ。"}],"translation":"在山路上，每次累了就到树荫下休息。","review":"approved"},
  {"id":"usage:tari:verb:降りる:おりる","senseId":"verb:降りる:おりる","meaning":"下车；下来","form":"tari","scene":"旅行途中下车换乘，也会在站台买饮料。","before":[{"text":"旅の途中で","reading":"たびのとちゅうで"},{"text":"電車を","reading":"でんしゃを"}],"after":[{"text":"、飲み物を買ったりする。","reading":"、のみものをかったりする。"}],"translation":"旅行途中会下电车，也会买饮料之类。","review":"approved"},
  {"id":"usage:tari:verb:伝える:つたえる","senseId":"verb:伝える:つたえる","meaning":"传达","form":"tari","scene":"开会时传达决定，也把后续安排告诉成员。","before":[{"text":"決定をメンバーに","reading":"けっていをメンバーに"}],"after":[{"text":"、予定を知らせたりする。","reading":"、よていをしらせたりする。"}],"translation":"会把决定传达给成员，也会告知安排之类。","review":"approved"},
  {"id":"usage:tari:verb:壊れる:こわれる","senseId":"verb:壊れる:こわれる","meaning":"坏；损坏","form":"tari","scene":"旧设备有时坏掉，有时只是运行变慢。","before":[{"text":"古い機械が","reading":"ふるいきかいが"}],"after":[{"text":"、動作が遅くなったりする。","reading":"、どうさがおそくなったりする。"}],"translation":"旧机器有时会坏掉，有时会运行变慢。","review":"approved"},
  {"id":"usage:tari:verb:似る:にる","senseId":"verb:似る:にる","meaning":"相似","form":"tari","scene":"观察不同兄弟，有的长相相似，有的完全不同。","before":[{"text":"兄弟でも、顔が","reading":"きょうだいでも、かおが"}],"after":[{"text":"、まったく違ったりする。","reading":"、まったくちがったりする。"}],"translation":"即使是兄弟，长相也有相似的，有完全不同的。","review":"approved"},
  {"id":"usage:tari:verb:落ちる:おちる","senseId":"verb:落ちる:おちる","meaning":"掉落","form":"tari","scene":"秋天院子里叶子落下，树枝也随风晃动。","before":[{"text":"秋には葉が","reading":"あきにははが"}],"after":[{"text":"、風が枝を揺らしたりする。","reading":"、かぜがえだをゆらしたりする。"}],"translation":"秋天叶子会掉落，风也会吹动树枝之类。","review":"approved"},
  {"id":"usage:tari:verb:変える:かえる","senseId":"verb:変える:かえる","meaning":"改变","form":"tari","scene":"项目推进时调整计划，也会重新分配工作。","before":[{"text":"計画を","reading":"けいかくを"}],"after":[{"text":"、役割を見直したりする。","reading":"、やくわりをみなおしたりする。"}],"translation":"会改变计划，也会重新审视分工之类。","review":"approved"},
  {"id":"usage:tari:verb:片付ける:かたづける","senseId":"verb:片付ける:かたづける","meaning":"收拾；整理","form":"tari","scene":"打扫房间时，收拾书桌也把衣服收起来。","before":[{"text":"部屋では机を","reading":"へやではつくえを"}],"after":[{"text":"、服をしまったりする。","reading":"、ふくをしまったりする。"}],"translation":"会在房间里收拾书桌，也会收好衣服之类。","review":"approved"},
  {"id":"usage:tari:verb:誘う:さそう","senseId":"verb:誘う:さそう","meaning":"邀请","form":"tari","scene":"周末邀请朋友看展，也和同事一起吃饭。","before":[{"text":"友達を展覧会に","reading":"ともだちをてんらんかいに"}],"after":[{"text":"、同僚と食事をしたりする。","reading":"、どうりょうとしょくじをしたりする。"}],"translation":"会邀请朋友看展，也会和同事一起吃饭之类。","review":"approved"}
];
