// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:tewa:verb:飲む:のむ","senseId":"verb:飲む:のむ","meaning":"喝","form":"tewa","scene":"他工作时反复喝咖啡，喝一些就再添一些。","before":[{"text":"彼は仕事中にコーヒーを","reading":"かれはしごとちゅうにコーヒーを"}],"after":[{"text":"、また注ぎ足す。","reading":"、またつぎたす。"}],"translation":"他工作时总是喝了咖啡又续上。","review":"approved"},
  {"id":"usage:tewa:verb:帰る:かえる","senseId":"verb:帰る:かえる","meaning":"回去","form":"tewa","scene":"他休息时常回老家，每次都吃母亲做的菜。","before":[{"text":"休みには実家に","reading":"やすみにはじっかに"}],"after":[{"text":"、母の料理を楽しんだ。","reading":"、ははのりょうりをたのしんだ。"}],"translation":"休息时常回老家，每次都享用母亲做的饭菜。","review":"approved"},
  {"id":"usage:tewa:verb:呼ぶ:よぶ","senseId":"verb:呼ぶ:よぶ","meaning":"呼叫","form":"tewa","scene":"点名时老师逐个叫学生名字，确认回应。","before":[{"text":"先生が生徒の名前を","reading":"せんせいがせいとのなまえを"}],"after":[{"text":"、返事を確かめる。","reading":"、へんじをたしかめる。"}],"translation":"老师每叫一个学生的名字，就确认一下回应。","review":"approved"},
  {"id":"usage:tewa:verb:取る:とる","senseId":"verb:取る:とる","meaning":"拿取","form":"tewa","scene":"他拿起工具又放回去，始终没有决定。","before":[{"text":"工具を","reading":"こうぐを"}],"after":[{"text":"、また棚に戻す。","reading":"、またたなにもどす。"}],"translation":"他反复拿起工具，又放回架子上。","review":"approved"},
  {"id":"usage:tewa:verb:歌う:うたう","senseId":"verb:歌う:うたう","meaning":"唱歌","form":"tewa","scene":"孩子唱一段就停下来，反复练习新歌。","before":[{"text":"子どもは一節ずつ","reading":"こどもはひとふしずつ"}],"after":[{"text":"、音程を確かめる。","reading":"、おんていをたしかめる。"}],"translation":"孩子每唱一段，就确认一下音准。","review":"approved"},
  {"id":"usage:tewa:verb:笑う:わらう","senseId":"verb:笑う:わらう","meaning":"笑","form":"tewa","scene":"聚会上他笑得开心，不时拍拍旁边的朋友。","before":[{"text":"彼は大声で","reading":"かれはおおごえで"}],"after":[{"text":"、隣の友達の肩をたたいた。","reading":"、となりのともだちのかたをたたいた。"}],"translation":"他不时放声大笑，随即拍拍旁边朋友的肩膀。","review":"approved"},
  {"id":"usage:tewa:verb:歩く:あるく","senseId":"verb:歩く:あるく","meaning":"走路","form":"tewa","scene":"他走几步就停下确认地图，进度十分缓慢。","before":[{"text":"道を数歩","reading":"みちをすうほ"}],"after":[{"text":"、地図を見直す。","reading":"、ちずをみなおす。"}],"translation":"他走几步就重新查看地图。","review":"approved"},
  {"id":"usage:tewa:verb:脱ぐ:ぬぐ","senseId":"verb:脱ぐ:ぬぐ","meaning":"脱下","form":"tewa","scene":"孩子每天自己脱外套，然后把衣服叠好。","before":[{"text":"子どもは毎日、上着を","reading":"こどもはまいにち、うわぎを"}],"after":[{"text":"、自分で畳んでいる。","reading":"、じぶんでたたんでいる。"}],"translation":"孩子每天都在脱下外套后自己叠好。","review":"approved"},
  {"id":"usage:tewa:verb:貸す:かす","senseId":"verb:貸す:かす","meaning":"借出","form":"tewa","scene":"常借书给朋友，每次还回来都会询问感想。","before":[{"text":"友達に本を","reading":"ともだちにほんを"}],"after":[{"text":"、返ってくると感想を聞いていた。","reading":"、かえってくるとかんそうをきいていた。"}],"translation":"常把书借给朋友，书还回来时便问问感想。","review":"approved"},
  {"id":"usage:tewa:verb:持つ:もつ","senseId":"verb:持つ:もつ","meaning":"持有","form":"tewa","scene":"挑选提包时，一个个拿在手里比较重量。","before":[{"text":"いろいろなかばんを","reading":"いろいろなかばんを"}],"after":[{"text":"、重さを比べた。","reading":"、おもさをくらべた。"}],"translation":"把不同的包拿在手里，逐个比较重量。","review":"approved"},
  {"id":"usage:tewa:verb:選ぶ:えらぶ","senseId":"verb:選ぶ:えらぶ","meaning":"选择","form":"tewa","scene":"她选定一件衣服又换掉，始终拿不定主意。","before":[{"text":"服を一着","reading":"ふくをいっちゃく"}],"after":[{"text":"、別の服に替える。","reading":"、べつのふくにかえる。"}],"translation":"她总是选中一件衣服又换成另一件。","review":"approved"},
  {"id":"usage:tewa:verb:住む:すむ","senseId":"verb:住む:すむ","meaning":"居住","form":"tewa","scene":"他们搬到不同城市又离开，生活地点不断改变。","before":[{"text":"新しい町に","reading":"あたらしいまちに"}],"after":[{"text":"、また別の町へ移る。","reading":"、またべつのまちへうつる。"}],"translation":"他们总是住进一个新城镇，又搬到另一个城镇。","review":"approved"},
  {"id":"usage:tewa:verb:走る:はしる","senseId":"verb:走る:はしる","meaning":"奔跑","form":"tewa","scene":"运动员反复跑圈，每跑一圈就喝水。","before":[{"text":"練習中は一周","reading":"れんしゅうちゅうはいっしゅう"}],"after":[{"text":"、水を飲む。","reading":"、みずをのむ。"}],"translation":"训练时每跑一圈就喝水。","review":"approved"},
  {"id":"usage:tewa:verb:入る:はいる","senseId":"verb:入る:はいる","meaning":"进入","form":"tewa","scene":"她逛街比价，一家家进店，看完价格就走。","before":[{"text":"彼女はいろいろな店に","reading":"かのじょはいろいろなみせに"}],"after":[{"text":"、値段を見てすぐに出てきた。","reading":"、ねだんをみてすぐにでてきた。"}],"translation":"她一家家进店，总是看了价格就马上出来。","review":"approved"},
  {"id":"usage:tewa:verb:売る:うる","senseId":"verb:売る:うる","meaning":"售卖","form":"tewa","scene":"摊主不断卖苹果，每卖掉就从箱里补上。","before":[{"text":"店主はりんごを","reading":"てんしゅはりんごを"}],"after":[{"text":"、箱からりんごを補充する。","reading":"、はこからりんごをほじゅうする。"}],"translation":"店主卖出苹果后，就从箱子里补货，反复如此。","review":"approved"},
  {"id":"usage:tewa:verb:言う:いう","senseId":"verb:言う:いう","meaning":"说","form":"tewa","scene":"他爱讲笑话，每次讲完自己就先笑起来。","before":[{"text":"彼は冗談を","reading":"かれはじょうだんを"}],"after":[{"text":"、自分で笑っていた。","reading":"、じぶんでわらっていた。"}],"translation":"他总是说了笑话又自己笑起来。","review":"approved"}
];
