// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:nakute:verb:書く:かく","senseId":"verb:書く:かく","meaning":"写；书写","form":"nakute","scene":"报名表漏了姓名，申请被退回了","before":[{"text":"申込書に名前を","reading":"もうしこみしょになまえを"}],"after":[{"text":"、書類を返された。","reading":"、しょるいをかえされた。"}],"translation":"因为没有在申请表上写名字，材料被退回了。","review":"approved"},
  {"id":"usage:nakute:verb:話す:はなす","senseId":"verb:話す:はなす","meaning":"说；交谈","form":"nakute","scene":"朋友一直不说原因，让人担心","before":[{"text":"彼が理由を","reading":"かれがりゆうを"}],"after":[{"text":"、私は心配になった。","reading":"、わたしはしんぱいになった。"}],"translation":"他没有说原因，我担心起来了。","review":"approved"},
  {"id":"usage:nakute:verb:死ぬ:しぬ","senseId":"verb:死ぬ:しぬ","meaning":"死亡","form":"nakute","scene":"病重的小狗活了下来，大家放心了","before":[{"text":"犬が","reading":"いぬが"}],"after":[{"text":"、家族はほっとした。","reading":"、かぞくはほっとした。"}],"translation":"狗没有死，家人松了口气。","review":"approved"},
  {"id":"usage:nakute:verb:分かる:わかる","senseId":"verb:分かる:わかる","meaning":"明白","form":"nakute","scene":"看不懂说明，困在售票机前","before":[{"text":"券売機の使い方が","reading":"けんばいきのつかいかたが"}],"after":[{"text":"、困っている。","reading":"、こまっている。"}],"translation":"不明白售票机的使用方法，正为此犯难。","review":"approved"},
  {"id":"usage:nakute:verb:寝る:ねる","senseId":"verb:寝る:ねる","meaning":"睡觉","form":"nakute","scene":"孩子不肯睡觉，妈妈十分为难","before":[{"text":"赤ちゃんがなかなか","reading":"あかちゃんがなかなか"}],"after":[{"text":"、母は困っていた。","reading":"、はははこまっていた。"}],"translation":"宝宝迟迟不睡觉，妈妈很为难。","review":"approved"},
  {"id":"usage:nakute:verb:来る:くる","senseId":"verb:来る:くる","meaning":"来","form":"nakute","scene":"约好的朋友迟迟没来，让人担心","before":[{"text":"約束の時間になっても友達が","reading":"やくそくのじかんになってもともだちが"}],"after":[{"text":"、心配になった。","reading":"、しんぱいになった。"}],"translation":"到了约定时间朋友也没来，我担心起来了。","review":"approved"},
  {"id":"usage:naide:verb:書く:かく","senseId":"verb:書く:かく","meaning":"写；书写","form":"naide","scene":"老师让学生先口头回答问题","before":[{"text":"答えを紙に","reading":"こたえをかみに"}],"after":[{"text":"、声に出して言ってください。","reading":"、こえにだしていってください。"}],"translation":"请不要把答案写在纸上，请说出声来。","review":"approved"},
  {"id":"usage:naide:verb:話す:はなす","senseId":"verb:話す:はなす","meaning":"说；交谈","form":"naide","scene":"两人整路沉默地并肩走回家","before":[{"text":"二人は何も","reading":"ふたりはなにも"}],"after":[{"text":"、並んで家まで歩いた。","reading":"、ならんでいえまであるいた。"}],"translation":"两人什么也没说，并肩走回了家。","review":"approved"},
  {"id":"usage:naide:verb:分かる:わかる","senseId":"verb:分かる:わかる","meaning":"明白","form":"naide","scene":"没弄懂规则就开始玩这个游戏","before":[{"text":"ルールがよく","reading":"ルールがよく"}],"after":[{"text":"、ゲームを始めてしまった。","reading":"、ゲームをはじめてしまった。"}],"translation":"没怎么弄明白规则，就开始玩游戏了。","review":"approved"},
  {"id":"usage:naide:verb:寝る:ねる","senseId":"verb:寝る:ねる","meaning":"睡觉","form":"naide","scene":"昨晚通宵准备今天的考试","before":[{"text":"昨夜は","reading":"さくやは"}],"after":[{"text":"、試験の勉強をした。","reading":"、しけんのべんきょうをした。"}],"translation":"昨晚没睡觉，复习了考试内容。","review":"approved"},
  {"id":"usage:naide:verb:来る:くる","senseId":"verb:来る:くる","meaning":"来","form":"naide","scene":"生病的同事今天从家里参会","before":[{"text":"田中さんは会社に","reading":"たなかさんはかいしゃに"}],"after":[{"text":"、自宅から会議に参加した。","reading":"、じたくからかいぎにさんかした。"}],"translation":"田中没有来公司，而是从家里参加了会议。","review":"approved"},
  {"id":"usage:zu:verb:話す:はなす","senseId":"verb:話す:はなす","meaning":"说；交谈","form":"zu","scene":"会议中负责人先听取各方意见","before":[{"text":"責任者は自分の意見を","reading":"せきにんしゃはじぶんのいけんを"}],"after":[{"text":"、全員の話を聞いた。","reading":"、ぜんいんのはなしをきいた。"}],"translation":"负责人没有说自己的意见，听了所有人的发言。","review":"approved"},
  {"id":"usage:zu:verb:死ぬ:しぬ","senseId":"verb:死ぬ:しぬ","meaning":"死亡","form":"zu","scene":"受伤的野鸟在照料下活了下来","before":[{"text":"傷ついた鳥は","reading":"きずついたとりは"}],"after":[{"text":"、翌月には空へ飛び立った。","reading":"、よくげつにはそらへとびたった。"}],"translation":"受伤的鸟没有死，到了下个月便飞上了天空。","review":"approved"},
  {"id":"usage:zu:verb:分かる:わかる","senseId":"verb:分かる:わかる","meaning":"明白","form":"zu","scene":"游客不懂当地语言，只好比画","before":[{"text":"言葉が","reading":"ことばが"}],"after":[{"text":"、身ぶりで道を尋ねた。","reading":"、みぶりでみちをたずねた。"}],"translation":"不懂语言，用手势问了路。","review":"approved"},
  {"id":"usage:zu:verb:寝る:ねる","senseId":"verb:寝る:ねる","meaning":"睡觉","form":"zu","scene":"医生整夜守着病情不稳的患者","before":[{"text":"医師は一晩","reading":"いしはひとばん"}],"after":[{"text":"、患者のそばにいた。","reading":"、かんじゃのそばにいた。"}],"translation":"医生一晚没睡，守在患者身边。","review":"approved"},
  {"id":"usage:zu:verb:来る:くる","senseId":"verb:来る:くる","meaning":"来","form":"zu","scene":"约好的采访对象临时缺席了","before":[{"text":"取材相手は会場に","reading":"しゅざいあいてはかいじょうに"}],"after":[{"text":"、電話で質問に答えた。","reading":"、でんわでしつもんにこたえた。"}],"translation":"采访对象没有来到会场，通过电话回答了问题。","review":"approved"},
  {"id":"usage:zuni:verb:書く:かく","senseId":"verb:書く:かく","meaning":"写；书写","form":"zuni","scene":"寄信时忘了在信封上写地址","before":[{"text":"封筒に住所を","reading":"ふうとうにじゅうしょを"}],"after":[{"text":"、手紙を出してしまった。","reading":"、てがみをだしてしまった。"}],"translation":"没在信封上写地址，就把信寄出去了。","review":"approved"},
  {"id":"usage:zuni:verb:話す:はなす","senseId":"verb:話す:はなす","meaning":"说；交谈","form":"zuni","scene":"转学前没有向朋友提起这件事","before":[{"text":"友人には転校のことを","reading":"ゆうじんにはてんこうのことを"}],"after":[{"text":"、町を去った。","reading":"、まちをさった。"}],"translation":"没有向朋友提起转学的事，就离开了小镇。","review":"approved"},
  {"id":"usage:zuni:verb:死ぬ:しぬ","senseId":"verb:死ぬ:しぬ","meaning":"死亡","form":"zuni","scene":"玩家这次顺利走到了关卡终点","before":[{"text":"今回は一度も","reading":"こんかいはいちども"}],"after":[{"text":"、最後の部屋まで進んだ。","reading":"、さいごのへやまですすんだ。"}],"translation":"这次一次也没死，走到了最后的房间。","review":"approved"},
  {"id":"usage:zuni:verb:分かる:わかる","senseId":"verb:分かる:わかる","meaning":"明白","form":"zuni","scene":"没弄懂问题就选了一个答案","before":[{"text":"問題の意味が","reading":"もんだいのいみが"}],"after":[{"text":"、適当に答えを選んだ。","reading":"、てきとうにこたえをえらんだ。"}],"translation":"没弄懂题目的意思，就随便选了个答案。","review":"approved"},
  {"id":"usage:zuni:verb:寝る:ねる","senseId":"verb:寝る:ねる","meaning":"睡觉","form":"zuni","scene":"为了截稿日期通宵完成原稿","before":[{"text":"一晩","reading":"ひとばん"}],"after":[{"text":"、原稿を書き上げた。","reading":"、げんこうをかきあげた。"}],"translation":"一晚没睡，把原稿写完了。","review":"approved"}
];
