// Reviewed exact sense/form cards. See docs/usage-card-linking-audit.md.
export default [
  {"id":"usage:nakute:verb:弾く:ひく","senseId":"verb:弾く:ひく","meaning":"弹奏","form":"nakute","scene":"今天不弹琴，好让手指休息。","before":[{"text":"今日はピアノを","reading":"きょうはピアノを"}],"after":[{"text":"、指の痛みが引いた。","reading":"、ゆびのいたみがひいた。"}],"translation":"今天没有弹钢琴，手指的疼痛缓解了。","review":"approved"},
  {"id":"usage:naide:verb:弾く:ひく","senseId":"verb:弾く:ひく","meaning":"弹奏","form":"naide","scene":"练习开始时先听老师演奏。","before":[{"text":"まずピアノを","reading":"まずピアノを"}],"after":[{"text":"、先生の演奏を聴いた。","reading":"、せんせいのえんそうをきいた。"}],"translation":"先不弹钢琴，听了老师的演奏。","review":"approved"},
  {"id":"usage:zu:verb:弾く:ひく","senseId":"verb:弾く:ひく","meaning":"弹奏","form":"zu","scene":"夜深了，他没有弹琴便收拾乐谱。","before":[{"text":"彼は夜遅く、ピアノを","reading":"かれはよるおそく、ピアノを"}],"after":[{"text":"、楽譜を片づけた。","reading":"、がくふをかたづけた。"}],"translation":"深夜，他没有弹钢琴，收拾了乐谱。","review":"approved"},
  {"id":"usage:zuni:verb:弾く:ひく","senseId":"verb:弾く:ひく","meaning":"弹奏","form":"zuni","scene":"演出前不弹琴，避免手指疲劳。","before":[{"text":"本番前はピアノを","reading":"ほんばんまえはピアノを"}],"after":[{"text":"、指を休めておく。","reading":"、ゆびをやすめておく。"}],"translation":"正式演出前不弹钢琴，让手指先休息。","review":"approved"},
  {"id":"usage:nakute:verb:知る:しる","senseId":"verb:知る:しる","meaning":"知道","form":"nakute","scene":"不了解情况，竟对他说了失礼的话。","before":[{"text":"事情を","reading":"じじょうを"}],"after":[{"text":"、彼に失礼なことを言ってしまった。","reading":"、かれにしつれいなことをいってしまった。"}],"translation":"因为不了解情况，竟对他说了失礼的话。","review":"approved"},
  {"id":"usage:nakute:verb:思う:おもう","senseId":"verb:思う:おもう","meaning":"想；认为","form":"nakute","scene":"事情比预想中更早结束，感到惊讶。","before":[{"text":"こんなに早く終わるとは","reading":"こんなにはやくおわるとは"}],"after":[{"text":"、驚いた。","reading":"、おどろいた。"}],"translation":"没想到这么快就结束了，吃了一惊。","review":"approved"},
  {"id":"usage:nakute:verb:忘れる:わすれる","senseId":"verb:忘れる:わすれる","meaning":"忘记","form":"nakute","scene":"朋友一直记得约定，自己很开心。","before":[{"text":"彼が約束を","reading":"かれがやくそくを"}],"after":[{"text":"、うれしかった。","reading":"、うれしかった。"}],"translation":"他没有忘记约定，我很开心。","review":"approved"},
  {"id":"usage:nakute:verb:いる:いる","senseId":"verb:いる:いる","meaning":"在；有（生物）","form":"nakute","scene":"到窗口办手续时负责人不在。","before":[{"text":"担当者が","reading":"たんとうしゃが"}],"after":[{"text":"、手続きができなかった。","reading":"、てつづきができなかった。"}],"translation":"负责人不在，没能办成手续。","review":"approved"},
  {"id":"usage:naide:verb:知る:しる","senseId":"verb:知る:しる","meaning":"知道","form":"naide","scene":"不了解事情经过就责怪了他。","before":[{"text":"事情を","reading":"じじょうを"}],"after":[{"text":"、彼を責めてしまった。","reading":"、かれをせめてしまった。"}],"translation":"不了解情况就责怪了他。","review":"approved"},
  {"id":"usage:naide:verb:思う:おもう","senseId":"verb:思う:おもう","meaning":"想；认为","form":"naide","scene":"当时说谎，还不觉得这有什么不好。","before":[{"text":"悪いことだと","reading":"わるいことだと"}],"after":[{"text":"、うそをついていた。","reading":"、うそをついていた。"}],"translation":"没觉得这是坏事，就一直在说谎。","review":"approved"},
  {"id":"usage:naide:verb:忘れる:わすれる","senseId":"verb:忘れる:わすれる","meaning":"忘记","form":"naide","scene":"朋友记得约定，准时前来赴约。","before":[{"text":"約束を","reading":"やくそくを"}],"after":[{"text":"、時間どおりに来てくれた。","reading":"、じかんどおりにきてくれた。"}],"translation":"他没有忘记约定，按时来了。","review":"approved"},
  {"id":"usage:naide:verb:いる:いる","senseId":"verb:いる:いる","meaning":"在；有（生物）","form":"naide","scene":"休息日没有待在家，去了公园。","before":[{"text":"休日は家に","reading":"きゅうじつはいえに"}],"after":[{"text":"、公園で過ごした。","reading":"、こうえんですごした。"}],"translation":"休息日没有待在家里，而是在公园度过了。","review":"approved"},
  {"id":"usage:zu:verb:知る:しる","senseId":"verb:知る:しる","meaning":"知道","form":"zu","scene":"不了解真相，却贸然发表了意见。","before":[{"text":"真相を","reading":"しんそうを"}],"after":[{"text":"、不用意に意見を述べた。","reading":"、ふよういにいけんをのべた。"}],"translation":"不了解真相，却贸然发表了意见。","review":"approved"},
  {"id":"usage:zu:verb:思う:おもう","senseId":"verb:思う:おもう","meaning":"想；认为","form":"zu","scene":"没有想到会下雨，出门时没带伞。","before":[{"text":"雨が降るとは","reading":"あめがふるとは"}],"after":[{"text":"、傘を持たずに出かけた。","reading":"、かさをもたずにでかけた。"}],"translation":"没想到会下雨，出门时没有带伞。","review":"approved"},
  {"id":"usage:zu:verb:忘れる:わすれる","senseId":"verb:忘れる:わすれる","meaning":"忘记","form":"zu","scene":"牢记约定，准时来到了会场。","before":[{"text":"約束を","reading":"やくそくを"}],"after":[{"text":"、時間どおりに会場へ来た。","reading":"、じかんどおりにかいじょうへきた。"}],"translation":"没有忘记约定，按时来到了会场。","review":"approved"},
  {"id":"usage:zu:verb:いる:いる","senseId":"verb:いる:いる","meaning":"在；有（生物）","form":"zu","scene":"小说中描述一间寂静无人的屋子。","before":[{"text":"家の中には誰も","reading":"いえのなかにはだれも"}],"after":[{"text":"、辺りは静まり返っていた。","reading":"、あたりはしずまりかえっていた。"}],"translation":"屋里没有任何人，四周一片寂静。","review":"approved","note":"此处使用较书面的叙述语体。"},
  {"id":"usage:zuni:verb:知る:しる","senseId":"verb:知る:しる","meaning":"知道","form":"zuni","scene":"不了解比赛规则就贸然参赛。","before":[{"text":"ルールを","reading":"ルールを"}],"after":[{"text":"、試合に参加してしまった。","reading":"、しあいにさんかしてしまった。"}],"translation":"不了解规则就参加了比赛。","review":"approved"},
  {"id":"usage:zuni:verb:思う:おもう","senseId":"verb:思う:おもう","meaning":"想；认为","form":"zuni","scene":"他把玩笑当真，认真听对方讲。","before":[{"text":"彼は冗談だと","reading":"かれはじょうだんだと"}],"after":[{"text":"、その話を真剣に聞いていた。","reading":"、そのはなしをしんけんにきいていた。"}],"translation":"他没认为那是玩笑，认真听着那番话。","review":"approved"},
  {"id":"usage:zuni:verb:忘れる:わすれる","senseId":"verb:忘れる:わすれる","meaning":"忘记","form":"zuni","scene":"记得带上钥匙，进房间放行李。","before":[{"text":"鍵を持ってくるのを","reading":"かぎをもってくるのを"}],"after":[{"text":"、部屋に入って荷物を置いた。","reading":"、へやにはいってにもつをおいた。"}],"translation":"没有忘记带钥匙来，进房间放下了行李。","review":"approved"},
  {"id":"usage:zuni:verb:いる:いる","senseId":"verb:いる:いる","meaning":"在；有（生物）","form":"zuni","scene":"书面回忆中交代他当时不在家。","before":[{"text":"彼は家に","reading":"かれはいえに"}],"after":[{"text":"、村の集会に出席していた。","reading":"、むらのしゅうかいにしゅっせきしていた。"}],"translation":"他没有待在家里，而是在参加村里的集会。","review":"approved","note":"此处使用较书面的叙述语体。"},
  {"id":"usage:zuni:verb:する:する","senseId":"verb:する:する","meaning":"做","form":"zuni","scene":"没有确认内容，便按下了发送按钮。","before":[{"text":"確認を","reading":"かくにんを"}],"after":[{"text":"、送信ボタンを押した。","reading":"、そうしんボタンをおした。"}],"translation":"没有确认内容，就按下了发送按钮。","review":"approved"}
];
